<html>
    <head>
        <style type="text/css">
            .border_atas {
                border-top: 1px solid black;
                border-collapse: collapse;
            }

            .border_kiri {
                border-left: 1px solid black;
                border-collapse: collapse;
            }

            .border_kanan {
                border-right: 1px solid black;
                border-collapse: collapse;
            }

            .border_bawah {
                border-bottom: 1px solid black;
                border-collapse: collapse;
            }

            .font_besar {
                font-size: 12pt;
            }

            .font_kecil {
                font-size: 10pt;
            }

            .font_lima {
                font-size: 7pt;
            }

            .font_tujuh {
                font-size: 7pt;
            }  

            .font_delapan {
                font-size: 10pt;
            }    

            .font_sembilan {
                font-size: 9pt;
            }   
            table{
                font-family: Arial;
            }
            @page{
                margin: 30px;
                header: html_MyCustomHeader;
                footer: html_MyCustomFooter;
            }
        </style>
    </head>
    <body>
        <?php
        ini_set("max_execution_time", 500);
        include($_SERVER['DOCUMENT_ROOT'] . "/" . $this->basePath() . '/public/barcodecoy/qrlib.php');

        if (!function_exists('kekata')) {

            function kekata($x) {
                $x = abs($x);
                $angka = array("", "Satu", "Dua", "Tiga", "Empat", "Lima",
                    "Enam", "Tujuh", "Delapan", "Sembilan", "Sepuluh", "Sebelas");
                $temp = "";
                if ($x < 12) {
                    $temp = " " . $angka[$x];
                } else if ($x < 20) {
                    $temp = kekata($x - 10) . " Belas";
                } else if ($x < 100) {
                    $temp = kekata($x / 10) . " Puluh" . kekata($x % 10);
                } else if ($x < 200) {
                    $temp = " Seratus" . kekata($x - 100);
                } else if ($x < 1000) {
                    $temp = kekata($x / 100) . " Ratus" . kekata($x % 100);
                } else if ($x < 2000) {
                    $temp = " Seribu" . kekata($x - 1000);
                } else if ($x < 1000000) {
                    $temp = kekata($x / 1000) . " Ribu" . kekata($x % 1000);
                } else if ($x < 1000000000) {
                    $temp = kekata($x / 1000000) . " Juta" . kekata($x % 1000000);
                } else if ($x < 1000000000000) {
                    $temp = kekata($x / 1000000000) . " Milyar" . kekata(fmod($x, 1000000000));
                } else if ($x < 1000000000000000) {
                    $temp = kekata($x / 1000000000000) . " Trilyun" . kekata(fmod($x, 1000000000000));
                }
                return $temp;
            }

        }

        function terbilang($x, $style = 4) {
            if ($x < 0) {
                $hasil = "MINUS " . trim(kekata($x));
            } else {
                $hasil = trim(kekata($x));
            }
            switch ($style) {
                case 1:
                    $hasil = strtoupper($hasil);
                    break;
                case 2:
                    $hasil = strtolower($hasil);
                    break;
                case 3:
                    $hasil = ucwords($hasil);
                    break;
                default:
                    $hasil = ucfirst($hasil);
                    break;
            }
            return $hasil;
        }

        foreach ($this->data as $data) {

            $PNG_TEMP_DIR = $_SERVER['DOCUMENT_ROOT'] . '/' . $this->basePath() . '/public/img_barcode/' .
                    $data['t_idjenisobjek'] . '/' . $data['t_periodepajak'] . '/' .
                    $data['t_idtransaksi'] . '/';

            $PNG_WEB_DIR = $_SERVER['DOCUMENT_ROOT'] . '/' . $this->basePath() . '/public/img_barcode/' .
                    $data['t_idjenisobjek'] . '/' . $data['t_periodepajak'] . '/' .
                    $data['t_idtransaksi'] . '/';

            if (!file_exists($PNG_TEMP_DIR)) {
                mkdir($_SERVER['DOCUMENT_ROOT'] . '/' . $this->basePath() . '/public/img_barcode/' . $data['t_idjenisobjek'] . '/' . $data['t_periodepajak'] . '/' . $data['t_idtransaksi'] . '/', 0777, true);
                chmod($_SERVER['DOCUMENT_ROOT'] . '/' . $this->basePath() . '/public/img_barcode/' . $data['t_idjenisobjek'] . '/', 0777);
                chmod($_SERVER['DOCUMENT_ROOT'] . '/' . $this->basePath() . '/public/img_barcode/' . $data['t_idjenisobjek'] . '/' . $data['t_periodepajak'] . '/', 0777);
                chmod($_SERVER['DOCUMENT_ROOT'] . '/' . $this->basePath() . '/public/img_barcode/' . $data['t_idjenisobjek'] . '/' . $data['t_periodepajak'] . '/' . $data['t_idtransaksi'] . '/', 0777);
            }

            $errorCorrectionLevel = 'L';
            $matrixPointSize = 3;
            $barcode = $data['t_kodebayar'];

            $filename = $PNG_TEMP_DIR . '' . $data['t_idjenisobjek'] . '_' . $data['t_periodepajak'] . '_' . $data['t_idtransaksi'] . '_' . md5($barcode . '|' . $errorCorrectionLevel . '|' . $matrixPointSize) . '.png';
            QRcode::png($barcode, $filename, $errorCorrectionLevel, $matrixPointSize, 2);

            $tampilbarcode = '<img width="70" src="' . $_SERVER['DOCUMENT_ROOT'] . '/' . $this->basePath() . '/public/img_barcode/' . $data['t_idjenisobjek'] . '/' . $data['t_periodepajak'] . '/' . $data['t_idtransaksi'] . '/' . basename($filename) . '" />';

            $abulan = ['01' => 'Januari', '02' => 'Februari', '03' => 'Maret', '04' => 'April', '05' => 'Mei', '06' => 'Juni', '07' => 'Juli', '08' => 'Agustus', '09' => 'September', '10' => 'Oktober', '11' => 'November', '12' => 'Desember'];
            $t_tglpenetapan = date('d', strtotime($data['t_tglpenetapan'])) . " " . $abulan[date('m', strtotime($data['t_tglpenetapan']))] . " " . date('Y', strtotime($data['t_tglpenetapan']));
            ?>
            <div style="height: 100%">
                <table class="border_atas border_bawah border_kanan border_kiri" style="font-size:8pt;width: 100%;">
                    <tr>
                        <td style="width: 7%">
                            <img src="<?= $_SERVER['DOCUMENT_ROOT'] . "" . $this->basePath() . "/" . $ar_pemda->s_logo; ?>" style="width:50px;"  />
                        </td>
                        <td style="width: 33%">
                            <b style="font-size:8pt;">PEMERINTAH KABUPATEN <?= strtoupper($ar_pemda->s_namakabkota) ?></b>
                            <br>
                            <b><?= strtoupper($ar_pemda->s_namainstansi) ?></b>
                            <br>
                            <span style="font-size:7pt;"><?= $ar_pemda->s_alamatinstansi ?>, <?= $ar_pemda->s_namaibukotakabkota ?><br>Telp/Fax <?= $ar_pemda->s_notelinstansi ?></span>
                        </td>
                        <td class="border_kiri" style="width: 40%;text-align:center;">
                            <b style="font-size: 22pt;">SKRD</b> 
                            <br>
                            <b style="font-size: 10pt;">(SURAT KETETAPAN RETRIBUSI DAERAH)</b>
                            <br>
                            Masa : <?= date('d-m-Y', strtotime($data['t_masaawal'])); ?> S/D <?= date('d-m-Y', strtotime($data['t_masaakhir'])); ?>
                            <br>
                            Tahun : <?= $data['t_periodepajak']; ?>
                        </td>
                        <td class="border_kiri" style="width: 20%;text-align:center;">
                            No. SKRD : <?= $data['t_nopenetapan'] ?><br>
                            Kode Bayar<br>
                            <?= $tampilbarcode ?><br>
                            <b><?= $data['t_kodebayar'] ?></b>
                        </td>
                    </tr>
                </table>
                <table class="border_bawah border_kanan border_kiri font_sembilan" style="width: 100%;">
                    <tr>
                        <td style="width: 5%; padding:0; border-spacing:0px; padding-left: 15px; padding-top: 10px;">
                            <b>I</b>
                        </td>
                        <td colspan="2" style="padding:0;border-spacing:0px; padding-top: 10px;">
                            <b>Identitas Wajib Retribusi</b>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                        </td>
                        <td style="padding:0; border-spacing:0px;">
                            NPWRD
                        </td>
                        <td class="border_kanan" style="padding:0;border-spacing:0px;">
                            : <?= $data['t_npwpd'] ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                        </td>
                        <td style="width: 20%; padding:0; border-spacing:0px;">
                            Nama
                        </td>
                        <td style="padding:0;border-spacing:0px;">
                            : <?= $data['t_nama'] ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                        </td>
                        <td style="padding:0; border-spacing:0px;">
                            Alamat
                        </td>
                        <td style="padding:0;border-spacing:0px;">
                            : <?= $data['t_alamat'] . ", Kel./Desa " . $data['s_namakel'] . ", Kec. " . $data['s_namakec'] . ", Kab. " . $data['t_kabupaten'] ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                        </td>
                        <td style="padding:0; border-spacing:0px;">
                            NIOR
                        </td>
                        <td class="border_kanan" style="padding:0;border-spacing:0px;">
                            : <?= $data['t_nop'] ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                        </td>
                        <td style="padding:0; border-spacing:0px;">
                            Nama Objek
                        </td>
                        <td class="border_kanan" style="padding:0;border-spacing:0px;">
                            : <?= $data['t_namaobjek'] ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                        </td>
                        <td style="padding:0; border-spacing:0px;">
                            Alamat Objek
                        </td>
                        <td class="border_kanan" style="padding:0;border-spacing:0px;">
                            : <?= $data['t_alamatobjek'] . ", Kel./Desa " . $data['s_namakelobjek'] . ", Kec. " . $data['s_namakecobjek'] . ", Kab. " . $data['t_kabupatenobjek'] ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:0; border-spacing:0px; padding-left: 15px; padding-bottom: 10px">
                            <b>II</b>
                        </td>
                        <td style="padding:0; border-spacing:0px; padding-bottom: 10px;font-size:9pt;">
                            <b>Tanggal Jatuh Tempo</b>
                        </td>
                        <td class="border_kanan" style="padding:0;border-spacing:0px; padding-bottom: 10px">
                            : <b><?= date('d-m-Y', strtotime($data['t_tgljatuhtempo'])) ?></b>
                        </td>
                    </tr>
                </table>
                <table class="border_bawah border_kanan border_kiri font_sembilan" style="width: 100%;">
                    <tr style="text-align: center">
                        <td class="border_kanan border_kiri" style="padding-top: 10px;">
                            <table style="margin-left: 15px; margin-right: 15px; padding-top: 10px; border: 1px solid black; border-collapse: collapse; width: 100%; margin-bottom: 10px; vertical-align: top">
                                <tr>
                                    <th style="width: 5%; border: 1px solid black; border-collapse: collapse; text-align: center">
                                        No.
                                    </th>
                                    <th style="border: 1px solid black; border-collapse: collapse; text-align: center">
                                        Kode Rekening
                                    </th>
                                    <th style="border: 1px solid black; border-collapse: collapse; text-align: center">
                                        Uraian
                                    </th>
                                    <th style="border: 1px solid black; border-collapse: collapse; text-align: center">
                                        Jumlah (Rp.)
                                    </th>
                                </tr>
                                <tr>
                                    <td style="text-align: center; border: 1px solid black; border-collapse: collapse">
                                        1.
                                    </td>
                                    <td style="border: 1px solid black; border-collapse: collapse;width:20%">
                                        <?= $data['korek'] ?><br>
                                    </td>
                                    <td style="border: 1px solid black; border-collapse: collapse;padding-bottom:50px;">
                                        - <?= strtoupper($data['s_namakorek']) ?><br>
                                        <?php if ($jenisobjek == 16) { ?>
                                            <table width="100%">
                                                <tr><td></td><td></td></tr>
                                            </table>
                                        <?php } ?>
                                    </td>
                                    <td style="border: 1px solid black; border-collapse: collapse; text-align: right">
                                        <?= number_format($data['t_jmlhpajak'], 0, ',', '.'); ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="text-align: center; border: 1px solid black; border-collapse: collapse" colspan="3">
                                        Jumlah Ketetapan Pokok Retribusi
                                    </td>
                                    <td style="border: 1px solid black; border-collapse: collapse; text-align: right">
                                        <?= number_format($data['t_jmlhpajak'], 0, ',', '.'); ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="border: 1px solid black; border-collapse: collapse" colspan="4">
                                        Dengan Huruf : #<i><?= terbilang($data['t_jmlhpajak']); ?> Rupiah</i>#
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                <table class="border_bawah border_kanan border_kiri font_sembilan" style="width: 100%">
                    <tr>
                        <td style="padding-top: 10px; padding-left: 15px" colspan="2">
                            PERHATIAN :
                        </td>
                    </tr>
                    <tr>
                        <td style="width:5%; border-spacing:0px; padding-left: 15px; vertical-align: top">
                            1.
                        </td>
                        <td style="padding:0; border-spacing:0px;">
                            Harap penyetoran dilakukan melalui Kas Daerah No. Rek : <?= $ar_pemda->s_norekbank ?> An : RKUD Kabupaten <?= $ar_pemda->s_namakabkota ?> dengan menggunakan Surat Setoran Retribusi Daerah (SSRD)
                        </td>
                    </tr>
                    <tr>
                        <td style="border-spacing:0px; padding-left: 15px; padding-bottom: 10px; vertical-align: top">
                            2.
                        </td>
                        <td style="padding:0; border-spacing:0px; padding-bottom: 10px">
                            Apabila SKRD ini tidak atau kurang dibayar setelah waktu paling lama 30 hari sejak SKRD ini diterima dikenakan sanksi administrasi
                            berupa bunga sebesar 2% per bulan.
                        </td>
                    </tr>
                </table>
                <table class="border_bawah border_kanan border_kiri font_sembilan" style="width: 100%">
                    <tr>
                        <td style="width: 50%; padding: 10px; padding-left: 15px;vertical-align:bottom;">

                        </td>
                        <td style="text-align: center; padding-top: 10px">
                            <?= $ar_pemda->s_namaibukotakabkota ?>, <?= $t_tglpenetapan ?><br>
                            a.n, Kepala <?= $ar_pemda->s_namainstansi ?><br>
                            <?= strtoupper($ar_ttd0->s_jabatanpej) ?>
                            <br><br><br><br><br><br>
                            <?= $ar_ttd0->s_namapej ?><br>
                            NIP. <?= $ar_ttd0->s_nippej ?>
                        </td>
                    </tr>
                </table>
                <div style="margin-top:10px;margin-bottom:10px;border: 0 none;border-top: 1px dashed #322f32;background: none;height:0;"></div>
                <table class="border_bawah border_kanan border_kiri border_atas" style="width: 100%;font-size:9pt;">
                    <tr>
                        <td colspan="2" style="padding-top: 5px">

                        </td>
                        <td style="text-align: right; padding-top: 5px;padding-right: 20px;">
                            <!--No. SKPD : <b><= str_pad($data['t_nopenetapan'], 5, "0", STR_PAD_LEFT).'/SKPD/'.substr($data['t_kodebayar'],2,2).'/'.date('m', strtotime($data['t_masaawal'])).'/'.$data['t_periodepajak'] ?></b>-->
                            No. SKPD : <?= str_pad($data['t_nopenetapan'], 5, 0, STR_PAD_LEFT) ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" style="text-align: center">
                            <b style="font-size: 14pt;">TANDA TERIMA</b>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 20%;padding-left: 25px;">
                            NPWPD
                        </td>
                        <td style="width: 2%">
                            :
                        </td>
                        <td>
                            <?= $data['t_npwpd'] ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 20%;padding-left: 25px; vertical-align: top;">
                            Nama
                        </td>
                        <td style="width: 2%">
                            :
                        </td>
                        <td>
                            <?= strtoupper($data['t_nama']); ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 20%;padding-left: 25px; vertical-align: top;">
                            Alamat
                        </td>
                        <td style="width: 2%">
                            :
                        </td>
                        <td>
                            <?= strtoupper($data['t_alamat_lengkap']) ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 20%;padding-left: 25px; vertical-align: top;">
                            Nama Objek / Usaha
                        </td>
                        <td style="width: 2%">
                            :
                        </td>
                        <td>
                            <?= strtoupper($data['t_namaobjek']) ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">

                        </td>
                        <td style="text-align: right;padding-right: 30px;">
                            <?= $ar_pemda->s_namaibukotakabkota ?>, 
                            .................................. 20 ...........
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" style="vertical-align:bottom;">
                            <div class="barcodecell"><barcode code="<?= $data['t_kodebayar'] ?>" type="I25" class="barcode" /><br>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-size:8pt;"><?= $data['t_kodebayar'] ?></span></div>
                        </td>
                        <td style="text-align: right;padding-right: 100px;">
                            Yang Menerima
                            <br><br><br><br><br><br>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" style="padding-bottom: 10px">

                        </td>
                        <td style="text-align: right;padding-right: 85px; padding-bottom: 10px">
                            (............................)
                        </td>
                    </tr>
                </table>
            </div>
        <?php } ?>
    <htmlpagefooter name="MyCustomFooter">
        <table style="vertical-align: bottom; font-family:sans-serif;font-size: 7pt;" width="100%">
            <tbody>
                <tr>
                        <!--<td width="33%"><span style="font-weight: bold; font-style: italic;">{DATE j-m-Y}</span></td>-->
                    <td style="font-style: italic;text-align: left;border: 1px solid #fff;" width="50%">Printed by SIMPATDA</td>
                    <td style="font-style: italic;text-align: right;border: 1px solid #fff;" width="50%">Halaman {PAGENO} dari {nbpg}</td>
                </tr>
            </tbody>
        </table>
    </htmlpagefooter>
</body>
</html>

