<div class="tab-pane" id="tab6">
    <div class="example-box-wrapper" style="font-size: 11px">
        <div class="panel-group" id="accordion">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            CETAK LAPORAN DAFTAR PEMBAYARAN
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Tanggal Cetak
                            </label>
                            <div class="col-md-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <input type="text" class="bootstrap-datepicker form-control" name="tglcetak" id="tglcetak"  value="<?= date('d-m-Y') ?>" data-date-format="dd-mm-yy" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Tanggal Pembayaran
                            </label>
                            <div class="col-md-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <input type="text" class="bootstrap-datepicker form-control" name="tglbayar0" id="tglbayar0"  value="<?= date('d-m-Y') ?>" data-date-format="dd-mm-yy" readonly>
                                </div>
                            </div>
                            <label class="col-md-1 control-label" style="text-align: center">s/d</label>
                            <div class="col-md-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <input type="text" class="bootstrap-datepicker form-control" name="tglbayar1" id="tglbayar1"  value="<?= date('d-m-Y') ?>" data-date-format="dd-mm-yy" readonly>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Jenis Pajak
                            </label>
                            <div class="col-md-5">
                                <select name="jenispajak" id="jenispajak" class="form-control">
                                    <option value="">--- PILIH SEMUA ---</option>
                                    <?php foreach ($dataobjek as $row) { ?>
                                        <option value="<?= $row['s_idjenis'] ?>"><?= $row['s_namajenis'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Jenis Ketetapan
                            </label>
                            <div class="col-md-5">
                                <select name="jenisketetapan" id="jenisketetapan" class="form-control">
                                    <option value="">--- PILIH SEMUA ---</option>
                                    <option value="SPTPD/SKPD">SPTPD/SKPD</option>
                                    <option value="SKPDKB">SKPDKB</option>
                                    <option value="SKPDKBT">SKPDKBT</option>
                                    <option value="SKPDT">SKPDT</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Kecamatan
                            </label>
                            <div class="col-md-5">
                                <select name="t_kecamatanobjek" id="t_kecamatanobjek" onchange="comboKelurahanCamat()" class="form-control">
                                    <option value="">--- PILIH KECAMATAN ---</option>
                                    <?php foreach ($ar_kecamatan as $row) { ?>
                                        <option value="<?= $row['s_idkec'] ?>"><?= str_pad($row['s_kodekec'], 2, "0", STR_PAD_LEFT) ?> || <?= $row['s_namakec'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Kelurahan
                            </label>
                            <div class="col-md-5">
                                <select name="t_kelurahanobjek" id="t_kelurahanobjek" class="form-control">
                                    <option value="">--- PILIH KELURAHAN ---</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Mengetahui
                            </label>
                            <div class="col-md-8">
                                <div class="input-prepend input-group">
                                    <select name="idpejabat_set0" id="idpejabat_set0" class="form-control">
                                        <?php foreach ($ar_ttd0 as $row): ?>
                                            <option value="<?= $row['s_idpej'] ?>"><?= $row['s_namapej'] . ' || ' . $row['s_jabatanpej'] ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Pembuat Laporan
                            </label>
                            <div class="col-md-8">
                                <div class="input-prepend input-group">
                                    <select name="idpejabat_set1" id="idpejabat_set1" class="form-control">
                                        <?php foreach ($ar_ttd0 as $row): ?>
                                            <option value="<?= $row['s_idpej'] ?>"><?= $row['s_namapej'] . ' || ' . $row['s_jabatanpej'] ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Format Cetakan
                            </label>
                            <div class="col-md-2">
                                <select name="formatcetak" id="formatcetak" class="form-control">
                                    <option value="pdf">PDF</option>
                                    <option value="excel">EXCEL</option>
                                </select>
                            </div>
                            <div class="col-md-1">
                                <a href="#" class="btn btn-md btn-success pull-left" title="" onclick="cetakpembayaran()"><i class="glyph-icon icon-print"></i> CETAK</a>
                            </div>
                        </div>
                        <div class='col-md-12'> 
                            <label class="col-md-3 control-label">

                            </label>
                            
                            <!-- <div class="col-md-1">
                                <a href="#" class="btn btn-sm btn-primary pull-left" title="" onclick="cetakpembayaranexcel()"><i class="glyph-icon icon-file-excel-o"></i> EXCEL</a>
                            </div> -->
                        </div>              
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function comboKelurahanCamat() {
        $.post('<?= $this->url() ?>/comboKelurahanCamat', {t_kecamatan: $('#t_kecamatanobjek').val()}, function (data) {
            $("#t_kelurahanobjek").html(data);
        });
    }
    
    function cetakpembayaran() {
        window.open('<?= $this->url() ?>/cetakpembayaran?tglcetak=' + $("#tglcetak").val() + "&tglbayar0=" + $("#tglbayar0").val() + "&tglbayar1=" + $("#tglbayar1").val() + "&jenispajak=" + $("#jenispajak").val() + "&jenisketetapan=" + $("#jenisketetapan").val() + "&formatcetak=" + $("#formatcetak").val() + "&kecamatan=" + $("#t_kecamatanobjek").val() + "&kelurahan=" + $("#t_kelurahanobjek").val() + "&diperiksa=" + $("#idpejabat_set1").val() + "&mengetahui=" + $("#idpejabat_set0").val());
    }
    
    function cetakpembayaranexcel() {
        window.open('<?= $this->url() ?>/cetakpembayaranexcel?tglcetak=' + $("#tglcetak").val() + "&tglbayar0=" + $("#tglbayar0").val() + "&tglbayar1=" + $("#tglbayar1").val() + "&jenispajak=" + $("#jenispajak").val() + "&jenisketetapan=" + $("#jenisketetapan").val());
    }
</script>