
<style>
    .dataTables_scrollBody{
        min-height: 250px;  
    }
</style>
<?php
$judul = '<span style="font-size: 24px;"><b>FORM EDIT SKPDT REKLAME</b></span>';
$link = '<div class="pull-right">         
                            <a href="' . $this->url('skpdt') . '" class="btn bg-orange btn-sm btn-flat">
                        <span class="glyphicon glyphicon-refresh"></span>&nbsp;&nbsp;Kembali
                    </a>  
                        </div>';

echo $this->MenuHelper()->headeratas($judul, $link);
?>

<div class="row">
    <div class="col-sm-6">
        <div class="box box-primary" style="border: 1px solid #f39c12;">
            <div class="box-header" style="background-color: #f39c12;">
                <center><h3 class="box-title" style="color: white; font-size: 18px;">DATA PEMILIK</h3></center>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>

            <div class="box-body">


                <div class="col-sm-12">
                    <label class="col-sm-4">Tgl. Pendaftaran</label>
                    <div class="col-md-4">
                        : <?= date('d-m-Y', strtotime($data['t_tgldaftar'])) ?>
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-4">Nama</label>
                    <div class="col-md-4">
                        : <?= $data['t_nama'] ?>
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-4">Alamat</label>
                    <div class="col-md-8">
                        : <?= $data['t_alamat'] ?>
                        ,Desa/Kel. <?= $data['s_namakel'] ?>
                        ,Kec. <?= $data['s_namakec'] ?>
                        ,Kab. <?= $data['t_kabupaten'] ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="box box-primary" style="border: 1px solid #f39c12;">
            <div class="box-header" style="background-color: #f39c12;">
                <center><h3 class="box-title" style="color: white; font-size: 18px;">DATA OBJEK PAJAK</h3></center>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>

            <div class="box-body">


                <div class="col-sm-12">
                    <label class="col-sm-2">Nama</label>
                    <div class="col-sm-4">
                        : <?= $data['t_namaobjek'] ?>
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2">Alamat</label>
                    <div class="col-sm-10">
                        : <?= $data['t_alamatobjek'] ?>
                        ,Desa/Kel. <?= $data['s_namakelobjek'] ?>
                        ,Kec. <?= $data['s_namakecobjek'] ?>
                        ,Kab. <?= $data['t_kabupatenobjek'] ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

 <div class="box box-primary" style="border: 1px solid #337ab7;">
        <div class="box-header" style="background-color: #337ab7;">
            <center><h3 class="box-title" style="color: white; font-size: 18px;">DATA TRANSAKSI</h3></center>
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        <div class="box-body">
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Nomor Urut</label>
                <div class="col-sm-2">                    
                    <input class="form-control" readonly="readonly" style="text-align:right" value="<?= $data['t_nourut'];?>" type="text" readonly="true">                    </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Periode Pajak</label>
                <div class="col-sm-2">
                    <div class="input-prepend input-group">
                        <span class="add-on input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </span>
                        <input class="form-control" value="<?= $data['t_periodepajak'];?>" type="text" readonly="true">                        
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Tanggal Pendataan</label>
                <div class="col-sm-2">
                    <div class="input-prepend input-group">
                        <span class="add-on input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </span>
                        <input class="form-control" value="<?= date('d-m-Y',strtotime($data['t_tglpendataan']));?>" type="text" readonly="true">                        
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Tgl. Penetapan</label>
                <div class="col-sm-2">
                    <div class="input-prepend input-group">
                        <span class="add-on input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </span>
                        <input class="form-control" value="<?= date('d-m-Y',strtotime($data['t_tglpenetapan']));?>" type="text" readonly="true">                        
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Masa Pajak</label>
                <div class="col-sm-2">
                    <div class="input-prepend input-group">
                        <span class="add-on input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </span>
                        <input class="form-control" value="<?= date('d-m-Y',strtotime($data['t_masaawal']));?>" type="text" readonly="true">                        
                    </div>
                </div>
                <label class="col-sm-1 control-label">S/D</label>
                <div class="col-sm-2">
                    <div class="input-prepend input-group">
                        <span class="add-on input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </span>
                        <input class="form-control" value="<?= date('d-m-Y',strtotime($data['t_masaakhir']));?>" type="text" readonly="true">                        
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Kecamatan<span style="color: red">*</span></label>
                <div class="col-md-3">
                    <div class="input-prepend input-group">
                        <span class="add-on input-group-addon">
                            <i class="fa fa-fw fa-globe"></i>
                        </span>
                        <?php $datakecamatan = $this->MenuHelper()->cekkecamatan($data['t_kecamatan_objek_ori']); ?>
                        <input class="form-control" value="<?= $datakecamatan['s_namakec'];?>" type="text" readonly="true">  
                    </div>
                </div>
                <label class="col-sm-1 control-label">Kelurahan<span style="color: red">*</span></label>
                <div class="col-md-3">
                    <div class="input-prepend input-group">
                        <span class="add-on input-group-addon">
                            <i class="fa fa-fw fa-globe"></i>
                        </span>
                        <?php $datakelurahan = $this->MenuHelper()->cekkelurahan($data['t_kelurahan_objek_ori']); ?>
                       <input class="form-control" value="<?= $datakelurahan['s_namakel'];?>" type="text" readonly="true">  
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Nama Naskah</label>
                <div class="col-sm-5">
                    <input class="form-control" value="<?= $data['t_naskah'];?>" readonly="true" type="text">      
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Lokasi</label>
                <div class="col-sm-5">
                    <textarea class="form-control" readonly="true"><?= $data['t_lokasi_reklame'];?></textarea>                    </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Kode Rekening</label>
                <div class="col-sm-2">                    
                    <input class="form-control" value="<?= $data['koderek'];?>" readonly="true"  type="text">                   
                </div>
                
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Nama Rekening</label>
                <div class="col-sm-5">
                    <input class="form-control" value="<?= $data['s_namakorek'];?>" readonly="readonly" type="text">                    </div>
                <label class="col-sm-2 control-label">Tarif (%)</label>
                <div class="col-sm-1">
                    <input  class="form-control" style="text-align:right" readonly="readonly" value="<?= $data['t_tarifpajak'];?>" type="text">                    </div>
            </div>
            <div> <!--'skpdtaktif' => 1-->
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Jenis Lokasi</label>
                    <div class="col-sm-5">
                        <?php 
                        if(!empty($data['t_jenislokasi'])){
                            $datajenislokasi = $this->MenuHelper()->jenislokasi_reklame($data['t_jenislokasi']);
                        }else{
                            $datajenislokasi = array('nama_lokasi' => null);
                        }
                         ?>
                        <input class="form-control" value="<?= $datajenislokasi['nama_lokasi'];?>" readonly="readonly" type="text"> 
                                           
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Kelas Jalan<span style="color: red">*</span></label>
                    <div class="col-md-3">
                        <?php
                            if(!empty($data['t_id_kelas_jalan'])){
                                $datakelasjalan = $this->MenuHelper()->kelasjalan_reklame($data['t_id_kelas_jalan']);
                            }else{
                                $datakelasjalan = array('nama_kelas_jalan' => null);
                            }
                        ?>
                        <input class="form-control" value="<?= $datakelasjalan['nama_kelas_jalan'];?>" readonly="readonly" type="text">                       
                    </div>
                    <label class="col-sm-1 control-label">Sudut Pandang<span style="color: red">*</span></label>
                    <div class="col-md-3">
                        <?php
                            if(!empty($data['t_id_sudut_pandang'])){
                                $datasudutpandang = $this->MenuHelper()->sudutpandang_reklame($data['t_id_sudut_pandang']);
                            }else{
                                $datasudutpandang = array('nama_sudut_pandang' => null);
                            }
                        ?>
                        <input class="form-control" value="<?= $datasudutpandang['nama_sudut_pandang'];?>" readonly="readonly" type="text"> 
                    </div>
                </div>
            </div>        
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Reklame Berupa</label>
                <div class="col-sm-5">
                    <?php
                        if($data['t_berupa_reklame'] == 1){
                            $reklameberupa = 'Bukan minuman keras dan atau rokok';
                        }else{
                            $reklameberupa = 'Minuman keras dan atau rokok';
                        }
                    ?>
                    <input class="form-control" value="<?= $reklameberupa;?>" readonly="readonly" type="text">             
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Pemasangan Reklame</label>
                <div class="col-sm-5">
                    <?php
                        if($data['t_pemasangan_reklame'] == 1){
                            $t_pemasangan_reklame = 'diluar ruang/outdoor';
                        }else{
                            $t_pemasangan_reklame = 'didalam ruang/indoor';
                        }
                    ?>
                    <input class="form-control" value="<?= $t_pemasangan_reklame;?>" readonly="readonly" type="text"> 
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Panjang</label>
                <div class="col-sm-1">
                    <input class="form-control" readonly="readonly" value="<?= $data['t_panjang']; ?>" type="text">                    </div>
                <label class="col-sm-1 control-label">Lebar</label>
                <div class="col-sm-1">
                    <input class="form-control" readonly="readonly" value="<?= $data['t_lebar']; ?>" type="text">                    
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Jumlah</label>
                <div class="col-sm-1">
                    <input class="form-control" readonly="readonly" value="<?= $data['t_jumlah_reklame']; ?>"  type="text">                    
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Jangka Waktu</label>
                <div class="col-sm-1">
                    <input class="form-control" readonly="readonly" value="<?= $data['t_jangkawaktu']; ?>" type="text">                    
                </div>
                <div class="col-sm-2">
                    <input class="form-control" readonly="readonly" value="<?= $data['t_tipewaktu']; ?>" type="text"> 
                    
                </div>
            </div>
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">NSR</label>
                <div class="col-sm-3">
                    <input class="form-control" style="text-align:right" readonly="readonly" value="<?= number_format($data['t_nsr_reklame'], 0, ',', '.'); ?>" type="text">                    
                </div>
                <div class="col-sm-3"></div>
            </div>
            
            <div class="col-sm-12">
                <label class="col-sm-2 control-label">Total Pajak</label>
                <div class="col-sm-4">
                    <input class="form-control" readonly="readonly" style="text-align:right; background:#000099; color: white; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder" value="<?= number_format($data['t_jmlhpajak'], 0, ',', '.'); ?>" type="text">                    
                </div>

            </div>
           
        </div>

   
</div>


<form method="post" action="<?= $this->url('skpdt') ?>/formpemeriksaanskpdtreklameedit/<?= $data['t_idskpdt']; ?>" id="demo-form" class="form-horizontal pad15L pad15R pad15T" data-parsley-validate="data-parsley-validate" enctype="multipart/form-data"><div class="row">
    <div class="col-sm-12">
        <div class="box box-primary" style="border: 1px solid #0073b7;">
            <div class="box-header" style="background-color: #337ab7;">
                <center><h3 class="box-title" style="color: white;font-size: 18px;">FORM PEMERIKSAAN REKLAME [EDIT]</h3></center>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
            </div>
            <div class="box-body">
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Nomor Pemeriksaan</label>
                    <div class="col-sm-2">
                         <input name="t_idpemeriksaan" id="t_idpemeriksaan" value="<?= $data['t_idskpdt']; ?>" type="hidden">  
                        <input name="t_jenisobjekpajak" value="<?= $data['t_jenispajak'] ?>" type="hidden">
                        <input name="t_idtransaksi" id="t_idtransaksi" value="<?= $data['t_idtransaksi'] ?>" type="hidden">                        
                        <input name="t_iddetailreklame" id="t_iddetailreklame" value="" type="hidden">                        
                        <input name="t_idobjek" id="t_idobjek" value="<?= $data['t_idwpobjek'] ?>" type="hidden">                        
                        <input name="t_jenispajak" id="t_jenispajak" value="<?= $data['t_jenispajak'] ?>" type="hidden">                        
                        <input name="t_nopemeriksaan" id="t_nopemeriksaan" class="form-control" required="required" value="<?= $data['t_nopemeriksaan']; ?>" type="text">                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Periode Pajak</label>
                    <div class="col-sm-2">
                        <div class="input-prepend input-group">
                            <span class="add-on input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </span>
                            <input name="t_periodepemeriksaan" id="t_periodepemeriksaan" class="form-control" value="<?= $data['t_periodeskpdt'] ?>" type="text">                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Tanggal Pemeriksaan</label>
                    <div class="col-sm-2">
                        <div class="input-prepend input-group">
                            <span class="add-on input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </span>
                            <input name="t_tglpemeriksaan" id="t_tglpemeriksaan" class="form-control" required="required" value="<?= date('d-m-Y', strtotime($data['t_tglskpdt'])); ?>" type="text">                        </div>
                    </div>
                </div>
                
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Masa Pajak</label>
                    <div class="col-sm-2">
                        <div class="input-prepend input-group">
                            <span class="add-on input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </span>
                            <input name="t_masaawal" id="t_masaawal" class="form-control" required="required" value="<?= date('d-m-Y',strtotime($data['t_masaawal_skpdt']));?>" onkeypress="hitungpajakreklame();" onchange="hitungpajakreklame();" onblur="hitungpajakreklame();" type="text">                        
                        </div>
                    </div>
                    <label class="col-sm-1 control-label">S/D</label>
                    <div class="col-sm-2">
                        <div class="input-prepend input-group">
                            <span class="add-on input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </span>
                            <input name="t_masaakhir" id="t_masaakhir" class="form-control" required="required" value="<?= date('d-m-Y',strtotime($data['t_masaakhir_skpdt']));?>" onkeypress="hitungpajakreklame();" onchange="hitungpajakreklame();" onblur="hitungpajakreklame();" type="text">                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Kecamatan<span style="color: red">*</span></label>
                    <div class="col-md-3">
                        <div class="input-prepend input-group">
                            <span class="add-on input-group-addon">
                                <i class="fa fa-fw fa-globe"></i>
                            </span>
                            <select name="t_kecamatan_objek" id="t_kecamatan_objek" onchange="comboKelurahanCamat()" class="form-control">
                                <option value="">Silahkan Pilih</option>
                                <?php foreach ($this->MenuHelper()->semuadatakecamatan() as $row) {
                                        if($row['s_idkec'] == $data['t_kecamatan_objek']){
                                            $selectkec = 'selected';
                                        }else{
                                            $selectkec = '';
                                        }
                                    
                                    ?>
                                    <option value="<?= $row['s_idkec'] ?>" <?= $selectkec; ?>><?= str_pad($row['s_kodekec'], 2, "0", STR_PAD_LEFT) ?> || <?= $row['s_namakec'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <label class="col-sm-1 control-label">Kelurahan<span style="color: red">*</span></label>
                    <div class="col-md-3">
                        <div class="input-prepend input-group">
                            <span class="add-on input-group-addon">
                                <i class="fa fa-fw fa-globe"></i>
                            </span>
                            <select name="t_kelurahan_objek" id="t_kelurahan_objek" class="form-control" required="required">
                                <option value="">Silahkan Pilih</option>
                                <?php foreach ($this->MenuHelper()->semuadatakelurahan_berdasarkec($data['t_kecamatan_objek']) as $row) {
                                        if($row['s_idkel'] == $data['t_kelurahan_objek']){
                                            $selectkel = 'selected';
                                        }else{
                                            $selectkel = '';
                                        }
                                    
                                    ?>
                                    <option value="<?= $row['s_idkel'] ?>" <?= $selectkel; ?>><?= str_pad($row['s_kodekel'], 2, "0", STR_PAD_LEFT) ?> || <?= $row['s_namakel'] ?></option>
                                <?php } ?>
                            </select>                        
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Nama Naskah</label>
                    <div class="col-sm-5">
                        <input name="t_naskah" id="t_naskah" class="form-control" required="required" value="<?= $data['t_naskah_skpdt']; ?>" type="text">                    
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Lokasi</label>
                    <div class="col-sm-5">
                        <textarea name="t_lokasi_reklame" id="t_lokasi_reklame" class="form-control" required="required"><?= $data['t_lokasi_reklame_skpdt']; ?></textarea>                    
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Kode Rekening</label>
                    <div class="col-sm-2">
                        <input name="t_idkorek" id="t_idkorek" value="<?= $data['t_idkorek']; ?>" type="hidden">                        
                        <input name="t_korek" id="t_korek" class="form-control" required="required" readonly="readonly" value="<?= $data['koderek']; ?>" type="text"> 
                    </div>
                    <div class="col-sm-1"><button type="button" class="btn btn-sm btn-primary" onclick="bukamodalRekening()"><span class="fa fa-search"></span></button></div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Nama Rekening</label>
                    <div class="col-sm-5">
                        <input name="t_namakorek" id="t_namakorek" class="form-control" required="required" readonly="readonly" value="<?= $data['s_namakorek']; ?>" type="text">                    
                    </div>
                    <label class="col-sm-2 control-label">Tarif (%)</label>
                    <div class="col-sm-1">
                        <input name="t_tarifpajak" id="t_tarifpajak" class="form-control" style="text-align:right" readonly="readonly" value="<?= $data['t_tarifpajak']; ?>" type="text">                    
                    </div>
                </div>
                
                <?php
                    if(($data['koderek'] == '4.1.1.04.01.01.00.00') || ($data['koderek'] == '4.1.1.04.01.02.00.00') || ($data['koderek'] == '4.1.1.04.01.03.00.00') || ($data['koderek'] == '4.1.1.04.01.04.00.00') ){
                        $diplayhidden = 'block';
                    }else{
                        $diplayhidden = 'none';
                    }
                
                ?>
                
                <div id="hidden_div" style="display: <?= $diplayhidden; ?>;">
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Jenis Lokasi</label>
                        <div class="col-sm-5">
                            <select name="t_jenislokasi" id="t_jenislokasi" class="form-control" required="required" onkeyup="hitungpajakreklame();" onkeypress="hitungpajakreklame();" onchange="hitungpajakreklame();" onblur="hitungpajakreklame();">
                                <option value="">Silahkan Pilih</option>
                                <?php foreach ($this->MenuHelper()->semuadatalokasireklame() as $row) { 
                                        if($row['id_lokasi_reklame'] == $data['t_jenislokasi_skpdt']){
                                            $selectlok = 'selected';
                                        }else{
                                            $selectlok = '';
                                        }
                                    ?>
                                
                                    <option value="<?= $row['id_lokasi_reklame'] ?>" <?= $selectlok; ?>>(<?= number_format($row['nilai_lokasi'], 0, ',', '.') ?> ) <?= $row['nama_lokasi'] ?></option>
                                <?php } ?>
                                </select>                        
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Kelas Jalan<span style="color: red">*</span></label>
                        <div class="col-md-3">
                                <select name="t_id_kelas_jalan" id="t_id_kelas_jalan" class="form-control" required="required" onchange="comboSudutPandang();"><option value="">Silahkan Pilih</option>
                                <?php foreach ($this->MenuHelper()->semuadatakelasjalan() as $row) { 
                                         if($row['id_kelas_jalan'] == $data['t_id_kelas_jalan_skpdt']){
                                            $selectjln = 'selected';
                                        }else{
                                            $selectjln = '';
                                        }   
                                    ?>
                                    <option value="<?= $row['id_kelas_jalan'] ?>" <?= $selectjln; ?>><?= $row['nama_kelas_jalan'] ?></option>
                                <?php } ?>
                                </select>                        
                        </div>
                        <label class="col-sm-1 control-label">Sudut Pandang<span style="color: red">*</span></label>
                        <div class="col-md-3">
                            <select name="t_id_sudut_pandang" id="t_id_sudut_pandang" class="form-control" required="required" onkeyup="hitungpajakreklame();" onkeypress="hitungpajakreklame();" onchange="hitungpajakreklame();" onblur="hitungpajakreklame();">
                                <?php 
                                    if(!empty($data['t_id_kelas_jalan'])){
                                    foreach ($this->MenuHelper()->semuadata_sudutpandang_berdasarkelasjalan($data['t_id_kelas_jalan']) as $row) { 
                                         if($row['id_sudut_pandang'] == $data['t_id_sudut_pandang_skpdt']){
                                            $selectsp = 'selected';
                                        }else{
                                            $selectsp = '';
                                        }   
                                    ?>
                                    <option value="<?= $row['id_sudut_pandang'] ?>" <?= $selectsp; ?>><?= $row['nama_sudut_pandang'] ?></option>
                                <?php } 
                                    }
                                ?>
                                
                            </select>                        
                        </div>
                    </div>
                </div>        
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Reklame Berupa</label>
                    <div class="col-sm-5">
                        <select name="t_berupa_reklame" id="t_berupa_reklame" class="form-control" required="required" onkeyup="hitungpajakreklame();" onkeypress="hitungpajakreklame();" onchange="hitungpajakreklame();" onblur="hitungpajakreklame();">
                            <option value="1" <?php if($data['t_berupa_reklame_skpdt'] == 1){ echo 'selected';} ?>>Bukan minuman keras dan atau rokok</option>
                            <option value="2" <?php if($data['t_berupa_reklame_skpdt'] == 2){ echo 'selected';} ?>>Minuman keras dan atau rokok</option>
                        </select>                    
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Pemasangan Reklame</label>
                    <div class="col-sm-5">
                        <select name="t_pemasangan_reklame" id="t_pemasangan_reklame" class="form-control" required="required" onkeyup="hitungpajakreklame();" onkeypress="hitungpajakreklame();" onchange="hitungpajakreklame();" onblur="hitungpajakreklame();">
                            <option value="1" <?php if($data['t_pemasangan_reklame_skpdt'] == 1){ echo 'selected';} ?>>diluar ruang/outdoor</option>
                            <option value="2" <?php if($data['t_pemasangan_reklame_skpdt'] == 2){ echo 'selected';} ?>>didalam ruang/indoor</option>
                        </select>                    
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Panjang</label>
                    <div class="col-sm-1">
                        <input name="t_panjang" id="t_panjang" class="form-control" required="required" onkeyup="hitungpajakreklame();" value="<?= $data['t_panjang_skpdt']; ?>" onkeypress="hitungpajakreklame();" onchange="hitungpajakreklame();" onblur="hitungpajakreklame();" type="text">                    
                    </div>
                    <label class="col-sm-1 control-label">Lebar</label>
                    <div class="col-sm-1">
                        <input name="t_lebar" id="t_lebar" class="form-control" required="required" onkeyup="hitungpajakreklame();" value="<?= $data['t_lebar_skpdt']; ?>" onkeypress="hitungpajakreklame();" onchange="hitungpajakreklame();" onblur="hitungpajakreklame();" type="text">                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Jumlah</label>
                    <div class="col-sm-1">
                        <input name="t_jumlah_reklame" id="t_jumlah_reklame" class="form-control" required="required" onkeyup="hitungpajakreklame();" value="<?= $data['t_jumlah_reklame']; ?>" onkeypress="hitungpajakreklame();" onchange="hitungpajakreklame();" onblur="hitungpajakreklame();" type="text">                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Jangka Waktu</label>
                    <div class="col-sm-1">
                        <input name="t_jangkawaktu" id="t_jangkawaktu" class="form-control" readonly="readonly" value="<?= $data['t_jangkawaktu_skpdt']; ?>" type="text">                    
                    </div>
                    <div class="col-sm-2">
                        <select name="t_tipewaktu" id="t_tipewaktu" class="form-control" readonly="readonly">
                                <option value="Hari" <?php if($data['t_tipewaktu_skpdt'] == 'Hari'){ echo 'selected';} ?>>Hari</option>
                                <option value="Minggu" <?php if($data['t_tipewaktu_skpdt'] == 'Minggu'){ echo 'selected';} ?>>Minggu</option>
                                <option value="Bulan" <?php if($data['t_tipewaktu_skpdt'] == 'Bulan'){ echo 'selected';} ?>>Bulan</option>
                                <option value="Tahun" <?php if($data['t_tipewaktu_skpdt'] == 'Tahun'){ echo 'selected';} ?>>Tahun</option>
                        </select>                    
                    </div>
                </div>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">NSR</label>
                    <div class="col-sm-3">
                        <input name="t_nsr_reklame" id="t_nsr_reklame" class="form-control" required="required" style="text-align:right" readonly="readonly" value="<?= number_format($data['t_nsr_reklame_skpdt'], 0, ',', '.') ?>" type="text">                    
                    </div>
                    <div class="col-sm-3"></div>
                </div>
                <label style="display: none;" class="col-sm-12 control-label" id="perhitungandetail"> </label>
                <div class="col-sm-12">
                    <label class="col-sm-2 control-label">Total Pajak</label>
                    <div class="col-sm-4">
                        <input name="t_jmlhpajak" id="t_jmlhpajak" class="form-control" required="required" readonly="readonly" style="text-align:right; background:#000099; color: white; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder" value="<?= number_format($data['t_jmlhpajakseharusnya'], 0, ',', '.') ?>" type="text">                    
                    </div>
                    <div class="col-sm-1">
                        <button type="button" class="btn btn-sm btn-primary" onclick="hitungpajakreklame()">
                            Hitung
                        </button>
                    </div>
                </div>
                
                <div class="col-sm-12">
                        <label class="col-sm-2 control-label">(Pajak Seharusnya)</label>
                        <div class="col-md-4">
                            <input name="t_jmlhpajakseharusnya" id="t_jmlhpajakseharusnya" value="<?= number_format($data['t_jmlhpajakseharusnya'], 0, ',', '.') ?>" class="form-control" readonly="true"  style="text-align:right; background:papayawhip; color: black; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder" required="required" style="text-align:right" onchange="hitungpemeriksaanskpdt();this.value = formatCurrency(this.value);" onblur="hitungpemeriksaanskpdt();this.value = formatCurrency(this.value);" onkeyup="hitungpemeriksaanskpdt();this.value = formatCurrency(this.value);"  onkeypress="return numbersonly(this, event);" type="text">                        </div>
                        <label class="col-sm-2 control-label">- (Pajak Sebelumnya)</label>
                        <div class="col-md-4">
                            <input id="t_jmlhpajaksebelumnya" class="form-control" readonly="true" value="<?= number_format($data['t_jmlhpajak'], 0, ',', '.') ?>" required="true" style="text-align:right; background:green; color: white; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder" type="text">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Jml. Bulan</label>
                        <div class="col-md-1">
                            <input name="t_jmlhbln" id="t_jmlhbln" class="form-control" required="required" readonly="readonly" style="text-align:right" value="<?= $data['t_jmlhbln']; ?>" type="text">                        </div>
                        <label class="col-sm-2 control-label">Denda (%)</label>
                        <div class="col-md-1">
                            <input name="t_tarifpersen" id="t_tarifpersen" class="form-control" required="required" readonly="readonly" style="text-align:right" value="<?= $data['t_tarifpersen']; ?>" type="text">                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Pajak (Rp.)</label>
                        <div class="col-md-4">
                            <input name="t_jmlhpajakpemeriksaan" id="t_jmlhpajakpemeriksaan" class="form-control" required="required" readonly="readonly" style="text-align:right" value="<?= number_format($data['t_jmlhpajakskpdt'], 0, ',', '.'); ?>" type="text">                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Kenaikan</label>
                        <div class="col-md-4">
                            <select name="t_jeniskenaikan" id="t_jeniskenaikan" class="form-control" required="required" onchange="hitungpemeriksaanskpdt()">
                                <option value="1" <?php if($data['t_jeniskenaikan'] == 1){ echo 'selected';} ?>>Tetapkan Kenaikan</option>
                                <option value="2" <?php if($data['t_jeniskenaikan'] == 2){ echo 'selected';} ?>>Tidak Tetapkan Kenaikan</option></select>                        
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Kenaikan (%)</label>
                        <div class="col-md-1">
                            <input name="t_tarifkenaikan" id="t_tarifkenaikan" class="form-control" required="required" readonly="readonly" style="text-align:right" value="<?= $data['t_tarifkenaikan'];?>" type="text">                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Kenaikan (Rp.)</label>
                        <div class="col-md-4">
                            <input name="t_jmlhkenaikan" id="t_jmlhkenaikan" class="form-control" required="required" readonly="readonly" style="text-align:right" value="<?= number_format($data['t_jmlhkenaikan'], 0, ',', '.'); ?>" type="text">                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Denda</label>
                        <div class="col-md-4">
                            <select name="t_jenisketetapandenda" id="t_jenisketetapandenda" class="form-control" required="required" onchange="hitungpemeriksaanskpdt()">
                                <option value="1" <?php if($data['t_jenisketetapandenda'] == 1){ echo 'selected';} ?>>Tetapkan Denda</option>
                                <option value="2" <?php if($data['t_jenisketetapandenda'] == 2){ echo 'selected';} ?>>Tidak Tetapkan Denda</option>
                            </select>                        
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Denda (Rp.)</label>
                        <div class="col-md-4">
                            <input name="t_jmlhdendapemeriksaan" id="t_jmlhdendapemeriksaan" class="form-control" required="required" readonly="readonly" style="text-align:right" value="<?= number_format($data['t_jmlhdendaskpdt'], 0, ',', '.'); ?>" type="text">                        </div>
                    </div>
                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Total (Rp.)</label>
                        <div class="col-md-4">
                            <input name="t_totalpemeriksaan" id="t_totalpemeriksaan" class="form-control" required="required" readonly="readonly" style="text-align:right; background:#000099; color: white; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder" value="<?= number_format($data['t_totalskpdt'], 0, ',', '.'); ?>" type="text">                        </div>
                       
                    </div>
                
                <div class="col-sm-6">
                    <div class="bg-default pull-right" id="tombolsimpan">
                        <input name="Pendataansubmit" id="Pendataansubmit" class="btn btn-success btn-sm" value="Simpan" type="submit"> 
                    </div>
                </div>
            </div>

                    </div>
    </div>
</div></form>




<?= $this->MenuHelper()->headeratas_end(); ?>


<div class="modal fade bs-example-modal-lg" id="modalRekening" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document" style="width: 80%">
        <div class="modal-content">
            <div class="modal-header with-border bg-green-gradient">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <center><h4 class="modal-title" id="myModalLabel">DAFTAR REKENING</h4></center>
            </div>
            <div class="box-body">
                <table id="datarekeningreklame" cellpadding="0" cellspacing="0" border="0" class="display" width="100%" style="min-width:100%;">
                    <thead>
                        <tr class="bg-blue tableheader">

                            <th width="15">No</th>
                            <th>Kode Rekening</th>            
                            <th>Nama Rekening</th>  
                            <th>Tarif (%)</th>
                            <th>NJOPR</th>
                            <th>Perintah</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tfoot>

                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>

                    </tfoot>
                </table>
                <input type="hidden" id="t_jenisobjek" value="<?= $datapendaftaran['t_jenisobjek'] ?>">
            </div>
        </div>
    </div>
</div>

<style type="text/css">
    .dataTables_filter {
        display: none;
    }
</style> 
<?php
$idtabel = '#datarekeningreklame';
$url = $this->url('pendataan') . '/dataGridRekeningReklame';
$jmlkolom = 5;
$seleksi_kolom = "'0','5'"; //iki data sort di disabel
$pencarian_bawah = 5;
?>
<?= $this->MenuHelper()->fr_datatables($this->basePath(), $idtabel, $url, $jmlkolom, $pencarian_bawah, $seleksi_kolom, null); ?>




<script>
    fr_tahun("#t_periodepajak");
    fr_tanggal("#t_tglpendataan");
    fr_tanggal("#t_tglpemeriksaan");
    fr_tanggal("#t_masaawal");
    fr_tanggal("#t_masaakhir");

    function bukamodalRekening() {
        $('#modalRekening').modal('show');
        //dTable.columns.adjust();
    }

    $('#modalRekening').on('shown.bs.modal', function (e) {
        //$.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();
        dTable.columns.adjust();
    });
    
    $('#t_jenislokasi').removeAttr('required');
    $('#t_id_kelas_jalan').removeAttr('required');
    $('#t_id_sudut_pandang').removeAttr('required');

    function pilihRekening(a) {
        $.post('<?= $this->url('pendataan') ?>/pilihRekening', {s_idkorek: a}, function (data) {
            var aa = JSON.parse(data);
            $('#t_idkorek').val(aa.t_idkorek);
            $('#t_korek').val(aa.t_korek);
            $('#t_namakorek').val(aa.t_namakorek);
            $('#t_tarifpajak').val(aa.t_tarifpajak);
            //$('#t_jenisreklame').html(aa.t_jenisreklame);
            $('#modalRekening').modal('hide');
            
            if((aa.t_korek == '4.1.1.04.01.01.00.00') || (aa.t_korek == '4.1.1.04.01.02.00.00') || (aa.t_korek == '4.1.1.04.01.03.00.00') || (aa.t_korek == '4.1.1.04.01.04.00.00') ){
                document.getElementById('hidden_div').style.display = "block";
                $('#t_jenislokasi').attr('required', 'required');
                $('#t_id_kelas_jalan').attr('required', 'required');
                $('#t_id_sudut_pandang').attr('required', 'required');
                
            }else{
                //document.getElementById('hidden_div').style.display = "none";
                document.getElementById('hidden_div').style.display = "block";

                $('#t_jenislokasi').removeAttr('required');
                $('#t_id_kelas_jalan').removeAttr('required');
                $('#t_id_sudut_pandang').removeAttr('required');
                
            }
            
            hitungpajakreklame();
            
        });
    }

    document.getElementById("perhitungandetail").style.display = 'none';
    document.getElementById("perhitungandetail").innerHTML = " ";
    function hitungpajakreklame() {
        $.post('<?= $this->url('pendataan') ?>/hitungpajakreklame', {
            t_jenislokasi: $("#t_jenislokasi").val(),
            t_id_kelas_jalan: $("#t_id_kelas_jalan").val(),
            t_id_sudut_pandang: $("#t_id_sudut_pandang").val(),
            t_panjang: $("#t_panjang").val(),
            t_lebar: $("#t_lebar").val(),
            t_jumlah_reklame: $("#t_jumlah_reklame").val(), 
            t_tipewaktu: $("#t_tipewaktu").val(), 
            t_jangkawaktu: $("#t_jangkawaktu").val(),
            t_masaawal: $("#t_masaawal").val(),
            t_masaakhir: $("#t_masaakhir").val(),
            t_idkorek: $("#t_idkorek").val(),
            t_berupa_reklame: $("#t_berupa_reklame").val(),
            t_pemasangan_reklame: $("#t_pemasangan_reklame").val(),
            t_korek: $('#t_idkorek').val()
        }, function (data) {
            var aa = JSON.parse(data);
            $('#t_jmlhpajak').val(aa.t_jmlhpajak);
            $('#t_nsr_reklame').val(aa.t_nsr_reklame);
            
            $('#t_jmlhpajakseharusnya').val(aa.t_jmlhpajak);
            
            
            document.getElementById("perhitungandetail").innerHTML = aa.perhitungandetail;
            document.getElementById("perhitungandetail").style.display = 'block';
            
            $('#t_jangkawaktu').val(aa.t_jangkawaktu);
            $('#t_tipewaktu').val(aa.t_tipewaktu);
            
        });
        
        hitungpemeriksaanskpdt();
    }


    function hitungpemeriksaanskpdt() {
        $.post('<?= $this->url() ?>/hitungpemeriksaanreklame', {t_jmlhpajakseharusnya: $("#t_jmlhpajakseharusnya").val(), t_jmlhpajak: $("#t_jmlhpajaksebelumnya").val(), t_masaawal: $("#t_masaawal").val(), t_tglpemeriksaan: $("#t_tglpemeriksaan").val(), t_tarifpersen: $("#t_tarifpersen").val(), t_jenisketetapandenda: $("#t_jenisketetapandenda").val(), t_jeniskenaikan: $("#t_jeniskenaikan").val(), t_idtransaksi: <?= $data['t_idtransaksi']; ?>, t_tglpenetapan: '<?= $data['t_tglpenetapan']; ?>', t_tgljatuhtempo: '<?= $data['t_tgljatuhtempo']; ?>'}, function (data) {
            var aa = JSON.parse(data);
            $('#t_jmlhbln').val(aa.t_jmlhbln);
            $('#t_jmlhdendapemeriksaan').val(aa.t_jmlhdendapemeriksaan);
            $('#t_jmlhpajakpemeriksaan').val(aa.t_jmlhpajakpemeriksaan);
            $('#t_totalpemeriksaan').val(aa.t_totalpemeriksaan);
            $('#t_tarifkenaikan').val(aa.t_tarifkenaikan);
            $('#t_jmlhkenaikan').val(aa.t_jmlhkenaikan);
        });
    }


    

//    function comboKelurahanCamat() {
//        $.post('<? $this->url() ?>/comboKelurahanCamat', {t_kecamatan: $('#t_kecamatanrek').val()}, function (data) {
//            $("#t_kelurahanrek").html(data);
//        });
//    }

    function comboKelurahanCamat() {
        $.post('<?= $this->url('pendataan') ?>/comboKelurahanCamat', {t_kecamatan: $('#t_kecamatan_objek').val()}, function (data) {
            var aa = JSON.parse(data);
            $("#t_kelurahan_objek").html(aa.res);
            //$("#keckelluar").html(aa.keckelluar);
        });
    }
    
    function comboSudutPandang() {
        $.post('<?= $this->url('pendataan') ?>/comboSudutPandang', {t_id_kelas_jalan: $('#t_id_kelas_jalan').val()}, function (data) {
            var aa = JSON.parse(data);
            $("#t_id_sudut_pandang").html(aa.res);
            //$("#keckelluar").html(aa.keckelluar);
            hitungpajakreklame();
        });
        
    }
</script>
