<?php

ini_set("max_execution_time", 5000);

if($data_get['jnscetak'] == 1){

include($_SERVER['DOCUMENT_ROOT'] . "/" . $this->basePath() . '/public/cetakan/MPDF57/mpdf.php');
$mpdf = new mPDF('utf-8', 'Legal-L', 0, '', 10, 10, 5, 5, 1, 1, '');
//$mpdf = new mPDF('utf-8', array(215.9,279.4), 7, 7, 7, 7, 7, 1, '');


if(!empty($data_get['s_idkorek'])){
    $datarekening = $this->MenuHelper()->cekrekening($data_get['s_idkorek']);
   
    $koderekeningcek = $datarekening['s_tipekorek'].$datarekening['s_kelompokkorek'].$datarekening['s_jeniskorek'].$datarekening['s_objekkorek'].$datarekening['s_rinciankorek'].$datarekening['s_sub1korek'].$datarekening['s_sub2korek'].$datarekening['s_sub3korek'];

            $s_tipekorek = substr($koderekening, 0,1);
            $s_kelompokkorek = substr($koderekening, 1,1);
            $s_jeniskorek = substr($koderekening, 2,1);
            $s_objekkorek = substr($koderekening, 3,2);
            $s_rinciankorek = substr($koderekening, 5,2);
            $s_sub1korek = substr($koderekening, 7,2);
            $s_sub2korek = substr($koderekening, 9,2);
            $s_sub3korek = substr($koderekening, 11,2);
            
            
           
}else{
    $koderekeningcek = '';
}

$numbering = '<htmlpageheader name="MyHeader1">

            </htmlpageheader>

            <htmlpageheader name="MyHeader2">

            </htmlpageheader>

            <htmlpagefooter name="MyFooter1">
            <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
                color: #000000; font-weight: bold; font-style: italic;"><tr>
                <td width="33%"><span style="font-weight: bold; font-style: italic;"></span></td>
                <td width="33%" align="center" style="font-weight: bold; font-style: italic;">{PAGENO}/{nbpg}</td>
                <td width="33%" style="text-align: right; "></td>
                </tr></table>
            </htmlpagefooter>

            <htmlpagefooter name="MyFooter2">
            <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
                color: #000000; font-weight: bold; font-style: italic;"><tr>
                <td width="33%"><span style="font-weight: bold; font-style: italic;"></span></td>
                <td width="33%" align="center" style="font-weight: bold; font-style: italic;">{PAGENO}/{nbpg}</td>
                <td width="33%" style="text-align: right; "></td>
                </tr></table>
            </htmlpagefooter>';

}else{
    header("Content-type: application/vnd-ms-excel");

    header("Content-Disposition: attachment; filename=cetakrealiasasi.xls");
    
    $numbering = "";
}

if(!empty($data_get['idkec'])){
    $datakec = $this->MenuHelper()->cekkecamatan($data_get['idkec']);
    $namakec = '<br>'.ucwords(strtolower('Kecamatan '.$datakec['s_namakec']));
}else{
    $namakec = '';
}

if(!empty($data_get['idkel'])){
    $datakel = $this->MenuHelper()->cekkelurahan($data_get['idkel']);
    $namakel = '<br>'.ucwords(strtolower('Kelurahan '.$datakel['s_namakel']));
}else{
    $namakel = '';
}

$html = '';
$html .= '
<html>
    <head>
        <style type="text/css">            
            @page {
                size: auto;
                odd-header-name: html_MyHeader1;
                odd-footer-name: html_MyFooter1;
              }
              @page chapter2 {
                  odd-header-name: html_MyHeader2;
                  odd-footer-name: html_MyFooter2;
              }
              @page noheader {
                  odd-header-name: _blank;
                  odd-footer-name: _blank;
              }
              div.chapter2 {
                  page-break-before: always;
                  page: chapter2;
              }
              div.noheader {
                  page-break-before: always;
                  page: noheader;
              }
            .border_atas {
                    border-top: 1px solid black;
                    border-collapse: collapse;
            }

            .border_kiri {
                    border-left: 1px solid black;
                    border-collapse: collapse;
            }

            .border_kanan {
                    border-right: 1px solid black;
                    border-collapse: collapse;
            }

            .border_bawah {
                    border-bottom: 1px solid black;
                    border-collapse: collapse;
            }

            

        </style>
    </head>
    <body>
            
            '.$numbering.'
        <div>
            
            <table width="100%" style="border-spacing: 0px;">
                <tr>
                    <td colspan="6" style="font-size: 12px;">
                        <center>
                        <b style="font-size: 16px;">PEMERINTAH '.strtoupper($ar_pemda->s_namakabkota).'
                        <br>'.strtoupper($ar_pemda->s_namainstansi).' ('.strtoupper($ar_pemda->s_namasingkatinstansi).')   </b>
                        <br>'.strtoupper($ar_pemda->s_alamatinstansi).' Telp/Fax '.$ar_pemda->s_notelinstansi.', '.$ar_pemda->s_namaibukotakabkota.' '.$ar_pemda->s_kodepos .'    
                        <br><br>
                        KETETAPAN BULAN '.date('d', strtotime($data_get['tgl1'])).' '.strtoupper($this->MenuHelper()->namabulandate(date('m', strtotime($data_get['tgl0'])))).' TAHUN '.date('Y', strtotime($data_get['tgl0'])).' s/d '.date('d', strtotime($data_get['tgl1'])).' '.strtoupper($this->MenuHelper()->namabulandate(date('m', strtotime($data_get['tgl1'])))).' TAHUN '.date('Y', strtotime($data_get['tgl1'])).'
                        '.$namakec.' '.$namakel.'
                        </center>    
                    </td>
                </tr>
                <tr>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>Kode Rekening</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>Jenis Penerimaan</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>Target Anggaran</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>Ketetapan</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>Pembayaran</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>Jumlah Tunggakan</b></center>
                    </td>
                </tr>
                ';
                
                $total_target = 0;
                $total_ketetapan = 0;
                $total_setoran = 0;
                $total_tunggakan = 0;
                $total_selisih = 0;
                $counter = 1;
                
                //$clast_rek_induk = '';
                //$clast_subinduk = '';
                
                $clast_rek_kel = '';
                $clast_rek = '';
                
                $subrekeninginduk = '';
                $clast_rek_name_subinduk = '';
                
                $total_semuacek = 0;
                
                foreach ($this->data as $k => $v) {
                   
                    $total_semuacek = $v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']
                                        + $v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']
                                        + $v['target_anggaran'];
                    
                    
                    
                    
                   
                if($total_semuacek == 0){
                        
                }else{
                    
                        
                        if ($v['s_rinciankorek'] == '00') {
                            $b = '<b>';
                            $b1 = '</b>';
                        } else {
                            $b = '';
                            $b1 = '';
                        } 
                        
                    
                $html .= '
                    <tr>
                        <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                            '.$b.' '.$v['rekening'].' '. $b1.'
                        </td>
                        <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                            '.$b.' '.$v['s_namakorek'].' '. $b1.'
                        </td>
                        <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                            '.$b.' '. number_format($v['target_anggaran'], 2, ',', '.').' '. $b1.'
                        </td>
                        <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                            '.$b.' '.number_format($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda'], 2, ',', '.').' '. $b1.' 
                        </td>
                        <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                            '.$b.' '. number_format($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda'], 2, ',', '.').' '. $b1.'
                        </td>
                        <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                            '.$b.' '. number_format(($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']) - ($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']), 2, ',', '.').' '. $b1.'
                        </td>
                        
                        
                    </tr>';
                    
                    
                    
                    }
                    
                    if(!empty($data_get['s_idkorek'])){
                        if(substr($koderekeningcek, 1,12) == '000000000000'){
                            if(strlen($v['rekening']) == 1 ){
                                $total_target += $v['target_anggaran'];
                                $total_ketetapan += $v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda'];
                                $total_setoran += $v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda'];
                                $total_tunggakan += ($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']) - ($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']);
                                //$total_selisih += $v['jmlh_setoran_normal_sdblnini'] + $v['jmlh_setoran_lain_sdblnini'] - $v['target_anggaran'];
                            }
                        }elseif(substr($koderekeningcek, 2,11) == '00000000000'){
                            if(strlen($v['rekening']) == 3 ){
                                $total_target += $v['target_anggaran'];
                                $total_ketetapan += $v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda'];
                                $total_setoran += $v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda'];
                                $total_tunggakan += ($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']) - ($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']);
                                //$total_selisih += $v['jmlh_setoran_normal_sdblnini'] + $v['jmlh_setoran_lain_sdblnini'] - $v['target_anggaran'];
                            }
                        }elseif(substr($koderekeningcek, 3,9) == '000000000'){
                            if(strlen($v['rekening']) == 5 ){
                                $total_target += $v['target_anggaran'];
                                $total_ketetapan += $v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda'];
                                $total_setoran += $v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda'];
                                $total_tunggakan += ($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']) - ($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']);
                                //$total_selisih += $v['jmlh_setoran_normal_sdblnini'] + $v['jmlh_setoran_lain_sdblnini'] - $v['target_anggaran'];
                            }
                        }elseif(substr($koderekeningcek, 5,8) == '00000000'){
                            if(strlen($v['rekening']) == 8 ){
                                $total_target += $v['target_anggaran'];
                                $total_ketetapan += $v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda'];
                                $total_setoran += $v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda'];
                                $total_tunggakan += ($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']) - ($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']);
                                //$total_selisih += $v['jmlh_setoran_normal_sdblnini'] + $v['jmlh_setoran_lain_sdblnini'] - $v['target_anggaran'];
                            }
                        }elseif(substr($koderekeningcek, 7,6) == '000000'){
                            if(strlen($v['rekening']) == 11 ){
                                $total_target += $v['target_anggaran'];
                                $total_ketetapan += $v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda'];
                                $total_setoran += $v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda'];
                                $total_tunggakan += ($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']) - ($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']);
                                //$total_selisih += $v['jmlh_setoran_normal_sdblnini'] + $v['jmlh_setoran_lain_sdblnini'] - $v['target_anggaran'];
                            }
                        }elseif(substr($koderekeningcek, 9,4) == '0000'){
                            if(strlen($v['rekening']) == 14 ){
                                $total_target += $v['target_anggaran'];
                                $total_ketetapan += $v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda'];
                                $total_setoran += $v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda'];
                                $total_tunggakan += ($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']) - ($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']);
                                //$total_selisih += $v['jmlh_setoran_normal_sdblnini'] + $v['jmlh_setoran_lain_sdblnini'] - $v['target_anggaran'];
                            }
                        }elseif(substr($koderekeningcek, 11,2) == '00'){
                            if(strlen($v['rekening']) == 17 ){
                                $total_target += $v['target_anggaran'];
                                $total_ketetapan += $v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda'];
                                $total_setoran += $v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda'];
                                $total_tunggakan += ($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']) - ($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']);
                                //$total_selisih += $v['jmlh_setoran_normal_sdblnini'] + $v['jmlh_setoran_lain_sdblnini'] - $v['target_anggaran'];
                            }
                        }else{
                            $total_target += $v['target_anggaran'];
                            $total_ketetapan += $v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda'];
                                $total_setoran += $v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda'];
                                $total_tunggakan += ($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']) - ($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']);

                        }
                    }else{
                        if(strlen($v['rekening']) == 1 ){
                                $total_target += $v['target_anggaran'];
                                $total_ketetapan += $v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda'];
                                $total_setoran += $v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda'];
                                $total_tunggakan += ($v['jmlh_ketetapan_selain46'] + $v['jmlh_ketetapan_minerba'] + $v['jmlh_ketetapan_reklame'] + $v['jmlh_ketetapan_denda']) - ($v['jmlh_pembayaran_selain46'] + $v['jmlh_pembayaran_minerba'] + $v['jmlh_pembayaran_reklame'] + $v['jmlh_pembayaran_denda']);
                                //$total_selisih += $v['jmlh_setoran_normal_sdblnini'] + $v['jmlh_setoran_lain_sdblnini'] - $v['target_anggaran'];
                        }
                    }
                    
                    
                    
                    
                }
                $html .= '
                <tr>
                    <td colspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> TOTAL </b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        <b>'. number_format($total_target,2, ',', '.').'</b>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        <b>'. number_format($total_ketetapan,2, ',', '.').'</b>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        <b>'. number_format($total_setoran,2, ',', '.').'</b>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        <b>'. number_format($total_tunggakan,2, ',', '.').'</b>
                    </td>
                    
                    
                </tr>';
                
                $html .= '
                <tr>
                    <td colspan="6">
                        &nbsp;
                    </td>
                </tr>    
                <tr>
                    <td colspan="3">';
                        if(!empty($data_get['ttd0'])){
                            $namapejabat = $this->MenuHelper()->getnamapejabat($data_get['ttd0']);
                            $html .= '
                                <center>
                                    <br><b>'.$namapejabat['s_jabatanpej'].'
                                    
                                    <br><br><br><br>
                                    <u>&nbsp;&nbsp;&nbsp;'.$namapejabat['s_namapej'].'&nbsp;&nbsp;&nbsp;</u></b>
                                        <br>'.$namapejabat['s_nippej'].'
                                    </center>';
                        }
                $html .= ' 
                    </td>
                    <td colspan="3">';
                        if(!empty($data_get['ttd1'])){
                            $namapejabat1 = $this->MenuHelper()->getnamapejabat($data_get['ttd1']);
                            $html .= '
                                <center>'.$ar_pemda->s_ttdkabkot.', '.$data_get['tglcetak'].'
                                    <br><b>'.$namapejabat1['s_jabatanpej'].'
                                    
                                    <br><br><br><br>
                                    <u>&nbsp;&nbsp;&nbsp;'.$namapejabat1['s_namapej'].'&nbsp;&nbsp;&nbsp;</u></b>
                                        <br>'.$namapejabat1['s_nippej'].'
                                    </center>';
                        }
                $html .= '    
                    </td>
                </tr> 
            </table>
        </div>
    </body>
</html>';
if ($data_get['jnscetak'] == 1) {

    $mpdf->WriteHTML($html);
    $mpdf->Output("cetakrealiasasi.pdf", "I");
}else{
    echo $html;    
}
?>    