<?php

ini_set("max_execution_time", 5000);
ini_set('memory_limit', '1024M');
if($data_get['jnscetak'] == 1){

include($_SERVER['DOCUMENT_ROOT'] . "/" . $this->basePath() . '/public/cetakan/MPDF57/mpdf.php');
$mpdf = new mPDF('utf-8', 'Legal', 0, '', 10, 10, 5, 1, 1, 1, '');
//$mpdf = new mPDF('utf-8', array(215.9,279.4), 7, 7, 7, 7, 7, 1, '');

$numbering = '<htmlpageheader name="MyHeader1">

            </htmlpageheader>

            <htmlpageheader name="MyHeader2">

            </htmlpageheader>

            <htmlpagefooter name="MyFooter1">
            <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
                color: #000000; font-weight: bold; font-style: italic;"><tr>
                <td width="33%"><span style="font-weight: bold; font-style: italic;"></span></td>
                <td width="33%" align="center" style="font-weight: bold; font-style: italic;">{PAGENO}/{nbpg}</td>
                <td width="33%" style="text-align: right; "></td>
                </tr></table>
            </htmlpagefooter>

            <htmlpagefooter name="MyFooter2">
            <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
                color: #000000; font-weight: bold; font-style: italic;"><tr>
                <td width="33%"><span style="font-weight: bold; font-style: italic;"></span></td>
                <td width="33%" align="center" style="font-weight: bold; font-style: italic;">{PAGENO}/{nbpg}</td>
                <td width="33%" style="text-align: right; "></td>
                </tr></table>
            </htmlpagefooter>';

}else{
    header("Content-type: application/vnd-ms-excel");

    header("Content-Disposition: attachment; filename=cetakrekapitulasi" . $data_get['tgl0']."_sd_".$data_get['tgl1'].".xls");
    
    $numbering = "";
}
if(!empty($data_get['jenisobjek'])){
$jenisobjek = $this->MenuHelper()->cekjenispajak($data_get['jenisobjek']);
$namaobjeknya = strtoupper($jenisobjek['s_namajenis']);
}else{
    $namaobjeknya = '';
}

if(!empty($kec_realisasi)){
    $cekkecamatan = $this->MenuHelper()->cekkecamatan($kec_realisasi);
    $namakec = "<br> KECAMATAN ".$cekkecamatan['s_namakec'];
}else{
    $namakec = "";
}

if(!empty($kel_realisasi)){
    $cekkelurahan = $this->MenuHelper()->cekkelurahan($kel_realisasi);
    $namakel = "KELURAHAN ".$cekkelurahan['s_namakel'];
}else{
    $namakel = "";
}

$html = '';
$html .= '
<html>
    <head>
        <style type="text/css">            
            @page {
                size: auto;
                odd-header-name: html_MyHeader1;
                odd-footer-name: html_MyFooter1;
              }
              @page chapter2 {
                  odd-header-name: html_MyHeader2;
                  odd-footer-name: html_MyFooter2;
              }
              @page noheader {
                  odd-header-name: _blank;
                  odd-footer-name: _blank;
              }
              div.chapter2 {
                  page-break-before: always;
                  page: chapter2;
              }
              div.noheader {
                  page-break-before: always;
                  page: noheader;
              }
            .border_atas {
                    border-top: 1px solid black;
                    border-collapse: collapse;
            }

            .border_kiri {
                    border-left: 1px solid black;
                    border-collapse: collapse;
            }

            .border_kanan {
                    border-right: 1px solid black;
                    border-collapse: collapse;
            }

            .border_bawah {
                    border-bottom: 1px solid black;
                    border-collapse: collapse;
            }

            

        </style>
    </head>
    <body>
            
            '.$numbering.'

            <table width="100%" style="border-spacing:0px;">
                <tr>
                    <td colspan="9">
                        <center>
                        <b style="font-size: 18px;">REKAPITULASI '.  $namaobjeknya.'
                        '.$namakec.' '.$namakel.'
                        <br>TANGGAL SETOR '.$data_get['tgl0'].' s/d '.$data_get['tgl1'].' </b>
                        </center>    
                    </td>
                </tr>
                 <tr>
                    <td colspan="9">&nbsp;</td>
                </tr>      
                <tr>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" >
                       <center><b> NO</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> NPWPD</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> NAMA</b></center>
                    </td>                   
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>JENIS KETETAPAN</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>NO SETOR</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>REKENING</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> MASA PAJAK</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> JUMLAH BAYAR</b></center>
                    </td>
                    
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> KETERANGAN</b></center>
                    </td>
                    
                </tr>
                <tr>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>1</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> 2</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b>3</b></center>
                    </td>
                    
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> 4</b></center>
                    </td >
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>5</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> 6</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>7</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b>8</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                      <center><b> 9</b></center>
                    </td>
                    
                </tr>';
                
                
                $totalkeseluruhan = 0;
                $no = 1;
                $clast_rek_kel = '';
                $clast_rek = '';
                
                $totalpembayaran = 0;
                
                
               
                
                
                $totalsubtgl_dbyr = 0;
                
                $last_tanggalpendataan = '';
                $last_tanggalpendataan_name = '';
                
                $last_berdasarrekening = '';
                $last_berdasarrekening_name = '';
                
                
                $totalsubrek_dbyr = 0;
                
                foreach ($data as $k => $v) {
                    
                    
if($v['t_bidangusaha'] == 2){
    $namawp = $v['t_nama_badan'];
    $alamatwp = '';
    if(!empty($v['t_jalan_badan'])){
        $alamatwp .= $v['t_jalan_badan'];
    }
    if(!empty($v['t_rt_badan'])){
        $alamatwp .= ' RT '.$v['t_rt_badan'];
    }
    if(!empty($v['t_rw_badan'])){
        $alamatwp .= ' RW '.$v['t_rw_badan'];
    }
    if(!empty($v['s_namakelbadan'])){
        $alamatwp .= ' Kel. '.$v['s_namakelbadan'];
    }
    if(!empty($v['s_namakecbadan'])){
        $alamatwp .= ' Kec. '.$v['s_namakecbadan'];
    }
    if(!empty($v['t_kabupaten_badan'])){
        $alamatwp .= ' Kab. '.$v['t_kabupaten_badan'];
    }
}else{
    $namawp = $v['t_nama'];
    $alamatwp = '';
    if(!empty($v['t_alamat'])){
        $alamatwp .= $v['t_alamat'];
    }
    if(!empty($v['t_rt'])){
        $alamatwp .= ' RT '.$v['t_rt'];
    }
    if(!empty($v['t_rw'])){
        $alamatwp .= ' RW '.$v['t_rw'];
    }
    if(!empty($v['s_namakel'])){
        $alamatwp .= ' Kel. '.$v['s_namakel'];
    }
    if(!empty($v['s_namakec'])){
        $alamatwp .= ' Kec. '.$v['s_namakec'];
    }
    if(!empty($v['t_kabupaten'])){
        $alamatwp .= ' Kab. '.$v['t_kabupaten'];
    }
}

if(!empty($v['t_jmlhpembayaran'])){
    if($v['t_jenisobjek'] == 6){
        $jmlhpembayaran = number_format($v['t_pajak'], 2, ",", ".");
        $belumbayar = 0;
        $belumbayartotalnya = 0;
    }else{
        $jmlhpembayaran = number_format($v['t_jmlhpembayaran'], 2, ",", ".");
        $belumbayar = 0;
        $belumbayartotalnya = 0;
    }
}else{
    if($v['t_jenisobjek'] == 6){
        $jmlhpembayaran = 0;
        $belumbayar = number_format($v['t_pajak'], 2, ",", ".");
        $belumbayartotalnya = $v['t_pajak'];
    }else{
    
        $jmlhpembayaran = 0;
        $belumbayar = number_format($v['t_jmlhpajak'], 2, ",", ".");
        $belumbayartotalnya = $v['t_jmlhpajak'];
    
    }
}

if(!empty($v['t_masaawal'])){
    $masapajak = date('d-m-Y', strtotime($v['t_masaawal'])) . ' S/D ' . date('d-m-Y', strtotime($v['t_masaakhir']));
}else{
    $masapajak = '';
}

                
                    if ($last_tanggalpendataan <> date('d-m-Y', strtotime($v['t_tglpembayaran']))) {

                        if ($last_tanggalpendataan <> '') {

                             $html .= '<tr>
                                            <td colspan="7" style="border-bottom: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;" align="right"><b>JUMLAH '. strtoupper($last_tanggalpendataan_name) .'</b>&nbsp;</td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubtgl_dbyr, 2, ',', '.') . '</i></b></td>    

                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right">&nbsp;</td>   
                              </tr>'; 

                            
                             $totalsubtgl_dbyr = 0;
                        }


                        $html .= '<tr>
                                                <td colspan="9" align="left" style="border-bottom: 1px solid #000;border-top: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;"><b>TANGGAL SETOR : ' . date('d-m-Y', strtotime($v['t_tglpembayaran'])) . '</b></td>

                                            </tr>';

                        $last_tanggalpendataan = date('d-m-Y', strtotime($v['t_tglpembayaran']));
                        $last_tanggalpendataan_name = date('d-m-Y', strtotime($v['t_tglpembayaran']));
                        //$counter = 1;
                    }
                


                    
                    $html .= '
                        <tr>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 20px;">
                        <center>'.$no.'</center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;">
                        <center>'.$v['t_npwpd'].'</center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 160px;">
                        '.$namawp.'
                    </td>
                    
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>'.$v['s_namasingkatsurat'].'</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>'.$v['t_nourut'].'</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; vertical-align: top;">
                    
                        '.$v['s_tipekorek'].'.'.$v['s_kelompokkorek'].'.'.$v['s_jeniskorek'].'.'.$v['s_objekkorek'].'.'.$v['s_rinciankorek'].'.'.$v['s_sub1korek'].'.'.$v['s_sub2korek'].'.'.$v['s_sub3korek'].' <br>
                            '.$v['s_namakorek'].'
                        
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;" >
                        ' . $masapajak . '
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;" align="right">
                        '.number_format($v['t_jmlhpembayaran'], 2, ",", ".") . '
                    
                    
                    </td>
                   
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;">
                        ';
                    if($v['t_dari_skpd'] == 1){
                        $nama_skpd = 'DARI SKPD';
                    }elseif($v['t_dari_skpd'] == 0){
                        $nama_skpd = 'DARI WP';
                    }else{
                        $nama_skpd = '';
                    }
                    $html .= ' '.$nama_skpd.' <br> '.$v['s_namaskpd'].'
                    </td>
                   
                </tr>';
                    
                    
                    
                    
                    $totalpembayaran += $v['t_jmlhpembayaran'];
                    
                    
                   
                    $totalsubtgl_dbyr += $v['t_jmlhpembayaran'];
                    
                    
                   
                    
                    $no++;
                }
               
                   
                        if ($last_tanggalpendataan <> '') {

                             $html .= '<tr>
                                            <td colspan="7" style="border-bottom: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;" align="right"><b>JUMLAH '. strtoupper($last_tanggalpendataan_name) .'</b>&nbsp;</td>
                                            
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubtgl_dbyr, 2, ',', '.') . '</i></b></td>    

                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right">&nbsp;</td>   
                              </tr>'; 

                            
                             $totalsubtgl_dbyr = 0;
                        }
                    
                $html .= '
                        <tr>
                    <td colspan="7" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>JUMLAH TOTAL</b></center>
                    </td>
                    
                    
                   
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        <b>'.number_format($totalpembayaran, 2, ",", ".").'</b>
                    </td >
                    
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        
                    </td>
                </tr>
                <tr>
                    <td colspan="9">
                    &nbsp;
                    </td>
                </tr>    
                 <tr>
                    <td colspan="3">
                        &nbsp;
                    </td>
                    <td colspan="6">';
                        if(!empty($data_get['ttd0'])){
                            $namapejabat = $this->MenuHelper()->getnamapejabat($data_get['ttd0']);
                            $html .= '
                                <center>'.$ar_pemda->s_ttdkabkot.', '.$data_get['tglcetak'].'
                                    <br><b>'.$namapejabat['s_jabatanpej'].'
                                    
                                    <br><br><br><br><br><br>
                                    <u>&nbsp;&nbsp;&nbsp;'.$namapejabat['s_namapej'].'&nbsp;&nbsp;&nbsp;</u></b>
                                        <br>'.$namapejabat['s_nippej'].'
                                    </center>';
                        }
                $html .= '    
                    </td>
                </tr>    
            </table>
        </div>
    </body>
</html>
';
if ($data_get['jnscetak'] == 1) {

    $mpdf->WriteHTML($html);
    $mpdf->Output("cetakrekapitulasi" . $data_get['tgl0']."_sd_".$data_get['tgl1'].".pdf", "I");
}else{
    echo $html;    
}
?>    