<?php
if ($formatcetak == 'excel') {
    header("Content-type: application/vnd-ms-excel");
    header("Content-Disposition: attachment; filename=cetakrealisasiobjek.xls");
}

ini_set("max_execution_time", 5000);
ini_set('memory_limit', '1024M');
$gambar = '<img src="' . $ar_pemda->s_logo . '" width="60">';

$namabulan_text = [
    "Januari",
    "Februari",
    "Maret",
    "April",
    "Mei",
    "Juni",
    "Juli",
    "Agustus",
    "September",
    "Oktober",
    "November",
    "Desember"
];
?>
<html>

<body>


    <div>
        <table width="100%" style="font-family:arial;">
            <tr>
                <?php
                if ($formatcetak == 'pdf') {
                    echo '<td width="10%" style="border: 1px solid #fff;">' . $gambar . '</td>';
                } else {
                    echo '<img src="' . $_SERVER["DOCUMENT_ROOT"] . '/' . $ar_pemda->s_logo . '" width="60">';
                }
                ?>

                <td colspan="4" style="text-align:center; padding-right: 10%;border: 1px solid #fff;">
                    <span style="font-size:14pt;font-weight: BOLD;">PEMERINTAH KABUPATEN <?= strtoupper($ar_pemda->s_namakabkota) ?></span><br>
                    <span style="font-size:16pt;font-weight: BOLD;"><?= strtoupper($ar_pemda->s_namainstansi) ?></span><br>
                    <span style="font-size:10pt;"><?= $ar_pemda->s_alamatinstansi . ' ' . $no_telp . ' ' . $ar_pemda->s_namaibukotakabkota . ' Kode Pos. ' . $ar_pemda->s_kodepos ?></span>
                </td>
            </tr>
        </table>
        <hr style="line-height: 1px; color: black">
        <div style="text-align:center;">
            <b style="text-align: center;font-family:arial;font-size:13pt;">REALISASI PER LOKASI OBJEK TAHUN <?= $periode ?></b>
        </div>
        <span style="font-family:arial">
            <?php if (!empty($kecamatan)) { ?>
                Kecamatan : <?= $kecamatan->s_namakec ?><br>
            <?php } ?>
            <?php if (!empty($kelurahan)) { ?>
                Kelurahan : <?= $kelurahan->s_namakel ?><br>
            <?php } ?>
        </span>
        <table width="100%" cellpadding="4" cellspacing="4" style="border-collapse: collapse;border-top:4px double black; table-layout: fixed; border-spacing: 0; text-align: center;font-family:arial;" border="0">
            <thead>
                <tr style="text-align: center;background: #f3f3f3">
                    <th style="border: 1px solid black; border-bottom: 1px solid black;">
                        KODE REKENING
                    </th>
                    <th style="border: 1px solid black;">
                        NAMA REKENING
                    </th>
                    <th style="border: 1px solid black;">
                        PENETAPAN (Rp.)
                    </th>
                    <th style="border: 1px solid black;">
                        REALISASI (Rp.)
                    </th>
                    <th style="border: 1px solid black;">
                        SELISIH (Rp.)
                    </th>
                </tr>
            </thead>
            <?php
            $total_penetapan = 0;
            $total_realisasi = 0;
            $total_selisih = 0;
            $counter = 1;
            foreach ($this->data as $k => $v) {
                $selisih = $v['penetapan'] - $v['realisasi'];
                if ($v['penetapan'] > 0) {
                    $b1 = '';
                    $b2 = '';
                    if ($v['s_rinciankorek'] == '00' || $v['s_rinciankorek'] == '') {
                        $b1 = '<b>';
                        $b2 = '</b>';
                    }
            ?>
                    <tbody>
                        <tr>
                            <td style="text-align: left;border: 1px solid black; border-bottom: 1px solid;">
                                <?= $b1 . $v['korek'] . $b2 ?>
                            </td>
                            <td style="text-align: left;border: 1px solid black;">
                                <?= $b1 . $v['s_namakorek'] . $b2 ?>
                            </td>
                            <td style="text-align: right;border: 1px solid black;">
                                <?= $b1 . number_format($v['penetapan'], 0, ',', '.') . ',-' . $b2 ?>
                            </td>
                            <td style="text-align: right;border: 1px solid black;">
                                <?= $b1 . number_format($v['realisasi'], 0, ',', '.'), ',-' . $b2 ?>
                            </td>
                            <td style="text-align: right;border: 1px solid black;">
                                <?= $b1 . number_format($selisih, 0, ',', '.') . ',-' . $b2 ?>
                            </td>
                        </tr>
                <?php
                }
            }
                ?>
                <tr>
                    <td colspan="5" style="border-top: 1px solid black;"></td>
                </tr>
                    </tbody>
        </table>
        <table width="100%" class="mengetahui">
            <tr class="mengetahui">
                <td style=" width: 35%; text-align: center;vertical-align: bottom;" class="mengetahui">
                    Mengetahui<br>
                    <?= $ar_diperiksa->s_jabatanpej ?>
                    <br><br><br><br><br><br><br>
                    <u><b><?= $ar_diperiksa->s_namapej ?></b></u><br>
                    NIP <?= $ar_diperiksa->s_nippej ?>
                </td>
                <td style=" width: 30%" class="mengetahui"></td>
                <td style=" width: 35%;text-align: center;vertical-align: bottom;" class="mengetahui">
                    <?= $ar_pemda->s_namaibukotakabkota . ', ' . date('d', strtotime($tglcetak)) . " " . $namabulan_text[date('m', strtotime($tglcetak)) - 1] . " " . date('Y', strtotime($tglcetak)) ?>
                    <br>
                    Diperiksa Oleh<br>

                    <?= $ar_mengetahui->s_jabatanpej ?>
                    <br><br><br><br><br><br><br>
                    <u><b><?= $ar_mengetahui->s_namapej ?></b></u><br>
                    NIP <?= $ar_mengetahui->s_nippej ?>
                </td>

            </tr>
        </table>
    </div>
    <?php
    if ($formatcetak == 'pdf') {
        echo '<htmlpagefooter name="MyFooter1">
        <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
               color: #000000; font-weight: bold; font-style: italic;border: 1px solid;">
            <tr>
                <!--<td width="33%"><span style="font-weight: bold; font-style: italic;">{DATE j-m-Y}</span></td>-->
                <td style="font-style: italic;text-align: left;font-size: 10px;border: 1px solid #fff;" width="50%">Printed by SIMPATDA</td>
                <td style="font-style: italic;text-align: right;font-size: 11px;border: 1px solid #fff;" width="50%">Halaman {PAGENO} dari {nbpg}</td>
            </tr>
        </table>
    </htmlpagefooter>';
    } ?>
</body>

</html>

<style type="text/css" media="print">
    /*    table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }*/
    .font_empatbelas {
        font-size: 14pt;
    }

    div.chapter2 {
        page-break-before: always;
        page: chapter2;
    }

    div.noheader {
        page-break-before: always;
        page: noheader;
    }

    @page {
        size: auto;
        odd-header-name: html_MyHeader1;
        odd-footer-name: html_MyFooter1;
    }
</style>