<html>
    <body>
        <?php
        ini_set("max_execution_time", 5000);
        ini_set('memory_limit', '1024M');
        ?>
        <div>
            <div>
                <div style='width: 10%; float: left;'>
                </div>
                <div style='width: 90%; float: right;'>
                    <p style="text-align: center; font-size: 10pt; font-weight: BOLD;">
                        PEMERINTAH <?= strtoupper($ar_pemda->s_namakabkota); ?>, <?= strtoupper($ar_pemda->s_namaprov); ?>
                    </p>
                    <p style="text-align: center; font-size: 12pt; font-weight: BOLD; line-height: 1px;">
                        <?= strtoupper($ar_pemda->s_namainstansi); ?> (<?= strtoupper($ar_pemda->s_namasingkatinstansi); ?>)
                    </p>
                    <p style="text-align: center; font-size: 8pt; line-height: 5px">
                        <?= strtoupper($ar_pemda->s_alamatinstansi); ?> Telp/Fax <?= $ar_pemda->s_notelinstansi ?>, <?= $ar_pemda->s_namaibukotakabkota ?> <?= $ar_pemda->s_kodepos ?>
                    </p>
                </div>
                <div style='clear:both;'></div>
            </div>
            <hr style="line-height: 1px; color: black">
            <h4 style="text-align: center">DAFTAR TUNGGAKAN</h4>
            <p style="font-size: 10pt; line-height: 5px"> 
                Tanggal : <?= $tgljatuhtempo0 ?> s/d <?= $tgljatuhtempo1 ?>
            </p>
            <table width="100%" class="font_sembilan" style="text-align: center">
                <tr>
                    <td class="border_atas border_bawah border_kanan border_kiri">
                        No.
                    </td>
                    <td>
                        Nama
                    </td>
                    <td>
                        NPWPD
                    </td>
                    <td>
                        NIOP
                    </td>
                    <td>
                        Tgl. Pendataan
                    </td>
                    <td>
                        Jmlh Pajak
                    </td>
                    <td>
                        Tgl. Pembayaran
                    </td>
                    <td>
                        Jumlah Pembayaran
                    </td>
                    <td>
                        Tgl. Jatuh Tempo
                    </td>
                    <td>
                        Jumlah Tunggakan
                    </td>
                </tr>
                <?php
                $totalpendataan = 0;
                $totalpembayaran = 0;
                $counter = 1;
                foreach ($this->data as $k => $v) {
                    ?>
                    <tr>
                        <td>
                            <?= $counter ?>
                        </td>
                        <td style="text-align: left">
                            <?= $v['t_nama'] ?>
                        </td>
                        <td>
                            <?= $v['t_npwpd'] ?>
                        </td>
                        <td>
                            <?= $v['t_nop'] ?>
                        </td>
                        <td>
                            <?= date('d-m-Y', strtotime($v['t_tglpendataan'])) ?>
                        </td>
                        <td style="text-align: right">
                            <?= number_format($v['t_jmlhpajak'], 0, ',', '.') ?>
                        </td>
                        <td>
                            <?php
                            $t_tglpembayaran = (!empty($v['t_tglpembayaran']) ? date('d-m-Y', strtotime($v['t_tglpembayaran'])) : '-');
                            ?>
                            <?= $t_tglpembayaran ?>
                        </td>
                        <td style="text-align: right">
                            <?= number_format($v['t_jmlhpembayaran'], 0, ',', '.') ?>
                        </td>
                        <td style="text-align: right">
                            <?= date('d-m-Y', strtotime($v['t_tgljatuhtempo'])) ?>
                        </td>
                        <td style="text-align: right">
                            <?= number_format($v['t_jmlhpajak'] - $v['t_jmlhpembayaran'], 0, ',', '.') ?>
                        </td>
                    </tr>
                    <?php
                    $totalpendataan += $v['t_jmlhpajak'];
                    $totalpembayaran += $v['t_jmlhpembayaran'];
                    $counter++;
                }
                ?>
                <tr>
                    <td colspan="4">

                    </td>
                    <td colspan="2" style="text-align: right">
                        <?= number_format($totalpendataan, 0, ',', '.') ?>
                    </td>
                    <td colspan="2" style="text-align: right">
                        <?= number_format($totalpembayaran, 0, ',', '.') ?>
                    </td>
                    <td colspan="2" style="text-align: right">
                        <?= number_format($totalpendataan - $totalpembayaran, 0, ',', '.') ?>
                    </td>
                </tr>
            </table>
        </div>
    </body>
</html>

<style type="text/css" media="print">
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    .font_empatbelas {
        font-size: 14pt;
    }    
</style>