<?php
if ($formatcetak == '2') {
    header("Content-type: application/vnd-ms-excel");
    header("Content-Disposition: attachment; filename=cetakrealisasisetoranlain.xls");
}

error_reporting(0);
ini_set("max_execution_time", 5000);
ini_set('memory_limit', '-1');

$bulan=(int)$bulan;
if ($bulan==1){
    $bulan="Januari";
}elseif($bulan==2){
    $bulan="Febuari";
}elseif($bulan==3){
    $bulan="Maret";
}elseif($bulan==4){
    $bulan="April";
}elseif($bulan==5){
    $bulan="Mei";
}elseif($bulan==6){
    $bulan="Juni";
}elseif($bulan==7){
    $bulan="Juli";
}elseif($bulan==8){
    $bulan="Agustus";
}elseif($bulan==9){
    $bulan="September";
}elseif($bulan==10){
    $bulan="Oktober";
}elseif($bulan==11){
    $bulan="November";
}elseif($bulan==12){
    $bulan="Desember";
}

$gambar = '<img src="' . $ar_pemda->s_logo . '" width="60">';
if ($ar_pemda->s_notelinstansi == 0 && $ar_pemda->s_notelinstansi == "") {
    $no_telp = '';
} else {
    $no_telp = ' Telp/Fax ' . $ar_pemda->s_notelinstansi . ',';
}
if  ($formatcetak == '2') {
  $gambar = '<img src="http://103.124.44.90:98/public/upload/Lambang_Kabupaten_Pulang Pisau.png" width="7%">';
}

?>

<html>
    <head>
        <style>
            @page {
                size: auto;
                odd-header-name: html_MyHeader1;
                odd-footer-name: html_MyFooter1;
            }
            @page chapter2 {
                odd-header-name: html_MyHeader2;
                odd-footer-name: html_MyFooter2;
            }
            @page noheader {
                odd-header-name: _blank;
                odd-footer-name: _blank;
            }
            div.chapter2 {
                page-break-before: always;
                page: chapter2;
            }
            div.noheader {
                page-break-before: always;
                page: noheader;
            }
        </style>
    </head>
    <body>
        <?php if ($formatcetak == '1') { ?>    
        <htmlpagefooter name="MyFooter1">
            <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
                   color: #000000; font-weight: bold; font-style: italic;border: 1px solid;">
                <tr>
                        <!--<td width="33%"><span style="font-weight: bold; font-style: italic;">{DATE j-m-Y}</span></td>-->
                    <td style="font-style: italic;text-align: left;font-size: 10px;border: 1px solid #fff;" width="50%">Printed by SIMPATDA</td>
                    <td style="font-style: italic;text-align: right;font-size: 11px;border: 1px solid #fff;" width="50%">Halaman {PAGENO} dari {nbpg}</td>
                </tr>
            </table>
        </htmlpagefooter>
    <?php } ?>
    <div>
        <table width="100%" style="font-family:arial;">
            <tr>
                <td width="10%" style="border: 1px solid #fff;"><?= $gambar ?></td>
                <td colspan="14" style="text-align:center; padding-right: 10%;border: 1px solid #fff;">
                    <span style="font-size:14pt;font-weight: BOLD;">PEMERINTAH KABUPATEN <?= strtoupper($ar_pemda->s_namakabkota) ?></span><br>
                    <span style="font-size:16pt;font-weight: BOLD;"><?= strtoupper($ar_pemda->s_namainstansi) ?></span><br>
                    <span style="font-size:10pt;"><?= $ar_pemda->s_alamatinstansi . ' ' . $no_telp . ' ' . $ar_pemda->s_namaibukotakabkota . ' Kode Pos. ' . $ar_pemda->s_kodepos ?></span>
                </td>
            </tr>
        </table>
        <hr style="line-height: 1px; color: black">
        <div style="text-align:center;">
            <b style="font-family:arial;font-size:16pt;">LAPORAN REALISASI SATUAN KERJA/OPD/DINAS </b><br>
            <span style="font-family:arial;">Periode : s/d <?= $bulan ." ". $tahun ?></span>
        </div>
       <!--  <table border="0" width="100%">
            <tr>
                 <tr>
                 <td colspan="14" style="text-align: left;"><b><?=$dataopd['s_namasatker']?></b></td>
            </tr>
            -->
        </table>
        <table  width="100%" style="border-collapse: collapse;border-top:1px double black; table-layout: fixed; border-spacing: 0; text-align: center;font-family:arial;" border="1">
            <thead>
                <tr>
                    <td style="border: 1px solid black; border-bottom: 1px solid;background-color:#28a745;" rowspan="2" colspan="3">
                        <b>&nbsp;Kode Rekening&nbsp;
                    </td>
                    <td rowspan="2" style="border: 1px solid black;background-color:#28a745;" colspan="7">
                        <b>&nbsp;Nama Rekening &nbsp;
                    </td>
                    <td rowspan="2" style="border: 1px solid black;background-color:#28a745;" >
                        <b>&nbsp;Target&nbsp;
                    </td>
                    
                    <td colspan="3" style="border: 1px solid black;background-color:#28a745;">
                        <b>&nbsp;Jumlah Realisasi (Rp)&nbsp;
                    </td>
                     <td colspan="2" style="border: 1px solid black;background-color:#28a745;">
                        <b>&nbsp;Selisih&nbsp;
                    </td>
                    
                </tr>
                <tr>
                    <td style="border: 1px solid black;background-color:#28a745;">
                        <b>&nbsp;s/d Bulan lalu&nbsp;
                    </td>
                    <td style="border: 1px solid black;background-color:#28a745;">
                        <b>&nbsp;Bulan ini&nbsp;
                    </td>
                    <td style="border: 1px solid black;background-color:#28a745;">
                        <b>&nbsp;s/d Bulan ini&nbsp;                        
                    </td>
                     <td style="border: 1px solid black;background-color:#28a745;">
                        <b>&nbsp;Selisih Target&nbsp;
                    </td>
                    <td style="border: 1px solid black;background-color:#28a745;">
                        <b>&nbsp;%&nbsp;                        
                    </td>
                   
                </tr>
            </thead>
             <tbody>
           
            <?php
            $totalbulanlalu=0;
            $totalbulanini=0;
            $totalsampaidenganbulanini=0;

            foreach ($data as $k){
                $datatransaksi=$k['datatransaksi'];
                $totaltargetopd=$k['totaltarget'];
               $totall=$k['totaltarget']+$k['totalbulanlalu']+$k['totalbulanini']+$k['totalsampaidenganbulanini'];
                // var_dump($k['totalbulanlalu']);exit(); 
                $dataopd=$k['dataopd']; if ($totall >0){?>

            <tr style="background-color:#bbf283">
                 <td colspan="10" style="text-align: left;border: 1px solid black;"><b><?=$dataopd['s_kodesatker'] ?>&nbsp;<?=$dataopd['s_namasatker']?></td>
                 <td colspan="1" style="text-align: right;border: 1px solid black;"><b><?= number_format($k['totaltarget'], 2, ',', '.')?></b></td>
                 <td colspan="1" style="text-align: right;border: 1px solid black;"><b><?= number_format($k['totalbulanlalu'], 2, ',', '.')?></b></td>
                  <td colspan="1" style="text-align: right;border: 1px solid black;"><b><?= number_format($k['totalbulanini'], 2, ',', '.')?></b></td>
                <td colspan="1" style="text-align: right;border: 1px solid black;"><b><?= number_format($k['totalsampaidenganbulanini'], 2, ',', '.')?></b></td>
                <td colspan="1" style="text-align: right;border: 1px solid black;"><b><?= number_format($k['selisihtotal'], 2, ',', '.')?></b></td>
                <td colspan="1" style="text-align: right;border: 1px solid black;"><b><?= number_format($k['persentotal'], 2, ',', '.')?></b></td>
            </tr>

             <?php } $no=1; foreach ($datatransaksi as $key) {
               
                $korek=$key['korek'];
                
               
                if (empty($key['s_target'])){
                    $targets=0;
                }else{
                $targets=$key['s_target'];
                }
                if (empty($key['bulanini'])){
                    $bulanini=0;
                }else{
                $bulanini=$key['bulanini'];
                }
                if (empty($key['bulanlalu'])){
                    $bulanlalu=0;
                }else{
                 $bulanlalu=$key['bulanlalu'];
                }

                // var_dump($targets);
                $sampaidenganbulanini=$key['sdbulanini'];
                $total= $targets+$bulanini+$bulanlalu;
                if (!empty($key['s_idsatker'])||$total > 0 ){
                $korekpokok=$key['korekpokok'];
                $selisih = ((int)$key['sampaidenganbulanini'])-((int)$key['target']);
                $persen =round(($key['sampaidenganbulanini'] / ((int)$key['target']) * 100),4);
               
                
                    
             
                if ($key['s_jenisobjek'] <=11 ){
                    $pajak="Pajak &nbsp;";
                }else{
                    $pajak="";
                }
                ?>

            

           
                <?php if  ($key['s_jenisobjek'] !=6){?>
                     <tr>
               <td colspan="3" style="text-align: left;background-color:#bbf283 ;border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; "><?=substr($key['korek'], 0, 12) ?></td>
               <td colspan="7" style="text-align: left;background-color:#bbf283 ; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; "><?=$pajak.$key['s_namakorek'] ?></td>
              
               <td colspan="1" style="text-align: right; background-color:#bbf283 ; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; "><?= number_format($targets, 2, ',', '.') ?></td>
               <td colspan="1" style="text-align: right; background-color:#bbf283 ; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; "><?= number_format($bulanlalu, 2, ',', '.') ?></td>
               <td colspan="1" style="text-align: right; background-color:#bbf283 ; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; "><?= number_format($bulanini, 2, ',', '.') ?></td> 
               <td colspan="1" style="text-align: right; background-color:#bbf283 ; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; "><?= number_format($key['sdbulanini'], 2, ',', '.') ?></td> 
               <td colspan="1" style="text-align: right; background-color:#bbf283 ; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; "><?= number_format($selisih, 2, ',', '.') ?></td>
              <td colspan="1" style="text-align: right; background-color:#bbf283 ; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; "><?=$persen ?></td>
                </tr>
               <?php } 

              if ($key['s_idkorek']==85){
                $bgcol='background-color:#bbf283';
                $bulanini=$minerbabulanini;
                $bulanlalu=$minerbulanlalu;
                $sampaidenganbulanini=$bulanini+$bulanlalu;
                $selisih=$sampaidenganbulanini-$targets;
                $persen=$totalsampaidenganbulanini / $targets*100;
               }else{
                $bgcol='';
               }
               ?>
               
            
               <tr style="text-align: right; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; <?=$bgcol?>">
               <td colspan="3" style="text-align: left; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; <?=$bgcol?>"><?=$key['korek'] ?></td>
               <td colspan="7" style="text-align: left; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; <?=$bgcol?>"><?=$key['s_namakorek'] ?></td>
                <td colspan="1" style="text-align: right; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; <?=$bgcol?>"><?= number_format($targets, 2, ',', '.') ?></td>
               <td colspan="1" style="text-align: right; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; <?=$bgcol?>"><?= number_format($bulanlalu, 2, ',', '.') ?></td>
               <td colspan="1" style="text-align: right; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; <?=$bgcol?>"><?= number_format($bulanini, 2, ',', '.') ?></td> 
               <td colspan="1" style="text-align: right; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; <?=$bgcol?>"><?= number_format($sampaidenganbulanini, 2, ',', '.') ?></td>
               <td colspan="1" style="text-align: right; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; <?=$bgcol?>"><?= number_format($selisih, 2, ',', '.') ?></td>
              <td colspan="1" style="text-align: right; border-left: 1px solid black; border-right: 1px solid black; border-bottom: 0.5px solid black; <?=$bgcol?>"><?=$persen ?></td>
            </tr>
             <?php 
           
              }
            }
           
               ?>

 
           

              <?php } ?>

            
            </tbody>
           

        </table>
        <br>
        <br>
  
        <table width="100%" class="mengetahui">
            <tr class="mengetahui"> 
          
                <td colspan="8" style=" width: 35%; text-align: center;vertical-align: bottom;" class="mengetahui">
                    Mengetahui<br>
                    <?= $ar_mengetahui->s_jabatanpej ?>
                    <br><br><br><br><br><br><br>
                    <u><b><?= $ar_mengetahui->s_namapej ?></b></u><br>
                    NIP <?= $ar_mengetahui->s_nippej ?>
                </td>
                 <td  style=" width: 30%" class="mengetahui"></td>
                       <td colspan="7" style=" width: 35%;text-align: center;vertical-align: bottom;" class="mengetahui">
                    <?= $ar_pemda->s_namaibukotakabkota . ', ' . date('d', strtotime($tglcetak)) . " " . $namabulan_text[date('m', strtotime($tglcetak)) - 1] . " " . date('Y', strtotime($tglcetak)) ?>
                    <br>
                    Diperiksa Oleh<br>
                    <?= $ar_diperiksa->s_jabatanpej ?>
                    <br><br><br><br><br><br><br>
                    <u><b><?= $ar_diperiksa->s_namapej ?></b></u><br>
                    NIP <?= $ar_diperiksa->s_nippej ?>  
                </td>
                
            </tr>
        </table>
    </div>
</body>
</html>