<footer class="main-footer">
    <div class="pull-right hidden-sm" style="padding:10px;">
        <!--<b>Beta Version</b>-->

        <?php
        if (date('Y') == 2021) {
            echo '<a href="javascript:void(0);">
                    <img width="12" src="' . $this->basePath() . '/public/upload/Lambang_Kabupaten_Pulang_Pisau.webp.png"> BPPKAD Pulang Pisau</a>';
        } else {
            echo  '<a href="javascript:void(0);"> <img width="12" src="' . $this->basePath() . '/public/upload/Lambang_Kabupaten_Pulang_Pisau.webp.png"> BPPKAD Pulang Pisau</a>';
        }
        ?>
    </div>
    <!--<strong>Copyright &copy; 2017 <a href="#">PT. MITRA PRIMA UTAMA</a>.</strong>-->
</footer>