<html>
    <head>
        <style type="text/css">            
            .border_atas {
                border-top: 1px solid black;
                border-collapse: collapse;
            }

            .border_kiri {
                border-left: 1px solid black;
                border-collapse: collapse;
            }

            .border_kanan {
                border-right: 1px solid black;
                border-collapse: collapse;
            }

            .border_bawah {
                border-bottom: 1px solid black;
                border-collapse: collapse;
            }

            .font_lima {
                font-size: 5pt;
            }

            .font_tujuh {
                font-size: 7pt;
            }  

            .font_delapan {
                font-size: 8pt;
            }    

            .font_sembilan {
                font-size: 9pt;
            }    

            .font_sepuluh {
                font-size: 10pt;
            }

            .font_duabelas {
                font-size: 12pt;
            }
            
            table{font-family: Arial;}
        </style>
    </head>
    <body>
        <?php
        ini_set("max_execution_time", 500);
        if (!function_exists('kekata')) {

            function kekata($x) {
                $x = abs($x);
                $angka = array("", "Satu", "Dua", "Tiga", "Empat", "Lima",
                    "Enam", "Tujuh", "Delapan", "Sembilan", "Sepuluh", "Sebelas");
                $temp = "";
                if ($x < 12) {
                    $temp = " " . $angka[$x];
                } else if ($x < 20) {
                    $temp = kekata($x - 10) . " Belas";
                } else if ($x < 100) {
                    $temp = kekata($x / 10) . " Puluh" . kekata($x % 10);
                } else if ($x < 200) {
                    $temp = " Seratus" . kekata($x - 100);
                } else if ($x < 1000) {
                    $temp = kekata($x / 100) . " Ratus" . kekata($x % 100);
                } else if ($x < 2000) {
                    $temp = " Seribu" . kekata($x - 1000);
                } else if ($x < 1000000) {
                    $temp = kekata($x / 1000) . " Ribu" . kekata($x % 1000);
                } else if ($x < 1000000000) {
                    $temp = kekata($x / 1000000) . " Juta" . kekata($x % 1000000);
                } else if ($x < 1000000000000) {
                    $temp = kekata($x / 1000000000) . " Milyar" . kekata(fmod($x, 1000000000));
                } else if ($x < 1000000000000000) {
                    $temp = kekata($x / 1000000000000) . " Trilyun" . kekata(fmod($x, 1000000000000));
                }
                return $temp;
            }

        }

        function terbilang($x, $style = 4) {
            if ($x < 0) {
                $hasil = "MINUS " . trim(kekata($x));
            } else {
                $hasil = trim(kekata($x));
            }
            switch ($style) {
                case 1:
                    $hasil = strtoupper($hasil);
                    break;
                case 2:
                    $hasil = strtolower($hasil);
                    break;
                case 3:
                    $hasil = ucwords($hasil);
                    break;
                default:
                    $hasil = ucfirst($hasil);
                    break;
            }
            return $hasil;
        }

        $abulan = ['01' => 'Januari', '02' => 'Februari', '03' => 'Maret', '04' => 'April', '05' => 'Mei', '06' => 'Juni', '07' => 'Juli', '08' => 'Agustus', '09' => 'September', '10' => 'Oktober', '11' => 'November', '12' => 'Desember'];
        $t_tglpenetapan = date('d', strtotime($data['t_tglpenetapan'])) . " " . $abulan[date('m', strtotime($data['t_tglpenetapan']))] . " " . date('Y', strtotime($data['t_tglpenetapan']));
        ?>
        <table class="border_atas border_bawah border_kanan border_kiri font_delapan" style="width: 100%">
            <tr>
                <td style="width: 7%" class="border_atas border_bawah  border_kiri font_delapan">
                    <img src="<?= $_SERVER['DOCUMENT_ROOT'] . "" . $this->basePath() . "/" . $ar_pemda->s_logo; ?>" style="width:60px;"  />
                </td>
                <td style="width: 45%" class="border_atas border_bawah border_kanan border_kiri font_delapan">
                    <b style="font-size:14px;">PEMERINTAH KABUPATEN <?= strtoupper($ar_pemda->s_namakabkota) ?></b>
                    <br>
                    <b style="font-size:18px;"><?= strtoupper($ar_pemda->s_namainstansi) ?></b>
                    <br>
                    <?= $ar_pemda->s_alamatinstansi ?> <?= $ar_pemda->s_namaibukotakabkota ?> Telp/Fax <?= $ar_pemda->s_notelinstansi ?>
                </td>
                <td class="border_atas border_bawah border_kanan border_kiri font_delapan" style="width: 40%; padding-left: 10px;">
                    <table >
                        <tr>
                            <td style="text-align: center;"><center>
                                <b style="font-size: 18px;text-align: ">NPPD</b> <br>
                                <span style="font-size:14px;">(NOTA PERHITUNGAN PAJAK DAERAH)</span>
                            </center>
                        </td>
                    </tr>
                    <tr>
                        <td>
                       
                            Masa Pajak &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <?= date('d-m-Y', strtotime($data['t_masaawal'])); ?> S/D <?= date('d-m-Y', strtotime($data['t_masaakhir'])); ?>
                            <br>
                            Tahun Pajak &nbsp;&nbsp;&nbsp;: <?= $data['t_periodepajak']; ?>
                        </td>
                    </tr>
                </table>
            </td>
                <td class="border_atas border_bawah border_kanan border_kiri font_delapan" style="width: 15%;text-align: center;">
                    No. SKPD : <?= str_pad($data['t_nopenetapan'], 5, 0, STR_PAD_LEFT) ?><br>
                    <!-- <?= $data['t_nourut'] ?> -->
                </td>
            </tr>
        </table>
         <table class="border_bawah border_kanan border_kiri" style="width: 100%;font-size:9pt;">
            <tr>
                <td style="width: 5%; padding:0; border-spacing:0px; padding-left: 15px; padding-top: 10px;">
                    <b>I.</b>
                </td>
                <td colspan="2" style="padding:0;border-spacing:0px; padding-top: 10px;">
                    <b>Data Wajib Pajak</b>
                </td>
            </tr>
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                </td>
                <td style="padding:0; border-spacing:0px;">
                    NPWPD
                </td>
                <td class="border_kanan" style="padding:0;border-spacing:0px;">
                    : <?= $data['t_npwpd'] ?>
                </td>
            </tr>
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                </td>
                <td style="width: 20%; padding:0; border-spacing:0px;">
                    Nama
                </td>
                <td style="padding:0;border-spacing:0px;">
                    : <?= $data['t_nama'] ?>
                </td>
            </tr>
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                </td>
                <td style="padding:0; border-spacing:0px;vertical-align:top;">
                    Alamat
                </td>
                <td style="padding:0;border-spacing:0px;">
                    : <?= $data['t_alamat'] . ", KEL. " . $data['s_namakel'] . ", KEC. " . $data['s_namakec'] . ", KAB. " . strtoupper($data['t_kabupaten']) ?>
                </td>
            </tr>
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                </td>
                <td style="padding:0; border-spacing:0px;">
                    NIOP
                </td>
                <td class="border_kanan" style="padding:0;border-spacing:0px;">
                    : <?= $data['t_nop'] ?>
                </td>
            </tr>
            
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 15px; padding-bottom: 0px">
                    <b>II.</b>
                </td>
                <td style="padding:0; border-spacing:0px; padding-bottom:0px;font-size:9pt;">
                    <b>Data Objek Pajak</b>
                </td>
            </tr>
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                </td>
                <td style="padding:0; border-spacing:0px;">
                    Nama Objek
                </td>
                <td class="border_kanan" style="padding:0;border-spacing:0px;">
                    : <?= $data['t_namaobjek'] ?>
                </td>
            </tr>
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                </td>
                <td style="padding:0; border-spacing:0px;vertical-align:top;">
                    Alamat Objek
                </td>
                <td class="border_kanan" style="padding:0;border-spacing:0px;">
                    : <?= $data['t_alamatobjek'] . ", KEL. " . $data['s_namakelobjek'] . ", KEC. " . $data['s_namakecobjek'] ?>
                </td>
            </tr>
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                </td>
                <td style="padding:0; border-spacing:0px;vertical-align:top;">
                    Jenis Pajak
                </td>
                <td class="border_kanan" style="padding:0;border-spacing:0px;">
                    : <?= strtoupper($data['s_namajenis']) ?>
                </td>
            </tr>
             <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 15px;">

                </td>
                <td style="padding:0; border-spacing:0px;vertical-align:top;">
                    Kode Rekening
                </td>
                <td class="border_kanan" style="padding:0;border-spacing:0px;">
                    : <?= $data['korek']  . " " . $data['s_namakorek'] ?>
                </td>
            </tr>
        </table>
        <table class="border_bawah border_kanan border_kiri font_delapan" style="width: 100%;">
            <tr style="text-align: center">
                <td class="border_kanan border_kiri" style="padding-top: 10px;">
                    <table style="margin-left: 15px; margin-right: 15px; padding-top: 10px; border: 1px solid black; border-collapse: collapse; width: 100%; margin-bottom: 10px; vertical-align: top"cellpadding="3";>
                        <tr>
                            <td style="width: 5%; border: 1px solid black; border-collapse: collapse; text-align: center">
                                NO.
                            </td>
                            
                            <td style="border: 1px solid black; border-collapse: collapse; text-align: center">
                                URAIAN
                            </td>
                            <td style="border: 1px solid black; border-collapse: collapse; text-align: center">
                                JUMLAH (Rp.)
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: center; border: 1px solid black; border-collapse: collapse">
                                1.
                            </td>
                            
                            <td style="border: 1px solid black; border-collapse: collapse; width: 400px;font-size: 12px;">
                                    &nbsp; Perhitungan <?= $data['s_namajenis'] ?> ditetapkan sebagai berikut :<br>
                                <?php if ($jenisobjek == 4) { ?>
                                    <?php

                                    if ($data['t_tipewaktu']=='2'||$data['t_tipewaktu']=="2") {
                                        $t_tipewaktu="Bulan";
                                    }elseif ($data['t_tipewaktu']=='3'||$data['t_tipewaktu']=="3") {
                                       $t_tipewaktu="Hari";
                                    }else{
                                    $t_tipewaktu="";
                                    }

                                    $koderek = (int) substr($data['korek'], 9, 2);
                                    ?>
                                    &nbsp; Jenis Reklame : <?= $ar_jenisreklame['s_namareklamejenis'] ?><br>
                                    &nbsp; Judul/Naskah : <?= $data['t_naskah'] ?><br>
                                    &nbsp; Lokasi : <?= $data['t_lokasi'] ?><br>
                                    &nbsp; Range Ukuran Media : <?=$dataukuran['s_keteranganukuran']?><br>
                                    &nbsp; Jumlah Reklame : <?=$data['t_jumlah'] ?><br>
                                    &nbsp; Jangka Waktu : <?= $data['t_jangkawaktu'].' '.$t_tipewaktu ?><br>
                                    &nbsp; Parameter : <?= $data['t_parameter']." x ".$data['t_tarifpajak']."% (tarif pajak)";?><br>
                                    &nbsp; Jumlah Pajak &nbsp;&nbsp;: Rp. <?= number_format($data['t_jmlhpajak'], 0, ',', '.'); ?>

                                    
                                    <table style="vertical-align: top;font-size: 11px;">
                                        
                                        <tr>
                                            <td colspan="3"></td>
                                        </tr>
                                    </table>
                                <?php
                                } elseif ($jenisobjek == 8) {
                                    ?>

                                    <table style="vertical-align: top;font-size: 11px">
 
                                         <tr>
                                            
                                            <td>
                                                Total biaya 
                                            </td>
                                            <td>
                                                : Rp <?= number_format($data['t_totalbiaya'], 0, ",", ".") ?>,-
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Debit Air
                                            </td>
                                            <td>
                                                : <?= number_format($data['t_debitair'], 0, ",", ".") ?> m<sup>3</sup>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                VPA
                                            </td>
                                            <td>
                                                : <?= number_format($data['t_volume'], 0, ",", ".") ?> m<sup>3</sup>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Parameter Lain
                                            </td>
                                            <td>
                                                <?php if ($data['t_kualitasair']==1||$data['t_kualitasair']=='1'){
                                                    $kualitas = "Kualitas Jelek";
                                                }elseif($data['t_kualitasair']==4||$data['t_kualitasair']=='4'){
                                                    $kualitas ="Kualitas Baik Tidak Ada Alternatif";
                                                }else{
                                                    $kualitas ="Kualitas Baik Memiliki Alternatif";
                                                }

                                                if($data['t_peruntukan']==1||$data['t_peruntukan']=='1'){
                                                    $peruntukan = "Non Niaga";
                                                }elseif($data['t_peruntukan']==2||$data['t_peruntukan']=='2'){
                                                    $peruntukan = "Niaga Kecil";
                                                }elseif($data['t_peruntukan']==3||$data['t_peruntukan']=='3'){
                                                    $peruntukan = "Niaga Besar";
                                                }elseif($data['t_peruntukan']==4||$data['t_peruntukan']=='4'){
                                                    $peruntukan = "Industri Kecil";
                                                }else{
                                                    $peruntukan = "Industri Besar";
                                                } ?>
                                                : <?=$kualitas.", ".$peruntukan?>


                                            
                                            </td>
                                        </tr>
                                        <tr>

                                            <td>
                                               Total NPA
                                            </td>
                                            <td>
                                                : <?= number_format($data['t_npa'], 0, ",", ".") ?> m<sup>3</sup>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Perhitungan 
                                            </td>
                                            <td>
                                                : (Total NPA x Tarif(<?=$data['t_tarifdasarkorek']?> %)<br>
                                                : (<?= number_format($data['t_npa'], 0, ",", ".") ?> x <?=$data['t_tarifdasarkorek']?>) / 100 
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                               Jumlah Pajak 
                                            </td>
                                            <td>
                                                : Rp. <?= number_format($data['t_jmlhpajak'], 0, ',', '.'); ?>,-
                                            </td>
                                        </tr>
                                    </table>
                                            <?php } ?>
                            </td>
                            <td style="border: 1px solid black; border-collapse: collapse; text-align: right;width: 15%">
                                <?= number_format($data['t_jmlhpajak'], 0, ',', '.'); ?>
                            </td>
                        </tr>
                        <tr>
                            <th style="text-align: center; border: 1px solid black; border-collapse: collapse" colspan="2">
                                Jumlah Pajak
                            </th>
                            <th style="border: 1px solid black; border-collapse: collapse; text-align: right">
                            <?= number_format($data['t_jmlhpajak'], 0, ',', '.'); ?>
                            </th>
                        </tr>
                        <tr>
                            <td style="border: 1px solid black; border-collapse: collapse" colspan="3">
                                Dengan Huruf : <i><?= terbilang($data['t_jmlhpajak']); ?> Rupiah</i>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <table class="border_bawah border_kanan border_kiri font_delapan" style="width: 100%;font-size:9pt;">
            
        </table>
        <table class="border_bawah border_kanan border_kiri font_delapan" style="width: 100%">
            <tr>
                <td style="width: 50%; padding-top: 5px; text-align: center; font-size:10pt; padding-left: 15px">
                    <br>
<?= ucwords(strtolower($ar_ttd1->s_jabatanpej)) ?>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <u><b><?= $ar_ttd1->s_namapej ?></b></u><br>
                    NIP. <?= $ar_ttd1->s_nippej ?>
                </td>
                <td style="text-align: center; padding-top: 5px;font-size:10pt;">
                    <?= $ar_pemda->s_namaibukotakabkota ?>, <?= $t_tglpenetapan ?><br>
<?= ucwords(strtolower($ar_ttd0->s_jabatanpej)) ?>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <u><b><?= $ar_ttd0->s_namapej ?></b></u><br>
                    NIP. <?= $ar_ttd0->s_nippej ?>
                </td>
            </tr>
        </table>
        
    </body>
</html>