<?php

ini_set("max_execution_time", 5000);
ini_set('memory_limit', '1024M');
if($data_get['jniscetak'] == 1){

include($_SERVER['DOCUMENT_ROOT'] . "/" . $this->basePath() . '/public/cetakan/MPDF57/mpdf.php');
$mpdf = new mPDF('utf-8', 'Legal-L', 0, '', 10, 10, 5, 1, 1, 1, '');
//$mpdf = new mPDF('utf-8', array(215.9,279.4), 7, 7, 7, 7, 7, 1, '');

$numbering = '<htmlpageheader name="MyHeader1">

            </htmlpageheader>

            <htmlpageheader name="MyHeader2">

            </htmlpageheader>

            <htmlpagefooter name="MyFooter1">
            <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
                color: #000000; font-weight: bold; font-style: italic;"><tr>
                <td width="33%"><span style="font-weight: bold; font-style: italic;"></span></td>
                <td width="33%" align="center" style="font-weight: bold; font-style: italic;">{PAGENO}/{nbpg}</td>
                <td width="33%" style="text-align: right; "></td>
                </tr></table>
            </htmlpagefooter>

            <htmlpagefooter name="MyFooter2">
            <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
                color: #000000; font-weight: bold; font-style: italic;"><tr>
                <td width="33%"><span style="font-weight: bold; font-style: italic;"></span></td>
                <td width="33%" align="center" style="font-weight: bold; font-style: italic;">{PAGENO}/{nbpg}</td>
                <td width="33%" style="text-align: right; "></td>
                </tr></table>
            </htmlpagefooter>';

}else{
    header("Content-type: application/vnd-ms-excel");

    header("Content-Disposition: attachment; filename=cetakrekapitulasi" . $data_get['tgl0']."_sd_".$data_get['tgl1'].".xls");
    
    $numbering = "";
}
if(!empty($data_get['jenisobjek'])){
$jenisobjek = $this->MenuHelper()->cekjenispajak($data_get['jenisobjek']);
$namaobjeknya = strtoupper($jenisobjek['s_namajenis']);
}else{
    $namaobjeknya = '';
}

if(!empty($data_get['t_kecamatan_objek'])){
    $cekkecamatan = $this->MenuHelper()->cekkecamatan($data_get['t_kecamatan_objek']);
    $namakec = "<br> KECAMATAN ".$cekkecamatan['s_namakec'];
}else{
    $namakec = "";
}

if(!empty($data_get['t_kelurahan_objek'])){
    $cekkelurahan = $this->MenuHelper()->cekkelurahan($data_get['t_kelurahan_objek']);
    $namakel = "KELURAHAN ".$cekkelurahan['s_namakel'];
}else{
    $namakel = "";
}

if(!empty($data_get['t_idobjek'])){
    $ceknamaobjek = $this->MenuHelper()->cekobjekwp($data_get['t_idobjek']);
    $namaobjek = '<br> NAMA OBJEK : '.strtoupper($ceknamaobjek['t_namaobjek']);
}else{
    $namaobjek = "";
}

$html = '';
$html .= '
<html>
    <head>
        <style type="text/css">            
            @page {
                size: auto;
                odd-header-name: html_MyHeader1;
                odd-footer-name: html_MyFooter1;
              }
              @page chapter2 {
                  odd-header-name: html_MyHeader2;
                  odd-footer-name: html_MyFooter2;
              }
              @page noheader {
                  odd-header-name: _blank;
                  odd-footer-name: _blank;
              }
              div.chapter2 {
                  page-break-before: always;
                  page: chapter2;
              }
              div.noheader {
                  page-break-before: always;
                  page: noheader;
              }
            .border_atas {
                    border-top: 1px solid black;
                    border-collapse: collapse;
            }

            .border_kiri {
                    border-left: 1px solid black;
                    border-collapse: collapse;
            }

            .border_kanan {
                    border-right: 1px solid black;
                    border-collapse: collapse;
            }

            .border_bawah {
                    border-bottom: 1px solid black;
                    border-collapse: collapse;
            }

            

        </style>
    </head>
    <body>
            
            '.$numbering.'

            <table width="100%" style="border-spacing:0px;">
                <tr>
                    <td colspan="14">
                        <center>
                        <b style="font-size: 18px;">DAFTAR REKAPITULASI PAJAK PPJ
                        '.$namakec.' '.$namakel.'
                        '.$namaobjek.'    
                        <br>TANGGAL PENDATAAN '.$data_get['tgl0'].' s/d '.$data_get['tgl1'].' </b>
                        </center>    
                    </td>
                </tr>
                 <tr>
                    <td colspan="14">&nbsp;</td>
                </tr>      
                <tr>
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" >
                       <center><b> NO</b></center>
                    </td>
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> NPWPD</b></center>
                    </td>
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> NAMA WAJIB PAJAK</b></center>
                    </td>
                    
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>ALAMAT</b></center>
                    </td>
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>JENIS KETETAPAN</b></center>
                    </td>
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>NO SPTPD</b></center>
                    </td>
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>REKENING</b></center>
                    </td>
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> MASA PAJAK</b></center>
                    </td>
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> PEMAKAIAN (Kwh)</b></center>
                    </td>
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> JUMLAH PAJAK</b></center>
                    </td>
                    <td colspan="3" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> PEMBAYARAN</b></center>
                    </td>
                    
                    <td rowspan="2" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> DARI</b></center>
                    </td>
                    
                </tr>
                <tr>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> JUMLAH</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>TANGGAL</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>KET</b></center>
                    </td>
                </tr>
                <tr>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>1</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> 2</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b>3</b></center>
                    </td>
                    
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> 4</b></center>
                    </td >
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>5</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> 6</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>7</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b>8</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                      <center><b> 9</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                       <center><b> 10</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                      <center><b> 11</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>12</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>13</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>14</b></center>
                    </td>
                    
                </tr>';
                
                
                $totalkeseluruhan = 0;
                $no = 1;
                $clast_rek_kel = '';
                $clast_rek = '';
                $totalsubkel = 0;
                $totalsubkec = 0;
                
                $totalkwhlistrik = 0;
                $totalpajakterutang = 0;
                $totaljmlhbayar = 0;
                
                
                
                
                $totalsubkel_kwhlistrik = 0;
                $totalsubkel_terhutang = 0;
                $totalsubkel_jmlhbayar = 0;
                $totalsubkel_sanksi = 0;
                
                
                $totalsubkec_kwhlistrik = 0;
                $totalsubkec_trhutang = 0;
                
                
                $totalsubkec_dbyr = 0;
                
                
                $totalsubtgl_kwhlistrik = 0;
                $totalsubtgl_terhutang = 0;
                $totalsubtgl_jmlpembayaran = 0;
                
                
                
                $last_tanggalpendataan = '';
                $last_tanggalpendataan_name = '';
                
                $last_berdasarrekening = '';
                $last_berdasarrekening_name = '';
                
                $totalsubrek_kwhlistrik = 0;
                $totalsubrek_terhutang = 0;
                $totalsubrek_jmlhbayar = 0;
                
                
                
                foreach ($data as $k => $v) {
                    
                    
if($v['t_bidangusaha'] == 2){
    $namawp = $v['t_nama_badan'];
    $alamatwp = '';
    if(!empty($v['t_jalan_badan'])){
        $alamatwp .= $v['t_jalan_badan'];
    }
    if(!empty($v['t_rt_badan'])){
        $alamatwp .= ' RT '.$v['t_rt_badan'];
    }
    if(!empty($v['t_rw_badan'])){
        $alamatwp .= ' RW '.$v['t_rw_badan'];
    }
    if(!empty($v['s_namakelbadan'])){
        $alamatwp .= ' Kel. '.$v['s_namakelbadan'];
    }
    if(!empty($v['s_namakecbadan'])){
        $alamatwp .= ' Kec. '.$v['s_namakecbadan'];
    }
    if(!empty($v['t_kabupaten_badan'])){
        $alamatwp .= ' Kab. '.$v['t_kabupaten_badan'];
    }
}else{
    $namawp = $v['t_nama'];
    $alamatwp = '';
    if(!empty($v['t_alamat'])){
        $alamatwp .= $v['t_alamat'];
    }
    if(!empty($v['t_rt'])){
        $alamatwp .= ' RT '.$v['t_rt'];
    }
    if(!empty($v['t_rw'])){
        $alamatwp .= ' RW '.$v['t_rw'];
    }
    if(!empty($v['s_namakel'])){
        $alamatwp .= ' Kel. '.$v['s_namakel'];
    }
    if(!empty($v['s_namakec'])){
        $alamatwp .= ' Kec. '.$v['s_namakec'];
    }
    if(!empty($v['t_kabupaten'])){
        $alamatwp .= ' Kab. '.$v['t_kabupaten'];
    }
}

if(!empty($v['t_tglpembayaran'])){
        $tglbayar = date('d-m-Y', strtotime($v['t_tglpembayaran']));
        $jmlhpembayaran = number_format($v['t_jmlhpembayaran'], 2, ",", ".");
        
        
        $statusbayar = 'LUNAS';
}else{
   
        $tglbayar = '-';
        $jmlhpembayaran = 0;
        
        $statusbayar = 'BELUM';
    
}

                if ($data_get['urutkan'] == 1) {
                    if ($last_tanggalpendataan <> $v['t_tglpendataan']) {

                        if ($last_tanggalpendataan <> '') {

                             $html .= '<tr>
                                            <td colspan="8" style="border-bottom: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;" align="right"><b>JUMLAH '. strtoupper($last_tanggalpendataan_name) .'</b>&nbsp;</td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubtgl_kwhlistrik, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubtgl_terhutang, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubtgl_jmlpembayaran, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>    

                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right">&nbsp;</td>   
                              </tr>'; 

                             $totalsubtgl_kwhlistrik = 0;
                             $totalsubtgl_terhutang = 0;
                             $totalsubtgl_jmlpembayaran = 0;
                             
                            
                        }


                        $html .= '<tr>
                                                <td colspan="14" align="left" style="border-bottom: 1px solid #000;border-top: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;"><b>TANGGAL PENDATAAN : ' . date('d-m-Y', strtotime($v['t_tglpendataan'])) . '</b></td>

                                            </tr>';

                        $last_tanggalpendataan = $v['t_tglpendataan'];
                        $last_tanggalpendataan_name = date('d-m-Y', strtotime($v['t_tglpendataan']));
                        //$counter = 1;
                    }
                }


                if($data_get['urutkan'] == 2){    
                    if ($clast_rek_kel <> $v['t_kelurahan_objek']) {
                        if ($clast_rek_kel <> '') {
                            $html .= '<tr>
                                            <td colspan="8" style="border-bottom: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;">Jumlah se-kelurahan '. strtoupper($clast_rek_name_kel) .'</td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubkel_kwhlistrik, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubkel_terhutang, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubkel_jmlhbayar, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>    

                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right">&nbsp;</td>


                                </tr>';
                            $totalSetoran_sub_kel = 0;
                            $totalsubkel = 0;
                            
                            $totalsubkel_kwhlistrik = 0;
                            $totalsubkel_terhutang = 0;
                            $totalsubkel_jmlhbayar = 0;
                            
                            
                            
                        }
                        if ($clast_rek <> $v['t_kecamatan_objek']) {
                            if ($clast_rek <> '') {
                                $html .= '<tr>

                                           <td colspan="8" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="center"><b><i>JUMLAH SE-KECAMATAN '. strtoupper($clast_rek_name) .'</i></b></td>
                                            <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right"><b>'. number_format($totalsubkec_kwhlistrik, 2, ',', '.') . '</b></td>
                                            <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right"><b>'. number_format($totalsubkec_trhutang, 2, ',', '.') . '</b></td>
                                            <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right"><b>'. number_format($totalsubkec_dbyr, 2, ',', '.') . '</b></td>
                                            <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right"><b>&nbsp;</b></td>
                                            <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right"><b>&nbsp;</b></td>
                                                
                                            <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">&nbsp;</td>


                                        </tr>';
                                $totalSetoran_sub = 0;
                                $totalsubkec = 0;
                                
                                $totalsubkec_kwhlistrik = 0;
                                $totalsubkec_trhutang = 0;
                                
                                
                                $totalsubkec_dbyr = 0;
                                
                            }
                            $html .= '<tr>
                                        <td colspan="14" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">Kecamatan : <b> '. $v['s_namakecobjek'] .'</td>

                                        </tr>';
                            $clast_rek = $v['t_kecamatan_objek'];
                            $clast_rek_name = $v['s_namakecobjek'];
                            $counter = 1;
                        }



                        $html .= '<tr>
                                <td class="border_atas border_bawah border_kiri">&nbsp;</td>
                                <td colspan="13" class="border_atas border_bawah border_kanan">Kelurahan : <b> '. $v['s_namakelobjek'] .'</td>

                                </tr>';
                        $clast_rek_kel = $v['t_kelurahan_objek'];
                        $clast_rek_name_kel = $v['s_namakelobjek'];
                        $counter = 1;
                    }
                }
                
                
                if ($data_get['urutkan'] == 3) {
                    
                        $koderek = $v['koderek'];
                        $s_namakorek = $v['s_namakorek'];
                    
                    
                    if ($last_berdasarrekening <> $koderek) {

                        if ($last_berdasarrekening <> '') {

                             $html .= '<tr>
                                            <td colspan="8" style="border-bottom: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;" align="right"><b>JUMLAH '. strtoupper($last_berdasarrekening_name) .'</b>&nbsp;</td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubrek_kwhlistrik, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubrek_terhutang, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubrek_jmlhbayar, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>    

                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right">&nbsp;</td>   
                              </tr>'; 

                             $totalsubrek_kwhlistrik = 0;
                             $totalsubrek_terhutang = 0;
                             $totalsubrek_jmlhbayar = 0;
                             
                             
                        }


                        $html .= '<tr>
                                                <td colspan="14" align="left" style="border-bottom: 1px solid #000;border-top: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;"><b>REKENING : ' . $s_namakorek . '</b></td>

                                            </tr>';

                        $last_berdasarrekening = $koderek;
                        $last_berdasarrekening_name = $s_namakorek;
                        //$counter = 1;
                    }
                }
                    
                    $html .= '
                        <tr>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 20px;">
                        <center>'.$no.'</center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;">
                        <center>'.$v['t_npwpd'].'</center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 160px;">
                        '.$namawp.'
                    </td>
                    
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;" >
                        '.$alamatwp.'
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>'.$v['s_namasingkatsurat'].'</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>'.$v['t_nourut'].'</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; vertical-align: top;">
                   
                        '.$v['koderek'].' <br>
                            '.$v['s_namakorek'].'
                        
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;" >
                        ' . date('d-m-Y', strtotime($v['t_masaawal'])) . ' S/D ' . date('d-m-Y', strtotime($v['t_masaakhir'])) . '
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;" align="right">
                        '.$v['t_kwhlistrik'].'
                    
                    
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;" align="right">
                    ';
                    
                    
                        $jmlpajakterhutang = number_format($v['t_jmlhpajak'], 2, ",", ".");
                    
                    $html .= ' '.$jmlpajakterhutang.'
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;" align="right">
                         '.$jmlhpembayaran.'
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;" align="right">
                       '.$tglbayar.'
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;" align="right">
                        <center><b>'.$statusbayar.'</b></center>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000; width: 100px;">
                        ';
                    if(!empty($v['s_idskpd'])){
                        $nama_skpd = 'DARI SKPD';
                    }else{
                        $nama_skpd = 'DARI WP';
                    }
                    $html .= ' '.$nama_skpd.'
                    </td>
                   
                </tr>';
                    
                    
                    
                    $totalsubkel_kwhlistrik += $v['t_kwhlistrik'];
                    $totalsubkel_terhutang += $v['t_jmlhpajak'];
                    $totalsubkel_jmlhbayar += $v['t_jmlhpembayaran'];
                    
                    
                    
                    $totalsubkec_kwhlistrik += $v['t_kwhlistrik'];
                    $totalsubkec_trhutang += $v['t_jmlhpajak'];
                    
                    
                    $totalsubkec_dbyr += $v['t_jmlhpembayaran'];
                    
                    $totalkwhlistrik += $v['t_kwhlistrik'];
                    $totalpajakterutang += $v['t_jmlhpajak'];
                    $totaljmlhbayar += $v['t_jmlhpembayaran'];
                    
                    
                    
                    
                    $totalsubtgl_kwhlistrik += $v['t_kwhlistrik'];
                    $totalsubtgl_terhutang += $v['t_jmlhpajak'];
                    $totalsubtgl_jmlpembayaran += $v['t_jmlhpembayaran'];
                    
                    
                    
                    
                    $totalsubrek_kwhlistrik += $v['t_kwhlistrik'];
                    $totalsubrek_terhutang += $v['t_jmlhpajak'];
                    $totalsubrek_jmlhbayar += $v['t_jmlhpembayaran'];
                    
                    
                    
                    
                    
                    $no++;
                }
               
                    if($data_get['urutkan'] == 1){
                        if ($last_tanggalpendataan <> '') {

                             $html .= '<tr>
                                            <td colspan="8" style="border-bottom: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;" align="right"><b>JUMLAH '. strtoupper($last_tanggalpendataan_name) .'</b>&nbsp;</td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubtgl_kwhlistrik, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubtgl_terhutang, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubtgl_jmlpembayaran, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>    

                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right">&nbsp;</td>   
                              </tr>'; 

                             $totalsubtgl_kwhlistrik = 0;
                             $totalsubtgl_terhutang = 0;
                             $totalsubtgl_jmlpembayaran = 0;
                             
                             
                        }
                    }    
                
                if($data_get['urutkan'] == 2){     
                    if ($clast_rek_kel <> '') {
                        $html .= '<tr>
                                        <td colspan="8" style="border-bottom: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;">Jumlah se-kelurahan '. strtoupper($clast_rek_name_kel) .'</td>
                                        <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubkel_kwhlistrik, 2, ',', '.') . '</i></b></td>
                                        <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubkel_terhutang, 2, ',', '.') . '</i></b></td>
                                        <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubkel_jmlhbayar, 2, ',', '.') . '</i></b></td>
                                        <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>
                                        <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>    

                                        <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right">&nbsp;</td>


                            </tr>';
                        $totalSetoran_sub_kel = 0;
                        $totalsubkel = 0;

                        $totalsubkel_kwhlistrik = 0;
                        $totalsubkel_terhutang = 0;
                        $totalsubkel_jmlhbayar = 0;
                       
                        

                    }

                    if ($clast_rek <> '') {
                        $html .= '<tr>

                                   <td colspan="8" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="center"><b><i>JUMLAH SE-KECAMATAN '. strtoupper($clast_rek_name) .'</i></b></td>
                                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right"><b>'. number_format($totalsubkec_kwhlistrik, 2, ',', '.') . '</b></td>
                                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right"><b>'. number_format($totalsubkec_trhutang, 2, ',', '.') . '</b></td>
                                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right"><b>'. number_format($totalsubkec_dbyr, 2, ',', '.') . '</b></td>
                                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right"><b>&nbsp;</b></td>
                                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right"><b>&nbsp;</b></td>

                                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">&nbsp;</td>


                                </tr>';
                        $totalSetoran_sub = 0;
                        $totalsubkec = 0;

                        $totalsubkec_kwhlistrik = 0;
                        $totalsubkec_trhutang = 0;
                        
                        
                        $totalsubkec_dbyr = 0;

                    }
                }    
                
                if($data_get['urutkan'] == 3){
                    if ($last_berdasarrekening <> '') {

                             $html .= '<tr>
                                            <td colspan="8" style="border-bottom: 1px solid #000;border-right: 1px solid #000;border-left: 1px solid #000; vertical-align:middle;" align="right"><b>JUMLAH '. strtoupper($last_berdasarrekening_name) .'</b>&nbsp;</td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubrek_kwhlistrik, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubrek_terhutang, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>'. number_format($totalsubrek_jmlhbayar, 2, ',', '.') . '</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>
                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right"><b><i>&nbsp;</i></b></td>    

                                            <td style="border-bottom: 1px solid #000;border-right: 1px solid #000; vertical-align:right;" align="right">&nbsp;</td>   
                              </tr>'; 

                             $totalsubrek_kwhlistrik = 0;
                             $totalsubrek_terhutang = 0;
                             $totalsubrek_jmlhbayar = 0;
                             
                             
                        }
                }        
                
                $html .= '
                        <tr>
                    <td colspan="8" style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;">
                        <center><b>JUMLAH TOTAL</b></center>
                    </td>
                    
                    
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        <b>'.number_format($totalkwhlistrik, 2, ",", ".").'</b>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        <b>'.number_format($totalpajakterutang, 2, ",", ".").'</b>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        <b>'.number_format($totaljmlhbayar, 2, ",", ".").'</b>
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        &nbsp;
                    </td>
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        <b>&nbsp;</b>
                    </td >
                    
                    <td style="border-top: 1px solid #000; border-bottom: 1px solid #000; border-right: 1px solid #000; border-left: 1px solid #000;" align="right">
                        
                    </td>
                </tr>
                <tr>
                    <td colspan="14">
                    &nbsp;
                    </td>
                </tr>    
                 <tr>
                    <td colspan="8">';
                        if(!empty($data_get['ttd0'])){
                            $namapejabat = $this->MenuHelper()->getnamapejabat($data_get['ttd0']);
                            $html .= '
                                <center>
                                    <br><b>'.$namapejabat['s_jabatanpej'].'
                                    
                                    <br><br><br><br><br><br>
                                    <u>&nbsp;&nbsp;&nbsp;'.$namapejabat['s_namapej'].'&nbsp;&nbsp;&nbsp;</u></b>
                                        <br>'.$namapejabat['s_nippej'].'
                                    </center>';
                        }
                $html .= '  
                    </td>
                    <td colspan="6">';
                        if(!empty($data_get['ttd1'])){
                            $namapejabat1 = $this->MenuHelper()->getnamapejabat($data_get['ttd1']);
                            $html .= '
                                <center>'.$ar_pemda->s_ttdkabkot.', '.$data_get['tglcetak'].'
                                    <br><b>'.$namapejabat1['s_jabatanpej'].'
                                    
                                    <br><br><br><br><br><br>
                                    <u>&nbsp;&nbsp;&nbsp;'.$namapejabat1['s_namapej'].'&nbsp;&nbsp;&nbsp;</u></b>
                                        <br>'.$namapejabat1['s_nippej'].'
                                    </center>';
                        }
                $html .= '    
                    </td>
                </tr>    
            </table>
        </div>
    </body>
</html>
';
if ($data_get['jniscetak'] == 1) {

    $mpdf->WriteHTML($html);
    $mpdf->Output("cetakrekapitulasi" . $data_get['tgl0']."_sd_".$data_get['tgl1'].".pdf", "I");
}else{
    echo $html;    
}
?>    