<?php
$form = $this->form;
$form->setAttribute('action', $this->url() . '/form_pageppj');
$form->setAttribute("id", "demo-form");
$form->setAttribute("class", "form-horizontal pad15L pad15R pad15T");
$form->setAttribute("data-parsley-validate", "data-parsley-validate");
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();
?>

<style type="text/css">
    blink,
    .blink {
        -webkit-animation: blink 1s step-end infinite;
        -moz-animation: blink 1s step-end infinite;
        -o-animation: blink 1s step-end infinite;
        animation: blink 1s step-end infinite;
    }

    @-webkit-keyframes blink {
        67% {
            opacity: 0
        }
    }

    @-moz-keyframes blink {
        67% {
            opacity: 0
        }
    }

    @-o-keyframes blink {
        67% {
            opacity: 0
        }
    }

    @keyframes blink {
        67% {
            opacity: 0
        }
    }
</style>
<div id="page-content-wrapper" style="font-size:12px">
    <div id="page-content" style="background-color: #DFF0D8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Pendataan <?= $datapendaftaran['s_namajenis'] ?><b class="blink" style="font-size: 12px; color: red"><?= $message ?></b>
                </h4>
            </div>
            <div class="panel-body">
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-12">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="text-align:right; background:black; color: orange; padding: 10px 10px; font-size: 16px; font-weight:bolder"><?= $datapendaftaran['t_npwpd'] ?></span>
                        </div>
                    </div>
                    <?= $this->form()->openTag($form) ?>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="alert alert-info">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Data WP</b></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2">NIK</label>
                            <div class="col-sm-4">
                                : <?= $datapendaftaran['t_nik'] ?>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2">Nama</label>
                            <div class="col-sm-4">
                                : <?= $datapendaftaran['t_nama'] ?>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2">Alamat</label>
                            <div class="col-sm-10">
                                : <?= $datapendaftaran['t_alamat'] ?>
                                ,RT. <?= $datapendaftaran['t_rt'] ?>
                                ,RW. <?= $datapendaftaran['t_rw'] ?>
                                ,Desa/Kel. <?= $datapendaftaran['s_namakel'] ?>
                                ,Kec. <?= $datapendaftaran['s_namakec'] ?>
                                ,Kab. <?= $datapendaftaran['t_kabupaten'] ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="alert alert-info">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Data OP</b></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2">NIOP</label>
                            <div class="col-sm-4">
                                : <?= $datapendaftaran['t_nop'] ?>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2">Nama</label>
                            <div class="col-sm-4">
                                : <?= $datapendaftaran['t_namaobjek'] ?>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2">Alamat</label>
                            <div class="col-sm-10">
                                : <?= $datapendaftaran['t_alamatobjek'] ?>
                                ,RT. <?= $datapendaftaran['t_rtobjek'] ?>
                                ,RW. <?= $datapendaftaran['t_rwobjek'] ?>
                                ,Desa/Kel. <?= $datapendaftaran['s_namakelobjek'] ?>
                                ,Kec. <?= $datapendaftaran['s_namakecobjek'] ?>
                                ,Kab. <?= $datapendaftaran['t_kabupatenobjek'] ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="alert alert-info">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Histori Pajak</b></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div id="datatransaksi"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="alert alert-warning">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Data Pendataan</b></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Nomor SPTPD</label>
                            <div class="col-sm-2">
                                <input type="hidden" name="t_jenisobjekpajak" value="<?= $datapendaftaran['t_jenisobjek'] ?>">
                                <?= $this->formHidden($form->get("t_idtransaksi")) ?>
                                <?= $this->formHidden($form->get("t_idobjek")) ?>
                                <?= $this->formHidden($form->get("t_jenispajak")) ?>
                                <?= $this->formText($form->get("t_nourut")) ?>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Periode Pajak</label>
                            <div class="col-sm-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_periodepajak")) ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Tanggal Pendataan</label>
                            <div class="col-sm-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_tglpendataan")) ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Masa Pajak</label>
                            <div class="col-sm-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_masaawal")) ?>
                                </div>
                            </div>
                            <label class="col-sm-1 control-label">S/D</label>
                            <div class="col-sm-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_masaakhir")) ?>
                                </div>
                            </div>
                            <?php if ($datapendaftaran['t_jenisobjek'] == 2) { ?>
                                <div class="col-sm-3">
                                    <input type="text" name="t_berdasarmasa" id="t_berdasarmasa" class="form-control" style="background:black; color: greenyellow; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder" value="<?= $t_berdasarmasa ?>">
                                </div>
                            <?php } else { ?>
                                <div class="col-sm-3">
                                    <input type="hidden" name="t_berdasarmasa" id="t_berdasarmasa">
                                </div>
                            <?php } ?>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Dasar Pengenaan</label>
                            <div class="col-sm-10 remove-columns">
                                <table class="table table-bordered table-striped table-condensed cf" style="font-size: 11px;">
                                    <tr>
                                        <th style="background-color:#00BCA4; color: white;" class="text-center">Uraian/Golongan</th>
                                        <th style="background-color:#00BCA4; color: white;" class="text-center">Jumlah Nilai Jual Tenaga Listrik (Rp.)</th>
                                        <th style="background-color:#00BCA4; color: white;" class="text-center">Tarif %</th>
                                        <th style="background-color:#00BCA4; color: white;" class="text-center">Jumlah Pajak (Rp.)</th>
                                    </tr>
                                    <?php
                                    $i = 0;
                                    foreach ($rekeningppj as $col => $row) :
                                    ?>
                                        <tr>
                                            <td><?= $row['s_namakorek'] ?></td>
                                            <td><input id="nilailistrik<?= $i ?>" name="t_nilailistrik[]" type="text" class="form-control text-right nilailistrik" data-id="<?= $i ?>" data-tarif="<?= $row['s_persentarifkorek'] ?>" onchange="hitungpajak(this);this.value = formatCurrency(this.value);" onblur="hitungpajak(this);this.value = formatCurrency(this.value);" onkeyup="hitungpajak(this);this.value = formatCurrency(this.value);" onkeypress="return numbersonly(this, event);"></td>
                                            <td class="text-right"><?= $row['s_persentarifkorek'] ?><input type="hidden" name="t_idkorek[]" value="<?= $row['s_idkorek'] ?>"></td>
                                            <td><input id="subtotalpajak<?= $i ?>" name="t_subtotalpajak[]" type="text" class="form-control text-right subtotalpajak" readonly></td>

                                        </tr>
                                    <?php
                                        $i++;
                                    endforeach;
                                    ?>
                                    <tr>
                                        <td colspan="3" class="text-right">Total Pajak (Rp.)</td>
                                        <td><?= $this->formText($form->get("t_jmlhpajak")) ?></td>
                                    </tr>
                                </table>
                            </div>

                        </div>
                        <div class="col-md-12">
                            <div class="col-sm-12">
                                <div class="alert alert-warning">
                                    <div class="alert-content">
                                        <h4 class="alert-title"><b style="color: #000099">Data Lampiran</b></h4>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table class="table table-bordered table-condensed cf" id="tableLampiran" style="font-size: 11px;">
                                        <thead>
                                            <tr>
                                                <th rowspan="2" class="text-center">NO.</th>
                                                <th colspan="7" class="text-center">VARIABEL PENENTU BESARAN TENAGA LISTRIK TERJUAL</th>
                                                <th rowspan="2" class="text-center">JML NILAI JUAL TENAGA LISTRIK (Rp.)</th>
                                                <th colspan="2" class="text-center">PENGHITUNGAN PAJAK</th>
                                                <th rowspan="3">#</th>
                                            </tr>
                                            <tr>
                                                <th class="text-center">GOL TARIF PLN</th>
                                                <th class="text-center">BATAS DAYA</th>
                                                <th class="text-center">JML PELANGGAN</th>
                                                <th class="text-center">JML KWH TERJUAL</th>
                                                <th class="text-center">TARIF PER KWH (Rp.)</th>
                                                <th class="text-center">JML LISTRIK TERJUAL (Rp.)</th>
                                                <th class="text-center">JML BIAYA BEBAN (Rp.)</th>
                                                <th class="text-center">TARIF</th>
                                                <th class="text-center">JML (Rp.)</th>
                                            </tr>
                                            <tr style="font-size:9px;">
                                                <th class="text-center">1</th>
                                                <th class="text-center">2</th>
                                                <th class="text-center">3</th>
                                                <th class="text-center">4</th>
                                                <th class="text-center">5</th>
                                                <th class="text-center">6</th>
                                                <th class="text-center">7 (4x5x6)</th>
                                                <th class="text-center">8</th>
                                                <th class="text-center">9 (7+8)</th>
                                                <th class="text-center">10</th>
                                                <th class="text-center">11 (9x10)</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td colspan="12"><b>A. PENJUALAN LISTRIK SETELAH PENGGUNAAN:</b></td>
                                            </tr>
                                            <tr class="row_a">
                                                <td class="text-center">1</td>
                                                <td><input type="text" name="t_goltarifpln1[]" class="form-control text-left"><input type="hidden" name="t_idlampiranppj1[]"></td>
                                                <td><input type="text" name="t_batasdaya1[]" class="form-control numeric"></td>
                                                <td><input type="text" name="t_jmlpelanggan1[]" class="form-control row_a_calc4 numeric"></td>
                                                <td><input type="text" name="t_jmlkwhterjual1[]" class="form-control row_a_calc5 numeric"></td>
                                                <td><input type="text" name="t_tarifperkwh1[]" class="form-control row_a_calc6 numeric"></td>
                                                <td><input type="text" name="t_jmllistrikterjual1[]" class="form-control row_a_calc7" readonly></td>
                                                <td><input type="text" name="t_jmlbiayabeban1[]" class="form-control row_a_calc8 numeric"></td>
                                                <td><input type="text" name="t_jmlnilaijuallistrik1[]" class="form-control row_a_calc9" readonly></td>
                                                <td><input type="text" name="t_tarif1[]" class="form-control row_a_calc10"></td>
                                                <td><input type="text" name="t_jumlah1[]" class="form-control row_a_calc11" readonly></td>
                                                <td><a href="javascript:;" class="btn btn-primary btn-xs btnAdd_row_a">+</a> <a href="javascript:;" class="btn btn-danger btn-xs btnDel_row_a">x</a></td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td colspan="9"><b>Jumlah A</b></td>
                                                <td><input type="text" id="t_total1" name="t_total1" class="form-control text-right row_a_total" readonly></td>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td colspan="12"><b>B. PENJUALAN LISTRIK PRABAYAR:</b></td>
                                            </tr>
                                            <tr class="row_b">
                                                <td class="text-center">1</td>
                                                <td><input type="text" name="t_goltarifpln2[]" class="form-control text-left"><input type="hidden" name="t_idlampiranppj2[]"></td>
                                                <td><input type="text" name="t_batasdaya2[]" class="form-control numeric"></td>
                                                <td><input type="text" name="t_jmlpelanggan2[]" class="form-control row_b_calc4 numeric"></td>
                                                <td><input type="text" name="t_jmlkwhterjual2[]" class="form-control row_b_calc5 numeric"></td>
                                                <td><input type="text" name="t_tarifperkwh2[]" class="form-control row_b_calc6 numeric"></td>
                                                <td><input type="text" name="t_jmllistrikterjual2[]" class="form-control row_b_calc7" readonly></td>
                                                <td><input type="text" name="t_jmlbiayabeban2[]" class="form-control row_b_calc8 numeric"></td>
                                                <td><input type="text" name="t_jmlnilaijuallistrik2[]" class="form-control row_b_calc9" readonly></td>
                                                <td><input type="text" name="t_tarif2[]" class="form-control row_b_calc10"></td>
                                                <td><input type="text" name="t_jumlah2[]" class="form-control row_b_calc11" readonly></td>
                                                <td><a href="javascript:;" class="btn btn-primary btn-xs btnAdd_row_b">+</a> <a href="javascript:;" class="btn btn-danger btn-xs btnDel_row_b">x</a></td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td colspan="9"><b>Jumlah B</b></td>
                                                <td><input type="text" id="t_total2" name="t_total2" class="form-control text-right row_b_total" readonly></td>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                                <td colspan="9"><b>Jumlah A+B</b></td>
                                                <td><input type="text" id="grandtotallampiran" class="form-control text-right" readonly></td>
                                                <td></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div id="kenaikan" style="display: none">
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Tarif Kenaikan (%)</label>
                                <div class="col-sm-1">
                                    <input type="text" name="t_tarifkenaikan" id="t_tarifkenaikan" class="form-control" readonly="" value="0">
                                </div>
                                <div class="col-sm-1">
                                    <a href="javascript:void(0)" class="btn btn-danger btn-sm" onclick="nonskpdjabatan()"><span class="glyph-icon icon-close"></span> Non SKPD Jabatan</a>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Jumlah Kenaikan</label>
                                <div class="col-sm-4">
                                    <input type="text" name="t_jmlhkenaikan" id="t_jmlhkenaikan" class="form-control" readonly="" value="0">
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="bg-default" id="tombolsimpan">
                        <?= $this->formInput($form->get('Pendataansubmit')) ?>
                    </div>
                    <?= $this->form()->closeTag($form) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalRekening" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><b>Data Rekening</b></h4>
            </div>
            <div class='modal-body'>
                <input type="hidden" id="t_jenisobjek" value="<?= $datapendaftaran['t_jenisobjek'] ?>">
                <div>
                    <table class="table table-condensed table-bordered cf" style="font-size: 11px; color: black">
                        <thead class="cf">
                            <tr class="bg-blue">
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    Kode Rekening
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    Nama Rekening
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    Tarif
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    Pilihan
                                </th>
                            </tr>
                            <tr>
                                <td>
                                    <input type="text" id="korek" class="form-control input-sm" onkeyup="calldataGridRekening()">
                                </td>
                                <td>
                                    <input type="text" id="s_namakorek" class="form-control input-sm" onkeyup="calldataGridRekening()">
                                </td>
                                <td>
                                    <input type="text" id="s_persentarifkorek" class="form-control input-sm" onkeyup="calldataGridRekening()">
                                </td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody id="listrekening">
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="4" class="text-center">
                                    <div class="row">
                                        <div class="col-sm-4 text-left">Jumlah Baris Ditampilkan: <input type="text" id="rows" style="width: 20%" class="text-center" value="10"></div>
                                        <div class="col-sm-3">
                                            <a href="#" onclick="calldataGridRekening(1);
                                                    return false;"><span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span></a>

                                            <input type="text" id="page" value="1" style="width: 20%" class="text-center">

                                            <a href="#" onclick="calldataGridRekening(2);
                                                    return false;"><span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span></a>
                                        </div>
                                        <div class="col-sm-5 text-right">
                                            <p>Jumlah Data <span id="total_data"></span>&nbsp;Jumlah Halaman <span id="total_halaman"></span></p>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    #tableLampiran th {
        background-color: #00BCA4;
        color: white;
    }

    #tableLampiran input[type=text] {
        text-align: right;
    }
</style>
<script>
    function calldataGridRekening(direction) {
        dataGridRekening($("#page").val(), $("#rows").val(), direction);
    }

    function dataGridRekening(page, row, direction) {
        $.post('<?= $this->url() ?>/dataGridRekening/' + null + '/' + page + '/' + row + '/' + direction + '?korek=' + $("#korek").val() + "&s_namakorek=" + $("#s_namakorek").val() + "&s_persentarifkorek=" + $("#s_persentarifkorek").val() + "&t_jenisobjek=" + $("#t_jenisobjek").val(), function(data) {
            var aa = JSON.parse(data);
            $("#listrekening").html(aa.grid);
            $("#rows").val(aa.rows);
            $("#page").val(aa.page);
            $("#total_data").html(": " + aa.count);
            $("#total_halaman").html(": " + aa.total_halaman);
        });
    }

    function bukamodalRekening() {
        calldataGridRekening();
        $('#modalRekening').modal('show');
    }

    function pilihRekening(a) {
        $.post('<?= $this->url() ?>/pilihRekening', {
            s_idkorek: a
        }, function(data) {
            var aa = JSON.parse(data);
            $('#t_idkorek').val(aa.t_idkorek);
            $('#t_korek').val(aa.t_korek);
            $('#t_namakorek').val(aa.t_namakorek);
            $('#t_tarifpajak').val(aa.t_tarifpajak);
            $('#t_berdasarmasa').val(aa.t_berdasarmasa);
            $('#modalRekening').modal('hide');
        });
    }

    function hitungpajak(o) {
        if (typeof o != undefined) {
            var id = $(o).data('id');
            var nilai = $(o).val();
            var tarif = $(o).data('tarif') / 100;
            var subtotal = unformatCurrency(nilai) * tarif;
            $('#subtotalpajak' + id).val(subtotal);
            document.getElementById('subtotalpajak' + id).value = formatCurrency(document.getElementById('subtotalpajak' + id).value);
            hitungtotalpajak();
        }
    }

    function hitungtotalpajak() {
        $('#t_jmlhpajak').val('');
        var totalpajak = 0;
        $('.subtotalpajak').each(function(i) {
            var s = unformatCurrency($(this).val());
            totalpajak += Number(s);
        });
        $('#t_jmlhpajak').val(totalpajak);
        document.getElementById('t_jmlhpajak').value = formatCurrency(document.getElementById('t_jmlhpajak').value);
    }
    $(function() {
        CariPendataanByObjek();
        //Add and Del Buttons functionality of Data Lampiran 
        $('#tableLampiran input[type=text].numeric').attr('onkeypress', 'return numbersonly(this,event);');
        $('.btnAdd_row_a').each(function() {
            $(this).on('click', function() {
                var row = $(this).parent().parent();
                $(row).clone(true).insertAfter(row);
                $(row).next().find('input').each(function() {
                    $(this).val('');
                });
                countRows('.row_a');
                sumRows('row_a');
                grandtotal();
            });

        });
        $('.btnDel_row_a').each(function() {
            $(this).on('click', function() {
                var row = $(this).parent().parent();
                if ($('.row_a').length > 1) {
                    $(row).remove();
                    countRows('.row_a');
                    sumRows('row_a');
                    grandtotal();

                }
            });
        });
        $('.btnAdd_row_b').each(function() {
            $(this).on('click', function() {
                var row = $(this).parent().parent();
                $(row).clone(true).insertAfter(row);
                $(row).next().find('input').each(function() {
                    $(this).val('');
                });
                countRows('.row_b');
                sumRows('row_b');
                grandtotal();
            });

        });
        $('.btnDel_row_b').each(function() {
            $(this).on('click', function() {
                var row = $(this).parent().parent();
                if ($('.row_b').length > 1) {
                    $(row).remove();
                    countRows('.row_b');
                    sumRows('row_b');
                    grandtotal();
                }
            });
        });

        //Calculation of Data Lampiran Columns
        // Col 7 = 4x5x6
        $('.row_a_calc4').keyup(function() {
            var calc5 = $(this).closest('tr').find('input.row_a_calc5').val();
            var calc6 = $(this).closest('tr').find('input.row_a_calc6').val();
            var calc7 = $(this).val() * calc5 * calc6;
            //calc7 col
            $(this).closest('tr').find('input.row_a_calc7').val(calc7).change();

        });
        $('.row_a_calc5').keyup(function() {
            var calc4 = $(this).closest('tr').find('input.row_a_calc4').val();
            var calc6 = $(this).closest('tr').find('input.row_a_calc6').val();
            var calc7 = $(this).val() * calc4 * calc6;
            //calc7 col
            $(this).closest('tr').find('input.row_a_calc7').val(calc7).change();
        });
        $('.row_a_calc6').keyup(function() {
            var calc4 = $(this).closest('tr').find('input.row_a_calc4').val();
            var calc5 = $(this).closest('tr').find('input.row_a_calc5').val();
            var calc7 = $(this).val() * calc4 * calc5;
            //calc7 col
            $(this).closest('tr').find('input.row_a_calc7').val(calc7).change();
        });
        $('.row_a_calc8').keyup(function() {
            var calc7 = $(this).closest('tr').find('input.row_a_calc7').val();
            var calc9 = Number($(this).val()) + Number(calc7);
            $(this).closest('tr').find('input.row_a_calc9').val(calc9).change();
        });
        $('.row_a_calc7').change(function() {
            var calc8 = $(this).closest('tr').find('input.row_a_calc8').val();
            var calc9 = Number($(this).val()) + Number(calc8);
            $(this).closest('tr').find('input.row_a_calc9').val(calc9).change();
        });

        $('.row_a_calc9').change(function() {
            var calc10 = $(this).closest('tr').find('input.row_a_calc10').val();
            var calc11 = $(this).val() * calc10;
            $(this).closest('tr').find('input.row_a_calc11').val(calc11).change();
        });

        $('.row_a_calc10').keyup(function() {
            var calc9 = $(this).closest('tr').find('input.row_a_calc9').val();
            var calc11 = $(this).val() * calc9;
            $(this).closest('tr').find('input.row_a_calc11').val(calc11).change();
        });
        $('.row_a_calc11').change(function() {
            sumRows('row_a');
            grandtotal();
        });
        $('.row_b_calc4').keyup(function() {
            var calc5 = $(this).closest('tr').find('input.row_b_calc5').val();
            var calc6 = $(this).closest('tr').find('input.row_b_calc6').val();
            var calc7 = $(this).val() * calc5 * calc6;
            //calc7 col
            $(this).closest('tr').find('input.row_b_calc7').val(calc7).change();

        });
        $('.row_b_calc5').keyup(function() {
            var calc4 = $(this).closest('tr').find('input.row_b_calc4').val();
            var calc6 = $(this).closest('tr').find('input.row_b_calc6').val();
            var calc7 = $(this).val() * calc4 * calc6;
            //calc7 col
            $(this).closest('tr').find('input.row_b_calc7').val(calc7).change();
        });
        $('.row_b_calc6').keyup(function() {
            var calc4 = $(this).closest('tr').find('input.row_b_calc4').val();
            var calc5 = $(this).closest('tr').find('input.row_b_calc5').val();
            var calc7 = $(this).val() * calc4 * calc5;
            //calc7 col
            $(this).closest('tr').find('input.row_b_calc7').val(calc7).change();
        });
        $('.row_b_calc8').keyup(function() {
            var calc7 = $(this).closest('tr').find('input.row_b_calc7').val();
            var calc9 = Number($(this).val()) + Number(calc7);
            $(this).closest('tr').find('input.row_b_calc9').val(calc9).change();
        });
        $('.row_b_calc7').change(function() {
            var calc8 = $(this).closest('tr').find('input.row_b_calc8').val();
            var calc9 = Number($(this).val()) + Number(calc8);
            $(this).closest('tr').find('input.row_b_calc9').val(calc9).change();
        });

        $('.row_b_calc9').change(function() {
            var calc10 = $(this).closest('tr').find('input.row_b_calc10').val();
            var calc11 = $(this).val() * calc10;
            $(this).closest('tr').find('input.row_b_calc11').val(calc11).change();
        });

        $('.row_b_calc10').keyup(function() {
            var calc9 = $(this).closest('tr').find('input.row_b_calc9').val();
            var calc11 = $(this).val() * calc9;
            $(this).closest('tr').find('input.row_b_calc11').val(calc11).change();
        });
        $('.row_b_calc11').change(function() {
            sumRows('row_b');
            grandtotal();
        });

    });

    function sumRows(row) {
        var row_total = 0;
        $('.' + row + '_calc11').each(function() {
            row_total += Number($(this).val());
        });
        $('.' + row + '_total').val(row_total).change();
    }

    function grandtotal() {
        var grandtotal = Number($('.row_a_total').val()) + Number($('.row_b_total').val());
        $('#grandtotallampiran').val(grandtotal);
    }

    function countRows(className) {
        var num = 1;
        $(className).each(function() {
            $(this).children('td:first').text(num);
            num++;
        });
    }

    function CariPendataanByObjek() {
        $.post('<?= $this->url() ?>/CariPendataanByObjek', {
            idobjek: $("#t_idobjek").val(),
            periodepajak: $("#t_periodepajak").val()
        }, function(data) {
            var aa = JSON.parse(data);
            $("#datatransaksi").html(aa.datatransaksi);
        });
    }

    function pilihskpdjabatan(a) {
        $.post('<?= $this->url() ?>/pilihskpdjabatan', {
            parameter: a
        }, function(data) {
            var aa = JSON.parse(data);
            $("#t_tglpendataan").val(aa.t_tglpendataan);
            $("#t_masaawal").val(aa.t_masaawal);
            $("#t_masaakhir").val(aa.t_masaakhir);
            $("#t_tarifkenaikan").val(aa.t_tarifkenaikan);
        });
        document.getElementById("kenaikan").style.display = "block";
        setTimeout(function() {
            hitungpajak();
        }, 1000);
    }

    function nonskpdjabatan() {
        document.getElementById("kenaikan").style.display = "none";
        $("#t_tarifkenaikan").val(0);
        hitungpajak();
    }
</script>
<div class="modal fade" id="modalCetakSuratTeguran" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><b>CETAK SuratTeguran</b></h4>
            </div>
            <div class='modal-body'>
                <div class='example-box-wrapper'>
                    <div class='example-box-wrapper'>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Jenis Pajak
                            </label>
                            <div class="col-md-4">
                                <input type="hidden" id="idjenispajak">
                                <input type="hidden" id="idobjekwp">
                                <input type="text" class="form-control" id="jenispajak" readonly="">
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Nama WP
                            </label>
                            <div class="col-md-4">
                                <input type="text" class="form-control" id="namawp" readonly="">
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Masa Pajak
                            </label>
                            <div class="col-sm-4">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <input type="text" class="form-control" id="masaawal" readonly="">
                                </div>
                            </div>
                            <label class="col-sm-1 control-label">S/D</label>
                            <div class="col-sm-4">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <input type="text" class="form-control" id="masaakhir" readonly="">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Alamat WP
                            </label>
                            <div class="col-md-9">
                                <textarea class="form-control" id="alamatwp">

                                </textarea>
                            </div>
                        </div>
                        <div class="col-md-12 form-horizontal">
                            <label class="col-md-3 control-label">
                                Penandatangan
                            </label>
                            <div class="col-md-9">
                                <select id="ttd0" class="form-control">
                                    <?php foreach ($ar_ttd0 as $row) { ?>
                                        <option value="<?= $row['s_idpej'] ?>"><?= $row['s_namapej'] . " || " . $row['s_jabatanpej'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class='modal-footer'>
                <div class='col-sm-12'>
                    <a href="#" class="btn btn-sm btn-danger" title="" onclick="cetaksuratteguran()"><i class="glyph-icon icon-file-pdf-o"></i> PDF</a>
                    <button class='btn btn-primary btn-sm' onclick='tutupCetakSuratTeguran()'><i class='glyph-icon icon-close'></i> Tutup</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function bukaCetakSuratTeguran(a, b) {
        $.post('<?= $this->url() ?>/dataSuratTeguran', {
            parameter: a,
            idobjekwp: b
        }, function(data) {
            var aa = JSON.parse(data);
            $("#idobjekwp").val(aa.idobjekwp);
            $("#namawp").val(aa.namawp);
            $("#alamatwp").val(aa.alamatwp);
            $("#jenispajak").val(aa.jenispajak);
            $("#idjenispajak").val(aa.idjenispajak);
            $("#masaawal").val(aa.t_masaawal);
            $("#masaakhir").val(aa.t_masaakhir);
        });
        $('#modalCetakSuratTeguran').modal('show');
    }

    function tutupCetakSuratTeguran() {
        $('#modalCetakSuratTeguran').modal('hide');
    }

    function cetaksuratteguran() {
        window.open('<?= $this->url() ?>/cetaksuratteguran?idobjekwp=' + $("#idobjekwp").val() + "&ttd0=" + $("#ttd0").val() + "&masaawal=" + $("#masaawal").val() + "&masaakhir=" + $("#masaakhir").val());
    }
</script>