<?php
$form = $this->form;
$form->setAttribute('action', $this->url() . '/form_pagereklame');
$form->setAttribute("id", "demo-form");
$form->setAttribute("class", "form-horizontal pad15L pad15R pad15T");
$form->setAttribute("data-parsley-validate", "data-parsley-validate");
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();
?>

<style type="text/css">
    blink,
    .blink {
        -webkit-animation: blink 1s step-end infinite;
        -moz-animation: blink 1s step-end infinite;
        -o-animation: blink 1s step-end infinite;
        animation: blink 1s step-end infinite;
    }

    @-webkit-keyframes blink {
        67% {
            opacity: 0
        }
    }

    @-moz-keyframes blink {
        67% {
            opacity: 0
        }
    }

    @-o-keyframes blink {
        67% {
            opacity: 0
        }
    }

    @keyframes blink {
        67% {
            opacity: 0
        }
    }
</style>
<div id="page-content-wrapper" style="font-size:12px">
    <div id="page-content" style="background-color: #DFF0D8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <i class="glyph-icon icon-pencil"></i>
                    Pendataan <?= $datapendaftaran['s_namajenis'] ?><b class="blink" style="font-size: 12px; color: red"><?= $message ?></b>
                </h4>
            </div>
            <div class="panel-body">
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-12 center-div">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="text-align:center; background:black; border-radius: 25px; color: orange; padding: 5px 15px 5px 15px; font-size: 16px; font-weight:bolder">NPWPD : <?= $datapendaftaran['t_npwpd'] ?> / NIOP : <?= $datapendaftaran['t_nop'] ?></span>
                        </div>
                    </div>
                    <?= $this->form()->openTag($form) ?>
                    <div class="col-md-6">

                        <div class="content-box">
                            <h3 class="content-box-header content-box-header-alt bg-success">
                                <span class="icon-separator">
                                    <i class="glyph-icon icon-database"></i>
                                </span>
                                <span class="header-wrapper">
                                    Data WP
                                </span>
                            </h3>
                            <div class="content-box-wrapper">
                                <div class='row'>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">NIK</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_nik'] ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">Nama</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_nama'] ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">Alamat</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_alamat_lengkap'] ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="content-box">
                            <h3 class="content-box-header content-box-header-alt bg-success">
                                <span class="icon-separator">
                                    <i class="glyph-icon icon-database"></i>
                                </span>
                                <span class="header-wrapper">
                                    Data OP
                                </span>
                            </h3>
                            <div class="content-box-wrapper">
                                <div class='row'>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">NIOP</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_nop'] ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">Nama</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_namaobjek'] ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">Alamat</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_alamatobjek'] ?>
                                            ,RT. <?= $datapendaftaran['t_rtobjek'] ?>
                                            ,RW. <?= $datapendaftaran['t_rwobjek'] ?>
                                            ,Desa/Kel. <?= $datapendaftaran['s_namakelobjek'] ?>
                                            ,Kec. <?= $datapendaftaran['s_namakecobjek'] ?>
                                            ,Kab. <?= $datapendaftaran['t_kabupatenobjek'] ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="alert alert-info">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Histori Pajak</b></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div id="datatransaksi"></div>
                        </div>
                    </div>
                    <div class="row pad10B">
                        <div class="col-sm-12">
                            <div class="alert alert-warning">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Data Pendataan</b></h4>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Periode Pajak</label>
                            <div class="col-sm-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_periodepajak")) ?>
                                    <input type="hidden" name="t_jenisobjekpajak" value="<?= $datapendaftaran['t_jenisobjek'] ?>">
                                    <?= $this->formHidden($form->get("t_idtransaksi")) ?>
                                    <?= $this->formHidden($form->get("t_iddetailreklame")) ?>
                                    <?= $this->formHidden($form->get("t_idobjek")) ?>
                                    <?= $this->formHidden($form->get("t_jenispajak")) ?>
                                    <?= $this->formHidden($form->get("t_nourut")) ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Tanggal Pendataan</label>
                            <div class="col-sm-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_tglpendataan")) ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Tgl. Penetapan</label>
                            <div class="col-sm-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_tglpenetapan")) ?>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Tipe Waktu</label>
                            <div class="col-sm-6">
                                <div class="input-prepend input-group">
                                    <?= $this->formSelect($form->get("t_tipewaktu")) ?>
                                    <?= $this->formHidden($form->get("t_jangkawaktu")) ?>

                                </div>
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Masa Pajak</label>
                            <div class="col-sm-6">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_masaawal")) ?>
                                    <span class="input-group-addon" style="background-color: #EEEEEE"><b>s/d</b></span>
                                    <?= $this->formText($form->get("t_masaakhir")) ?>
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Kode Rekening</label>
                            <div class="col-sm-2">
                                <?= $this->formHidden($form->get("t_idkorek")) ?>
                                <?= $this->formText($form->get("t_korek")) ?>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Nama Rekening</label>
                            <div class="col-sm-6">
                                <?= $this->formText($form->get("t_namakorek")) ?>
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Naskah</label>
                            <div class="col-sm-6">
                                <?= $this->formTextarea($form->get("t_naskah")) ?>
                            </div>
                        </div>
                        <div class="col-sm-12" id="divLokasiReklame">
                            <label class="col-sm-2 control-label">Nilai Srategis</label>
                            <div class="col-sm-2">
                                <?= $this->formSelect($form->get("t_kelasjalan")) ?>
                            </div>
                            <div class="col-sm-1">
                                <div class="box">
                                    <div class="box-header with-border">
                                        <span class="btn btn-sm btn-info" id="btnInfoKawasan" al><i class="glyph-icon icon-file"></i> Klasifikasi</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-12" id="divrekomendasi">

                        </div>

                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Detail Lokasi</label>
                            <div class="col-sm-6">
                                <?= $this->formTextarea($form->get("t_lokasi")) ?>
                            </div>
                        </div>


                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Jumlah</label>
                            <div class="col-sm-1">
                                <?= $this->formText($form->get("t_jumlah")) ?>
                            </div>
                            <label class="col-sm-2 control-label">Kategori</label>
                            <div class="col-sm-2">
                                <?= $this->formSelect($form->get("t_jenisreklameusaha")) ?>
                            </div>
                        </div>
                    </div>

                    <div align="right" style="margin-bottom:5px;">
                        <hr>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="box box-danger">

                                <div class="box-body">
                                    <?php
                                    $idl = 1;
                                    foreach (@$datadetail as $row) {
                                        echo '<div style="border-bottom: 1px solid red; margin-bottom: 10px;" id="detailnode' . $idl . '">
                                        <div class="col-sm-12">
                                                <label class="col-sm-2 control-label">Jenis Reklame</label>
                                                <div class="col-sm-6">
                                                    <select onchange="ukuranmedia(' . $idl . ')" name="t_jenisreklame[]" id="t_jenisreklame' . $idl . '" class="form-control" required="true">
                                                        <option value="">Silahkan Pilih</option>';
                                        foreach ($ar_jenisreklame as $vRow) {
                                            $selected = ($vRow['s_idreklamejenis'] == $row['t_jenisreklame']) ? 'selected' : '';
                                            echo '<option ' . $selected . ' value="' . $vRow['s_idreklamejenis'] . '">' . $vRow['s_namareklamejenis'] . '</option>';
                                        }
                                        echo '</select>
                                                </div>
                                            </div>';
                                        if ($row['t_jenisreklame'] == 1 || $row['t_jenisreklame'] == 2) {
                                            echo '
                                            <div class="col-sm-12" style="" id="divtinggi' . $idl . '">
                                            <label class="col-sm-2 control-label">Tinggi (m)</label>
                                            <div class="col-sm-1">
                                            <input type="text" onchange="hitungpajakreklame(' . $idl . ')" onkeypress="return hanyaAngka(event)" name="t_tinggi[]" id="t_tinggi' . $idl . '" class="form-control text-right" required="true" value="' . $row['t_tinggi'] . '">
                                            </div>
                                            </div>';
                                        } else if (
                                            $row['t_jenisrejkame']  == "11" ||
                                            $row['t_jenisrejkame']  == "10" ||
                                            $row['t_jenisrejkame']  == "13"
                                        ) {
                                            echo '
                                            <div class="col-sm-12" style="display:none;" id="divfolio' . $idl . '">
                                            <label class="col-sm-2 control-label">Folio (lembar)</label>
                                            <div class="col-sm-1">
                                            <input type="text" onkeyup="hitungpajakreklame(' . $idl . ')" onkeypress="return hanyaAngka(event)" name="t_folio[]" id="t_folio' . $idl . '" class="form-control text-right" required="true" value="0">
                                            </div>
                                            </div>';
                                        } else {
                                            echo '
                                            <div class="col-sm-12" style="" id="divluas' . $idl . '">
                                            <label class="col-sm-2 control-label">Panjang (m)</label>
                                            <div class="col-sm-1">
                                            <input type="text" onchange="hitungpajakreklame(' . $idl . ')" onkeypress="return hanyaAngka(event)" name="t_panjang[]" id="t_panjang' . $idl . '" class="form-control text-right" required="true" value="' . $row['t_panjang'] . '">
                                            </div>
                                            <label class="col-sm-1 control-label">Lebar (m)</label>
                                            <div class="col-sm-1">
                                            <input type="text" onchange="hitungpajakreklame(' . $idl . ')" onkeypress="return hanyaAngka(event)" name="t_lebar[]" id="t_lebar' . $idl . '" class="form-control text-right" required="true" value="' . $row['t_lebar'] . '">
                                            </div>
                                            <label class="col-sm-1 control-label">Sisi</label>
                                            <div class="col-sm-1">
                                            <input type="text" onchange="hitungpajakreklame(' . $idl . ')" onkeypress="return hanyaAngka(event)" name="t_sisi[]" id="t_sisi' . $idl . '" class="form-control text-right" required="true" value="' . $row['t_sudutpandang'] . '">
                                            </div>
                                            </div>';
                                        }
                                        echo '
                                        <div class="col-sm-12" style="display:none;" id="divluas' . $idl . '">
                                        <label class="col-sm-2 control-label">Panjang (m)</label>
                                        <div class="col-sm-1">
                                        <input type="text" onchange="hitungpajakreklame(' . $idl . ')" onkeypress="return hanyaAngka(event)" name="t_panjang[]" id="t_panjang' . $idl . '" class="form-control text-right" required="true" value="0">
                                        </div>
                                        <label class="col-sm-1 control-label">Lebar (m)</label>
                                        <div class="col-sm-1">
                                        <input type="text" onchange="hitungpajakreklame(' . $idl . ')" onkeypress="return hanyaAngka(event)" name="t_lebar[]" id="t_lebar' . $idl . '" class="form-control text-right" required="true" value="0">
                                        </div>
                                        <label class="col-sm-1 control-label">Sisi</label>
                                        <div class="col-sm-1">
                                        <input type="text" onchange="hitungpajakreklame(' . $idl . ')" onkeypress="return hanyaAngka(event)" name="t_sisi[]" id="t_sisi' . $idl . '" class="form-control text-right" required="true" value="0">
                                        </div>
                                        </div>

                                        <div class="col-sm-12" style="display:none;" id="divtinggi' . $idl . '">
                                        <label class="col-sm-2 control-label">Tinggi (m)</label>
                                        <div class="col-sm-1">
                                        <input type="text" onchange="hitungpajakreklame(' . $idl . ')" onkeypress="return hanyaAngka(event)" name="t_tinggi[]" id="t_tinggi' . $idl . '" class="form-control text-right" required="true" value="0">
                                        </div>
                                        </div>

                                        <div class="col-sm-12" style="display:none;" id="divfolio' . $idl . '">
                                        <label class="col-sm-2 control-label">Folio (lembar)</label>
                                        <div class="col-sm-1">
                                        <input type="text" onkeyup="hitungpajakreklame(' . $idl . ')" onkeypress="return hanyaAngka(event)" name="t_folio[]" id="t_folio' . $idl . '" class="form-control text-right" required="true" value="0">
                                        </div>
                                        </div>

                                        <div class="col-sm-12">
                                        <label class="col-sm-2 control-label">Tarif Pajak</label>
                                        <div class="col-sm-6">
                                        <input type="text" name="t_nsr[]" id="t_nsr' . $idl . '" class="form-control text-right" readonly="true" required="true" value="' . $row['t_nsr'] . '">
                                        </div>
                                        </div>

                                        <div class="col-sm-12">
                                        <label class="col-sm-2 control-label">Parameter</label>
                                        <div class="col-sm-6">
                                        <input type="text" name="t_param[]" id="t_param' . $idl . '" class="form-control text-right" readonly="true" required="true" value="' . $row['t_parameter'] . '">
                                        </div>
                                        </div>

                                        <div class="col-sm-12">
                                        <label class="col-sm-2 control-label">Jumlah</label>
                                        <div class="col-sm-6">
                                        <input type="text" name="t_jmlhpajaksub[]" id="t_jmlhpajaksub' . $idl . '" class="form-control text-right" readonly="true" required="true" value="' . $row['t_jmlhpajakasli'] . '">
                                        </div>
                                        <div class="col-sm-3">
                                        <span class="btn btn-xs btn-warning" onclick="hitungpajakreklame(' . $idl . ')"><span class="glyphicon glyphicon-refresh"></span>
                                        </div>
                                        </div>';



                                        echo '<div align="right" style="margin-bottom:5px;">
                                        <span class="btn btn-xs btn-danger" onclick="removetr(' . $idl . ')"><span class="glyph-icon icon-trash"></span> HAPUS</span>
                                        </div>
                                        </div>';
                                        $idl++;
                                    } ?>
                                    <input type="hidden" id="idl" value="<?= $idl++ ?>">
                                    <div id="add_Detail"></div>
                                </div>
                                <div align="right" class="box-header with-border">
                                    <span class="btn btn-sm btn-success" id="tambahDetail" al><i class="glyph-icon icon-plus-square-o"></i> TAMBAH JENIS REKLAME</span>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div align="right" style="margin-bottom:5px;">
                        <hr>
                    </div>

                    <div class="col-sm-12">
                        <label class="col-sm-2 control-label">Total Pajak</label>
                        <div class="col-sm-4">
                            <?= $this->formText($form->get("t_jmlhpajak")) ?>
                        </div>
                        <div class="col-sm-1">
                            <button type="button" class="btn btn-sm btn-success" onclick="hitungpajakreklame()">
                                <span class="glyph-icon icon-calculator"></span> Hitung
                            </button>
                        </div>
                    </div>

                    <div class="bg-default" id="tombolsimpan">
                        <?= $this->formInput($form->get('Pendataansubmit')) ?>
                    </div>
                    <?= $this->form()->closeTag($form) ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalKawasan" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-info">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><b>Klasifikasi Nilai Strategis Jalan</b></h4>
            </div>
            <div class=' modal-body'>
                <div>
                    <table class="table table-condensed table-bordered cf" style="font-size: 11px; color: black">
                        <thead class="cf">

                            <tr>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    Utama
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    A
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    B
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    C
                                </th>
                            </tr>

                        </thead>
                        <tbody>
                            <tr>
                                <td>- Jl. Tinggang Menteng (Kecamatan Kahayan Hilir)<br>
                                    - Jl. Trans Kalimantan Km. 10 (Kecamatan Kahayan Hilir)<br>

                                </td>
                                <td>
                                    - Jln. Pemda<br>
                                    - Jln. Pananjung Tarung<br>


                                </td>
                                <td>
                                    - Jln. Darung Bawan<br>
                                    - Jln. Masyuni Layar<br>
                                    - Jln. Rey 2<br>
                                    - Jln. Hasanudin;<br>
                                    - Jln. Tajakan Antang<br>
                                    - Kelurahan Kalawa<br>

                                </td>
                                <td>- Diluar Kecamatan Kahayan Hilir</td>

                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        getformrekomendasi()

        $("#tambahDetail").click(function() {
            if ($("#t_korek").val() == '') {
                alert('Silahkan Pilih Kode Rekening Terlebih dahulu!');


            } else if ($("#t_jenisreklameusaha").val() == '') {
                alert('Silahkan Pilih Kategori Terlebih dahulu!');
            } else if ($("#t_kelasjalan").val() == '') {
                alert('Silahkan Pilih Nilai Strategis!');
            } else if ($("#t_tipewaktu").val() == '') {
                alert('Silahkan Pilih Tipe Waktu!');
            } else {
                var idl = document.getElementById("idl").value;
                comboJenisReklame(idl);
                $("#add_Detail").append(

                    '<div style="border-bottom: 1px solid red; margin-bottom: 10px;" id="detailnode' + idl + '">' +
                    '<div class="col-sm-12">' +
                    '<label class="col-sm-2 control-label">Jenis Reklame</label>' +
                    '<div class="col-sm-6">' +
                    '<select onchange="ukuranmedia(' + idl + ')" name="t_jenisreklame[]" id="t_jenisreklame' + idl + '" class="form-control" required="true">' +
                    '<option value="">Silahkan Pilih</option>' +
                    '</select>' +
                    '</div>' +
                    '</div>' +


                    '<div class="col-sm-12" style="display:none;" id="divluas' + idl + '">' +
                    '<label class="col-sm-2 control-label">Panjang (m)</label>' +
                    '<div class="col-sm-1">' +
                    '<input type="text" onchange="hitungpajakreklame(' + idl + ')" name="t_panjang[]" id="t_panjang' + idl + '" class="form-control text-right" required="true" value="0">' +
                    '</div>' +
                    '<label class="col-sm-1 control-label">Lebar (m)</label>' +
                    '<div class="col-sm-1">' +
                    '<input type="text" onchange="hitungpajakreklame(' + idl + ')" name="t_lebar[]" id="t_lebar' + idl + '" class="form-control text-right" required="true" value="0">' +
                    '</div>' +
                    '<label class="col-sm-1 control-label">Sisi</label>' +
                    '<div class="col-sm-1">' +
                    '<input type="text" onchange="hitungpajakreklame(' + idl + ')" name="t_sisi[]" id="t_sisi' + idl + '" class="form-control text-right" required="true" value="0">' +
                    '</div>' +
                    '</div>' +

                    '<div class="col-sm-12" style="display:none;" id="divtinggi' + idl + '">' +
                    '<label class="col-sm-2 control-label">Tinggi (m)</label>' +
                    '<div class="col-sm-1">' +
                    '<input type="text" onchange="hitungpajakreklame(' + idl + ')" name="t_tinggi[]" id="t_tinggi' + idl + '" class="form-control text-right" required="true" value="0">' +
                    '</div>' +
                    '</div>' +

                    '<div class="col-sm-12" style="display:none;" id="divfolio' + idl + '">' +
                    '<label class="col-sm-2 control-label">Folio (lembar)</label>' +
                    '<div class="col-sm-1">' +
                    '<input type="text" onkeyup="hitungpajakreklame(' + idl + ')" name="t_folio[]" id="t_folio' + idl + '" class="form-control text-right" required="true" value="0">' +
                    '</div>' +
                    '</div>' +


                    '<div class="col-sm-12">' +
                    '<label class="col-sm-2 control-label">Tarif Pajak</label>' +
                    '<div class="col-sm-6">' +
                    '<input type="text" name="t_nsr[]" id="t_nsr' + idl + '" class="form-control text-right" readonly="true" required="true">' +
                    '</div>' +
                    '</div>' +

                    '<div class="col-sm-12">' +
                    '<label class="col-sm-2 control-label">Parameter</label>' +
                    '<div class="col-sm-6">' +
                    '<input type="text" name="t_param[]" id="t_param' + idl + '" class="form-control text-right" readonly="true" required="true">' +
                    '</div>' +
                    '</div>' +

                    '<div class="col-sm-12">' +
                    '<label class="col-sm-2 control-label">Jumlah</label>' +
                    '<div class="col-sm-6">' +
                    '<input type="text" onchange="hitungTotalJumlahPajakReklame()" name="t_jmlhpajaksub[]" id="t_jmlhpajaksub' + idl + '" class="form-control text-right" readonly="true" required="true">' +
                    '</div>' +
                    '<div class="col-sm-3">' +
                    '<span class="btn btn-xs btn-warning" onclick="hitungpajakreklame(' + idl + ')"><span class="glyphicon glyphicon-refresh"></span>' +
                    '</div>' +
                    '</div>' +

                    '<div class="col-sm-12" style="display:none;" id="divrekomendasi' + idl + '">' +
                    '<label class="col-sm-2 control-label">Surat Rekomendasi</label>' +
                    '<div class="col-sm-6">' +
                    '<input type="file" id="t_rekomendasi[]" name="t_rekomendasi[]" accept=".jpg,.jpeg,.png,.pdf"  onchange="ceksize(this,' + idl + ')">' +
                    '</div>' +
                    '</div>' +

                    '<div align="right" style="margin-bottom:5px;">' +
                    '<span class="btn btn-xs btn-danger" onclick="removetr(' + idl + ')"><span class="glyph-icon icon-trash"></span> HAPUS</span>' +
                    '</div>' +
                    '</div>'
                );
                idl = (idl - 1) + 2;
                document.getElementById("idl").value = idl;




            }

        });
    });

    function getformrekomendasi() {
        $.post('<?= $this->url() ?>/getformrekomendasi', {
            t_kelasjalan: $("#t_kelasjalan").val(),
        }).then(function(data) {
            var aa = JSON.parse(data);
            $("#divrekomendasi").html(aa.form);
        });
    }

    $('#btnInfoKawasan').click(function() {
        $('#modalKawasan').modal('show');
    })

    function ukuranmedia(idl) {
        if ($("#t_jenisreklame" + idl).val() == "1" ||
            $("#t_jenisreklame" + idl).val() == "2") {
            $("#divtinggi" + idl).show();
            $("#divluas" + idl).hide();
            $("#divfolio" + idl).hide();
        } else if ($("#t_jenisreklame" + idl).val() == "11" ||
            $("#t_jenisreklame" + idl).val() == "10" ||
            $("#t_jenisreklame" + idl).val() == "13") {
            $("#divfolio" + idl).show();
            $("#divluas" + idl).hide();
            $("#divtinggi" + idl).hide();
        } else {
            $("#divluas" + idl).show();
            $("#divtinggi" + idl).hide();
            $("#divfolio" + idl).hide();

        }
        caritarifreklame(idl);
    }

    function hitungjangkawaktu() {
        $.post('<?= $this->url() ?>/hitungjangkawaktu', {
            t_masaawal: $("#t_masaawal").val(),
            t_masaakhir: $("#t_masaakhir").val(),
            t_tipewaktu: $("#t_tipewaktu").val()
        }).then(function(data) {
            var aa = JSON.parse(data);
            $("#t_jangkawaktu").val(aa.t_jangkawaktu);
        });

    }

    function caritarifreklame(a) {
        $.post('<?= $this->url() ?>/caritarifreklame', {
                t_jenisreklame: $('#t_jenisreklame' + a).val(),
                t_jenisreklameusaha: $('#t_jenisreklameusaha').val(),
                t_jangkawaktu: $('#t_jangkawaktu').val(),
                t_kelasjalan: $('#t_kelasjalan').val()
            },
            function(data) {
                var aa = JSON.parse(data);
                $('#t_nsr' + a).val(aa.s_nsr);



            });
    }

    function hitungpajakreklame(a) {
        $.post('<?= $this->url() ?>/hitungpajakreklame', {

            t_jenisreklame: $("#t_jenisreklame" + a).val(),
            t_panjang: $("#t_panjang" + a).val(),
            t_lebar: $("#t_lebar" + a).val(),
            t_tinggi: $("#t_tinggi" + a).val(),
            t_sisi: $("#t_sisi" + a).val(),
            t_jumlah: $("#t_jumlah").val(),
            t_nsr: $("#t_nsr" + a).val(),
            t_jangkawaktu: $("#t_jangkawaktu").val(),
            t_tipewaktu: $("#t_tipewaktu").val(),
        }, function(data) {
            var aa = JSON.parse(data);
            console.log(aa);
            $('#t_jmlhpajaksub' + a).val(aa.t_jmlhpajaksub);
            $('#t_param' + a).val(aa.t_param);

            hitungTotalJumlahPajakReklame();
        });

    }


    function hitungTotalJumlahPajakReklame() {
        let total = 0;
        let maxidl = $('#idl').val();
        for (let index = 1; index < maxidl; index++) {
            var strnum = $('#t_jmlhpajaksub' + index).val();
            var Re = new RegExp("\\.", "g");
            totalpernode = strnum.replace(Re, "");

            total += Number(totalpernode);
        }
        console.log(total);
        $('#t_jmlhpajak').val(format(String(total)));
    }

    function format(str) {
        var length = 3,
            separator = ".",
            count = 0,
            result = str.split('').reduceRight((a, c) => {
                if (count === length) {
                    a.push(separator);
                    count = 1;
                } else
                    count++;
                a.push(c);
                return a;
            }, []).reverse().join('');
        return result;
    }

    function removetr(a) {
        $("#detailnode" + a).remove();
    }

    function clearform() {
        location.reload();
        //    $("#t_idkorek").val('');
        //    $("#t_korek").val('');
        //    $("#t_namakorek").val('');

    }

    function comboJenisReklame(a) {
        $.post('<?= $this->url() ?>/comboJenisReklame', {
            t_idkorek: $("#t_idkorek").val()
        }, function(data) {
            var aa = JSON.parse(data);
            $('#t_jenisreklame' + a).html(aa.res);
        });
    }


    $('#t_tglpendataan').datepicker({
        format: 'dd-mm-yyyy'
    });
    $('#t_masaawal').datepicker({
        format: 'dd-mm-yyyy'
    });
    $('#t_masaakhir').datepicker({
        format: 'dd-mm-yyyy'
    });
    $('#t_tglpenetapan').datepicker({
        format: 'dd-mm-yyyy'
    });
    $('#t_periodepajak').datepicker({
        format: 'yyyy',
        viewMode: "years",
        minViewMode: "years"
    });


    $(function() {
        CariPendataanReklameByObjek();
        // populateJangkaWaktuDropdown();
        // hitungpajakreklame();
        cariukuranmedia();

        $('#t_panjang').change(function() {
            $.post('<?= $this->url() ?>/hitungluasreklame', {
                t_panjang: $('#t_panjang').val(),
                t_lebar: $('#t_lebar').val()
            }).then(function(data) {
                var aa = JSON.parse(data);
                $("#t_luas").val(aa.t_luas);
                hitungpajakreklame();
            });
        });

        $('#t_panjang').blur(function() {
            $.post('<?= $this->url() ?>/hitungluasreklame', {
                t_panjang: $('#t_panjang').val(),
                t_lebar: $('#t_lebar').val()
            }).then(function(data) {
                var aa = JSON.parse(data);
                $("#t_luas").val(aa.t_luas);
            });
        });

        $('#t_lebar').change(function() {
            $.post('<?= $this->url() ?>/hitungluasreklame', {
                t_panjang: $('#t_panjang').val(),
                t_lebar: $('#t_lebar').val()
            }).then(function(data) {
                var aa = JSON.parse(data);
                $("#t_luas").val(aa.t_luas);
            });
        });

        $('#t_lebar').blur(function() {
            $.post('<?= $this->url() ?>/hitungluasreklame', {
                t_panjang: $('#t_panjang').val(),
                t_lebar: $('#t_lebar').val()
            }).then(function(data) {
                var aa = JSON.parse(data);
                $("#t_luas").val(aa.t_luas);
            });
        });

        $('#t_jenisreklame').change(function() {
            $.post('<?= $this->url() ?>/hitungluasreklame', {
                t_panjang: $('#t_panjang').val(),
                t_lebar: $('#t_lebar').val()
            }).then(function(data) {
                var aa = JSON.parse(data);
                $("#t_luas").val(aa.t_luas);
            });
        });
    });


    function carirekeningreklame() {
        $.post('<?= $this->url() ?>/carirekeningreklame', {
            t_jenisreklame: $('#t_jenisreklame').val()
        }).then(function(data) {
            var aa = JSON.parse(data);
            $("#t_idkorek").val(aa.t_idkorek);
            $("#t_korek").val(aa.t_korek);
            $("#t_namakorek").val(aa.t_namakorek);

            populateJangkaWaktuDropdown();
            // cariukuranmedia();

        });
    }

    function CariPendataanReklameByObjek() {
        $.post('<?= $this->url() ?>/CariPendataanReklameByObjek', {
            idobjek: $("#t_idobjek").val(),
            periodepajak: $("#t_periodepajak").val()
        }).then(function(data) {
            var aa = JSON.parse(data);
            $("#datatransaksi").html(aa.datatransaksi);
        });
    }

    function ceksize(input) {
        const fileSize = input.files[0].size / 1024 / 1024; // in MiB
        if (fileSize > 2) {
            alert('Ukuran File tidak boleh lebih dari 2 Mb');
            $("#t_rekomendasi").val(''); //for clearing with Jquery
        }
    }


    function toggleLokasiReklame() {
        showDiv('#divLokasiReklame', isReklamePermanen());
        setInputRequiered('#t_idlokasi', isReklamePermanen());
    }

    function toggleSudutPandangReklame() {
        showDiv('#divSudutPandang', isReklamePermanen());
        setInputRequiered('#t_sisi', isReklamePermanen());
    }

    function toggleLuasReklame() {

        showDiv('#divLuas', isReklameNeedLuas());
        setInputRequiered('#t_panjang', isReklameNeedLuas());
        setInputRequiered('#t_lebar', isReklameNeedLuas());
        setInputRequiered('#t_luas', isReklameNeedLuas());

    }

    function isReklameNeedLuas() {
        var jenisReklame = $('#t_jenisreklame').val();
        var reklameNeedLuas = ['6', '8', '9', '10', '11'];
        return $.inArray(jenisReklame, reklameNeedLuas) == -1;
    }

    function isReklamePermanen() {
        return $('#t_permanen').val() == '1';
    }

    function showDiv(div, show) {
        // if(show){
        //     $(div).show();
        // }else{
        //     $(div).hide();
        // }
    }

    function setInputRequiered(element, required) {
        if (required) {
            $(element).attr('required', 'required');
        } else {
            $(element).removeAttr('required');
        }
    }

    function resetJangkaWaktuDropdown() {
        // $('#t_tipewaktu').find('option').remove();
    }

    function resetKodeRekening() {
        $('#t_korek').val('');
        $('#t_namakorek').val('');
    }

    function getlokasi() {
        $.post('<?= $this->url() ?>/carilokasikelas', {
            t_kelasjalan: $("#t_kelasjalan").val()
        }).then(function(data) {
            var aa = JSON.parse(data);
            $("#t_idlokasi").html(aa.datalokasi);
        });
    }

    function hitungjangkawaktu() {
        if ($("#t_tipewaktu").val() == '') {

        } else {
            $.post('<?= $this->url() ?>/hitungjangkawaktu', {
                t_masaawal: $("#t_masaawal").val(),
                t_masaakhir: $("#t_masaakhir").val(),
                t_tipewaktu: $("#t_tipewaktu").val()
            }).then(function(data) {
                var aa = JSON.parse(data);
                $("#t_jangkawaktu").val(aa.t_jangkawaktu);
            });
        }
    }

    function cariukuranmedia() {
        if ($('#t_jenisreklame').val() == '10' || $('#t_jenisreklame').val() == '11' || $('#t_jenisreklame').val() == '12') {
            $('#t_ukuranmedia').html('<option value="2">Folio</option>');
            $("#hitungluas").hide();
        } else {
            $('#t_ukuranmedia').html('<option value="1">Meter</option>');
            $("#hitungluas").show();
        }
    }

    function gettarifreklame() {
        $.post('<?= $this->url() ?>/caritarifreklame', {
            t_jenistarif: $("#t_jenisreklameusaha").val()
        }).then(function(data) {
            var aa = JSON.parse(data);
            $("#t_tarifpajak").val(aa.t_tarifreklame);
            hitungpajakreklame();
        });

    }

    function hanyaAngka(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode
        if (charCode > 31 && (charCode < 48 || charCode > 57) && charCode != 46)


            return false;

        return true;
    }
</script>