<?php
$form = $this->form;
$form->setAttribute('action', $this->url() . '/form_pageppj');
$form->setAttribute("id", "demo-form");
$form->setAttribute("class", "form-horizontal pad15L pad15R pad15T");
$form->setAttribute("data-parsley-validate", "data-parsley-validate");
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();
?>

<style type="text/css">
    blink,
    .blink {
        -webkit-animation: blink 1s step-end infinite;
        -moz-animation: blink 1s step-end infinite;
        -o-animation: blink 1s step-end infinite;
        animation: blink 1s step-end infinite;
    }

    @-webkit-keyframes blink {
        67% {
            opacity: 0
        }
    }

    @-moz-keyframes blink {
        67% {
            opacity: 0
        }
    }

    @-o-keyframes blink {
        67% {
            opacity: 0
        }
    }

    @keyframes blink {
        67% {
            opacity: 0
        }
    }
</style>
<div id="page-content-wrapper" style="font-size:12px">
    <div id="page-content" style="background-color: #DFF0D8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <i class="glyph-icon icon-pencil"></i>
                    Pendataan <?= $datapendaftaran['s_namajenis'] ?><b class="blink" style="font-size: 12px; color: red"><?= $message ?></b>
                </h4>
            </div>
            <div class="panel-body">
                <div class="example-box-wrapper">
                    <div class="row">
                        <div class="col-md-12 center-div">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="text-align:center; background:black; border-radius: 25px; color: orange; padding: 5px 15px 5px 15px; font-size: 16px; font-weight:bolder">NPWPD : <?= $datapendaftaran['t_npwpd'] ?> / ID OP : <?= $datapendaftaran['t_nop'] ?></span>
                        </div>
                    </div>
                    <?= $this->form()->openTag($form) ?>
                    <div class="col-md-6">

                        <div class="content-box">
                            <h3 class="content-box-header content-box-header-alt bg-success">
                                <span class="icon-separator">
                                    <i class="glyph-icon icon-database"></i>
                                </span>
                                <span class="header-wrapper">
                                    Data WP
                                </span>
                            </h3>
                            <div class="content-box-wrapper">
                                <div class='row'>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">NIK</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_nik'] ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">Nama</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_nama'] ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">Alamat</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_alamat_lengkap'] ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="content-box">
                            <h3 class="content-box-header content-box-header-alt bg-success">
                                <span class="icon-separator">
                                    <i class="glyph-icon icon-database"></i>
                                </span>
                                <span class="header-wrapper">
                                    Data OP
                                </span>
                            </h3>
                            <div class="content-box-wrapper">
                                <div class='row'>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">NIOP</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_nop'] ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">Nama</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_namaobjek'] ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-2">Alamat</label>
                                        <div class="col-sm-10">
                                            : <?= $datapendaftaran['t_alamatobjek'] ?>
                                            ,RT. <?= $datapendaftaran['t_rtobjek'] ?>
                                            ,RW. <?= $datapendaftaran['t_rwobjek'] ?>
                                            ,Desa/Kel. <?= $datapendaftaran['s_namakelobjek'] ?>
                                            ,Kec. <?= $datapendaftaran['s_namakecobjek'] ?>
                                            ,Kab. <?= $datapendaftaran['t_kabupatenobjek'] ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="alert alert-info">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Histori Pajak</b></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div id="datatransaksi"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="alert alert-warning">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Data Pendataan</b></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Nomor SPTPD</label>
                            <div class="col-sm-2">
                                <input type="hidden" name="t_jenisobjekpajak" value="<?= $datapendaftaran['t_jenisobjek'] ?>">
                                <?= $this->formHidden($form->get("t_idtransaksi")) ?>
                                <?= $this->formHidden($form->get("t_idobjek")) ?>
                                <?= $this->formHidden($form->get("t_jenispajak")) ?>
                                <?= $this->formText($form->get("t_nourut")) ?>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Periode Pajak</label>
                            <div class="col-sm-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_periodepajak")) ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Tanggal Pendataan</label>
                            <div class="col-sm-2">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_tglpendataan")) ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Masa Pajak</label>
                            <div class="col-sm-5">
                                <div class="input-prepend input-group">
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>
                                    <?= $this->formText($form->get("t_masaawal")) ?>
                                    <!--</div>-->
                                    <span class="input-group-addon" style="background-color: #EEEEEE"><b>s/d</b></span>
                                    <!--<div class="input-prepend input-group">-->
                                    <?= $this->formText($form->get("t_masaakhir")) ?>
                                    <span class="add-on input-group-addon">
                                        <i class="glyph-icon icon-calendar"></i>
                                    </span>

                                </div>
                            </div>
                            <?php if ($datapendaftaran['t_jenisobjek'] == 2) { ?>
                                <div class="col-sm-3">
                                    <input type="text" name="t_berdasarmasa" id="t_berdasarmasa" class="form-control" style="background:black; color: greenyellow; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder" value="<?= $t_berdasarmasa ?>">
                                </div>
                            <?php } else { ?>
                                <div class="col-sm-3">
                                    <input type="hidden" name="t_berdasarmasa" id="t_berdasarmasa">
                                </div>
                            <?php } ?>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Asal Tenaga Listrik</label>
                            <div class="col-sm-4">
                                <?= $this->formSelect($form->get("t_asallistrik")) ?>
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Dasar Pengenaan</label>
                            <div class="col-sm-10 remove-columns">
                                <table class="table table-bordered table-striped table-condensed cf" style="font-size: 11px;">
                                    <tr>
                                        <th style="background-color:#00BCA4; color: white;" class="text-center">Uraian/Golongan</th>
                                        <th style="background-color:#00BCA4; color: white;" class="text-center">Jumlah Nilai Jual Tenaga Listrik (Rp.)</th>
                                        <th style="background-color:#00BCA4; color: white;" class="text-center">Tarif %</th>
                                        <th style="background-color:#00BCA4; color: white;" class="text-center">Jumlah Pajak (Rp.)</th>
                                    </tr>
                                    <?php
                                    $i = 0;
                                    foreach ($rekeningppj_pln as $col => $row) :
                                    ?>
                                        <tr>
                                            <td><?= $row['s_namakorek'] ?></td>
                                            <td><input id="nilailistrik<?= $i ?>" name="t_nilailistrik[]" type="text" class="form-control text-right nilailistrik" data-id="<?= $i ?>" data-tarif="<?= $row['s_persentarifkorek'] ?>" onchange="hitungpajak(this);this.value = formatCurrency(this.value);" onblur="hitungpajak(this);this.value = formatCurrency(this.value);" onkeyup="hitungpajak(this);this.value = formatCurrency(this.value);" onkeypress="return numbersonly(this, event);"></td>
                                            <td class="text-center"><?= $row['s_persentarifkorek'] ?><input type="hidden" name="t_idkorek[]" value="<?= $row['s_idkorek'] ?>"></td>
                                            <td><input id="subtotalpajak<?= $i ?>" name="t_subtotalpajak[]" type="text" class="form-control text-right subtotalpajak" readonly></td>

                                        </tr>
                                    <?php
                                        $i++;
                                    endforeach;
                                    ?>
                                    <tr>
                                        <td colspan="3" class="text-right">Total Pajak (Rp.)</td>
                                        <td><?= $this->formText($form->get("t_jmlhpajak")) ?></td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Dasar Pengenaan</label>
                                <div class="col-sm-10 remove-columns">
                                    <table class="table table-bordered table-striped table-condensed cf" style="font-size: 11px;">
                                        <tr>
                                            <th style="background-color:#00BCA4; color: white;" class="text-center">Uraian/Golongan</th>
                                            <th style="background-color:#00BCA4; color: white;" class="text-center">Jumlah KWH</th>
                                            <th style="background-color:#00BCA4; color: white;" class="text-center">Tarif Listrik per KWH</th>
                                            <th style="background-color:#00BCA4; color: white;" class="text-center">Jumlah</th>
                                        </tr>
                                        <?php
                                        $i = 0;
                                        foreach ($rekeningppj_nonpln as $col => $row) :
                                        ?>
                                            <tr>
                                                <td><?= $row['s_namakorek'] ?></td>
                                                <td><input id="nilailistrik<?= $i ?>" name="t_nilailistrik[]" type="text" class="form-control text-right nilailistrik" data-id="<?= $i ?>" data-tarifkwh="<?= $row['s_tarifdasarkorek'] ?>" onchange="hitungpajak(this);this.value = formatCurrency(this.value);" onblur="hitungpajak(this);this.value = formatCurrency(this.value);" onkeyup="hitungpajak(this);this.value = formatCurrency(this.value);" onkeypress="return numbersonly(this, event);"></td>
                                                <td class="text-center"><?= $row['s_tarifdasarkorek'] ?><input type="hidden" name="t_idkorek[]" value="<?= $row['s_idkorek'] ?>"></td>
                                                <td><input id="subtotalpajak<?= $i ?>" name="t_subtotalpajak[]" type="text" class="form-control text-right subtotalpajak" readonly></td>

                                            </tr>
                                        <?php
                                            $i++;
                                        endforeach;
                                        ?>
                                        <tr>
                                            <td colspan="3" class="text-right">Tarif (%)</td>
                                            <td><?= $this->formText($form->get("t_tarifdasar")) ?></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3" class="text-right">Total Pajak (Rp.)</td>
                                            <td><?= $this->formText($form->get("t_jmlhpajak")) ?></td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="bg-default" id="tombolsimpan">
                            <?= $this->formInput($form->get('Pendataansubmit')) ?>
                        </div>
                        <?= $this->form()->closeTag($form) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function calldataGridRekening(direction) {
            dataGridRekening($("#page").val(), $("#rows").val(), direction);
        }

        function dataGridRekening(page, row, direction) {
            $.post('<?= $this->url() ?>/dataGridRekening/' + null + '/' + page + '/' + row + '/' + direction + '?korek=' + $("#korek").val() + "&s_namakorek=" + $("#s_namakorek").val() + "&s_persentarifkorek=" + $("#s_persentarifkorek").val() + "&t_jenisobjek=" + $("#t_jenisobjek").val(), function(data) {
                var aa = JSON.parse(data);
                $("#listrekening").html(aa.grid);
                $("#rows").val(aa.rows);
                $("#page").val(aa.page);
                $("#total_data").html(": " + aa.count);
                $("#total_halaman").html(": " + aa.total_halaman);
            });
        }

        function bukamodalRekening() {
            calldataGridRekening();
            $('#modalRekening').modal('show');
        }

        function pilihRekening(a) {
            $.post('<?= $this->url() ?>/pilihRekening', {
                s_idkorek: a
            }, function(data) {
                var aa = JSON.parse(data);
                $('#t_idkorek').val(aa.t_idkorek);
                $('#t_korek').val(aa.t_korek);
                $('#t_namakorek').val(aa.t_namakorek);
                $('#t_tarifpajak').val(aa.t_tarifpajak);
                $('#t_berdasarmasa').val(aa.t_berdasarmasa);
                $('#modalRekening').modal('hide');
            });
        }

        // function hitungpajak() {
        //     $.post('<?= $this->url() ?>/hitungpajak', {t_dasarpengenaan: $("#t_dasarpengenaan").val(), t_tarifpajak: $("#t_tarifpajak").val(), t_tarifkenaikan: $("#t_tarifkenaikan").val(), t_jmlhkenaikan: $("#t_jmlhkenaikan").val(), t_jenispajak: $("#t_jenispajak").val(), t_idkorek: $("#t_idkorek").val()}, function (data) {
        //         var aa = JSON.parse(data);
        //         $('#t_jmlhpajak').val(aa.t_jmlhpajak);
        //         $('#t_jmlhkenaikan').val(aa.t_jmlhkenaikan);
        //         $('#t_tarifpajak').val(aa.t_tarifpajak);
        //     });
        // }

        $(function() {
            CariPendataanByObjek();
        });

        function CariPendataanByObjek() {
            $.post('<?= $this->url() ?>/CariPendataanByObjek', {
                idobjek: $("#t_idobjek").val(),
                periodepajak: $("#t_periodepajak").val()
            }, function(data) {
                var aa = JSON.parse(data);
                $("#datatransaksi").html(aa.datatransaksi);
            });
        }

        function pilihskpdjabatan(a) {
            $.post('<?= $this->url() ?>/pilihskpdjabatan', {
                parameter: a
            }, function(data) {
                var aa = JSON.parse(data);
                $("#t_tglpendataan").val(aa.t_tglpendataan);
                $("#t_masaawal").val(aa.t_masaawal);
                $("#t_masaakhir").val(aa.t_masaakhir);
                $("#t_tarifkenaikan").val(aa.t_tarifkenaikan);
            });
            document.getElementById("kenaikan").style.display = "block";
            setTimeout(function() {
                hitungpajak();
            }, 1000);
        }

        function nonskpdjabatan() {
            document.getElementById("kenaikan").style.display = "none";
            $("#t_tarifkenaikan").val(0);
            hitungpajak();
        }
    </script>
    <div class="modal fade" id="modalCetakSuratTeguran" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                <div class="modal-header bg-warning">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"><b>CETAK SURAT TEGURAN</b></h4>
                </div>
                <div class='modal-body'>
                    <div class='example-box-wrapper'>
                        <div class='example-box-wrapper'>
                            <div class="col-md-12 form-horizontal">
                                <label class="col-md-3 control-label">
                                    Jenis Pajak
                                </label>
                                <div class="col-md-4">
                                    <input type="hidden" id="idjenispajak">
                                    <input type="hidden" id="idobjekwp">
                                    <input type="text" class="form-control" id="jenispajak" readonly="">
                                </div>
                            </div>
                            <div class="col-md-12 form-horizontal">
                                <label class="col-md-3 control-label">
                                    Nama WP
                                </label>
                                <div class="col-md-4">
                                    <input type="text" class="form-control" id="namawp" readonly="">
                                </div>
                            </div>
                            <div class="col-md-12 form-horizontal">
                                <label class="col-md-3 control-label">
                                    Masa Pajak
                                </label>
                                <div class="col-sm-4">
                                    <div class="input-prepend input-group">
                                        <span class="add-on input-group-addon">
                                            <i class="glyph-icon icon-calendar"></i>
                                        </span>
                                        <input type="text" class="form-control" id="masaawal" readonly="">
                                    </div>
                                </div>
                                <label class="col-sm-1 control-label">S/D</label>
                                <div class="col-sm-4">
                                    <div class="input-prepend input-group">
                                        <span class="add-on input-group-addon">
                                            <i class="glyph-icon icon-calendar"></i>
                                        </span>
                                        <input type="text" class="form-control" id="masaakhir" readonly="">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 form-horizontal">
                                <label class="col-md-3 control-label">
                                    Alamat WP
                                </label>
                                <div class="col-md-9">
                                    <textarea class="form-control" id="alamatwp" readonly="">

                                </textarea>
                                </div>
                            </div>
                            <div class="col-md-12 form-horizontal">
                                <label class="col-md-3 control-label">
                                    Nomor Surat
                                </label>
                                <div class="col-md-4">
                                    <input type="text" class="form-control" id="nomorsrt" value="0001">
                                </div>
                            </div>
                            <div class="col-md-12 form-horizontal">
                                <label class="col-md-3 control-label">
                                    Penandatangan
                                </label>
                                <div class="col-md-9">
                                    <select id="ttd0" class="form-control">
                                        <?php foreach ($ar_ttd0 as $row) { ?>
                                            <option value="<?= $row['s_idpej'] ?>"><?= $row['s_namapej'] . " || " . $row['s_jabatanpej'] ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class='modal-footer'>
                    <div class='col-sm-12'>
                        <a href="#" class="btn btn-sm btn-danger" title="" onclick="cetaksuratteguran()"><i class="glyph-icon icon-file-pdf-o"></i> PDF</a>
                        <button class='btn btn-primary btn-sm' onclick='tutupCetakSuratTeguran()'><i class='glyph-icon icon-close'></i> Tutup</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function bukaCetakSuratTeguran(a, b) {
            $.post('<?= $this->url() ?>/dataSuratTeguran', {
                parameter: a,
                idobjekwp: b
            }, function(data) {
                var aa = JSON.parse(data);
                $("#idobjekwp").val(aa.idobjekwp);
                $("#namawp").val(aa.namawp);
                $("#alamatwp").val(aa.alamatwp);
                $("#jenispajak").val(aa.jenispajak);
                $("#idjenispajak").val(aa.idjenispajak);
                $("#masaawal").val(aa.t_masaawal);
                $("#masaakhir").val(aa.t_masaakhir);
            });
            $('#modalCetakSuratTeguran').modal('show');
        }

        function tutupCetakSuratTeguran() {
            $('#modalCetakSuratTeguran').modal('hide');
        }

        function cetaksuratteguran() {
            window.open('<?= $this->url() ?>/cetaksuratteguran?idobjekwp=' + $("#idobjekwp").val() + "&ttd0=" + $("#ttd0").val() + "&masaawal=" + $("#masaawal").val() + "&masaakhir=" + $("#masaakhir").val() + "&nomorsrt=" + $("#nomorsrt").val());
        }

        function hitungpajak(o) {
            if (typeof o != undefined) {
                var id = $(o).data('id');
                var nilai = $(o).val();
                var tarif = $(o).data('tarif') / 100;
                var subtotal = unformatCurrency(nilai) * tarif;
                $('#subtotalpajak' + id).val(subtotal);
                document.getElementById('subtotalpajak' + id).value = formatCurrency(document.getElementById('subtotalpajak' + id).value);
                hitungtotalpajak();
            }
        }

        function hitungpajakkwh(o) {
            if (typeof o != undefined) {
                var id = $(o).data('id');
                var nilai = $(o).val();
                var tarif = $(o).data('tarifkwh') / 100;
                var subtotal = unformatCurrency(nilai) * tarif;
                $('#subtotalpajak' + id).val(subtotal);
                document.getElementById('subtotalpajak' + id).value = formatCurrency(document.getElementById('subtotalpajak' + id).value);
                hitungtotalpajak();
            }
        }

        function hitungtotalpajak() {
            $('#t_jmlhpajak').val('');
            var totalpajak = 0;
            $('.subtotalpajak').each(function(i) {
                var s = unformatCurrency($(this).val());
                totalpajak += Number(s);
            });
            $('#t_jmlhpajak').val(totalpajak);
            document.getElementById('t_jmlhpajak').value = formatCurrency(document.getElementById('t_jmlhpajak').value);
        }
    </script>