<?php
$ukuran = [
  1 => 'Sampai dengan 5 m<sup>2</sup>',  
  2 => 'Lebih dari 5 m<sup>2</sup> s/d 10 m<sup>2</sup>',  
  3 => 'Lebih dari 10 m<sup>2</sup> s/d 15 m<sup>2</sup>',  
  4 => 'Lebih dari 15 m<sup>2</sup> s/d 20 m<sup>2</sup>',  
  5 => 'Lebih dari 20 m<sup>2</sup> s/d 30 m<sup>2</sup>',  
  6 => 'Lebih dari 30 m<sup>2</sup> s/d 40 m<sup>2</sup>',  
  7 => 'Lebih dari 40 m<sup>2</sup>',  
];
?>
<div id="page-content-wrapper">
    <div id="page-content">
        <div class="">
            <!-- Parsley -->
            <div id="page-title">
                <h2>
                    Setting Skor Ukuran Reklame
                </h2>
            </div>
            <div class="panel">
                <div class="panel-body">
                    <div class="example-box-wrapper">         
                        <div>
                            <form id="formreklame" method="post" action="<?= $this->url() ?>">
                                <table class="table table-bordered table-condensed table-striped">

                                    <tr>
                                        <th style="background-color: #00BCA4; color: white; text-align: center;">Ukuran</th>
                                        <th style="background-color: #00BCA4; color: white; text-align: center;">Skor</th>
                                    </tr>
                                    <?php
                                    foreach ($data as $row):
                                        ?>
                                        <tr>
                                            <td><?= $ukuran[$row['s_idskorukuran']] ?><input type="hidden" name="s_idskorukuran[]" value="<?= $row['s_idskorukuran'] ?>" /></td>
                                            <td><input type="text" name="s_skor[]" class="form-control text-right" value="<?= $row['s_skor'] ?>" onkeypress="return numbersonly(this.value, event);"/></td>
                                        </tr>
                                        <?php
                                    endforeach;
                                    ?>

                                </table>
                                <div class="col-sm-12">
                                    <input type="submit" value="Update" class="btn btn-primary btn-sm form-control" />
                                    <a href="<?= $this->url('main') ?>" class="btn btn-warning btn-sm form-control">Kembali</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



