<?php
$form = $this->form;
$form->setAttribute('action', $this->url() . '/form_tambah');
$form->setAttribute("id", "demo-form");
$form->setAttribute("class", "form-horizontal pad15L pad15R pad15T");
$form->setAttribute("data-parsley-validate", "data-parsley-validate");
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();
?>
<div id="page-content-wrapper">
    <div id="page-content">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <b style="font-family: monospace;">EDIT PERMOHONAN KEBERATAN</b>
                </h3>
            </div>
            <div class="panel-body">
                <div class="example-box-wrapper">
                    <?= $this->form()->openTag($form) ?>
                    <div class="row pad10B">
                        <div class="col-sm-12">
                            <div class="alert alert-success">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Data WP & OP</b></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Jenis Ketetapan</label>
                            <div class="col-md-4">
                                <?= $this->formHidden($form->get("t_idkeberatan")) ?>
                                <?= $this->formHidden($form->get("t_jenispajak")) ?>
                                <?= $this->formHidden($form->get("t_idwpobjek")) ?>
                                <?= $this->formSelect($form->get("t_jenisketetapan")) ?>
                            </div>
                            <div class="col-md-1">
                                <button type="button" id="cariketetapan" class="btn btn-warning btn-md"><span class="glyph-icon icon-search-minus"></span> Cari Ketetapan</button>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">NPWP</label>
                            <div class="col-md-4">
                                <input type="text" id="t_npwpdwp" class="form-control" readonly="" value="<?= $data['t_npwpdwp'] ?>">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Nama WP</label>
                            <div class="col-md-4">
                                <input type="text" id="t_namawp" class="form-control" readonly="" value="<?= $data['t_namawp'] ?>">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Alamat WP</label>
                            <div class="col-md-6">
                                <textarea class="form-control" id="t_alamat_lengkap" readonly=""><?= $data['t_alamat_lengkapwp'] ?></textarea>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">NOP</label>
                            <div class="col-md-4">
                                <input type="text" id="t_nop" class="form-control" readonly="" value="<?= $data['t_nop'] ?>">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Nama OP</label>
                            <div class="col-md-4">
                                <input type="text" id="t_namaobjek" class="form-control" readonly="" value="<?= $data['t_namaobjek'] ?>">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Alamat OP</label>
                            <div class="col-md-6">
                                <textarea class="form-control" id="t_alamatlengkapobjek" readonly=""><?= $data['t_alamatlengkapobjek'] ?></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row pad10B">
                        <div class="col-sm-12">
                            <div class="alert alert-success">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Data Ketetapan</b></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Nama Ketetapan</label>
                            <div class="col-md-2">
                                <?= $this->formHidden($form->get("t_idketetapan")) ?>
                                <input type="text" id="t_namaketetapan" class="form-control" readonly="" value="<?= $jenisketetapan ?>">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">No. Ketetapan</label>
                            <div class="col-md-2">
                                <input type="text" id="t_nopenetapan" class="form-control" readonly="" value="<?= $data['t_nopenetapan'] ?>">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Tgl. Ketetapan</label>
                            <div class="col-md-2">
                                <input type="text" id="t_tglpenetapan" class="form-control" readonly="" value="<?= date('d-m-Y', strtotime($data['t_tglpenetapan'])) ?>">
                            </div>
                            <label class="col-sm-2 control-label">Tgl. Jatuh Tempo</label>
                            <div class="col-md-2">
                                <input type="text" id="t_tgljatuhtempo" class="form-control" readonly="" value="<?= date('d-m-Y', strtotime($data['t_tgljatuhtempo'])) ?>" style="background:green; color: white; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder">
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Jumlah Ketetapan</label>
                            <div class="col-md-4">
                                <?= $this->formText($form->get("t_jmlhpajak")) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row pad10B">
                        <div class="col-sm-12">
                            <div class="alert alert-danger">
                                <div class="alert-content">
                                    <h4 class="alert-title"><b style="color: #000099">Data Permohonan Keberatan</b></h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Tgl. Permohonan</label>
                            <div class="col-md-2">
                                <?= $this->formText($form->get("t_tglketetapankeberatan")) ?>
                            </div>
                        </div>
                        <div id="reklame">
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Jangka Waktu Pendataan</label>
                                <div class="col-md-2">
                                    <input type="text" class="form-control" readonly name="" id="jangakwaktusebelumnya">
                                </div>
                                <label class="col-sm-1 control-label">Seharusnya</label>
                                <div class="col-md-2">
                                    <?= $this->formText($form->get("t_jangkawaktu")) ?>
                                </div>
                                <div class="col-sm-1">
                                    <input type="text" readonly="" name="" id="t_tipewaktu" class="form-control">
                                    <input type="hidden" readonly="" name="" id="t_idtipewaktu" class="form-control">
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Range Ukuran media</label>
                                <div class="col-sm-2">
                                    <?= $this->formSelect($form->get("t_ukuranmedia")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Jumlah</label>
                                <div class="col-sm-1">
                                    <?= $this->formText($form->get("t_jumlah")) ?>
                                </div>
                                <label class="col-sm-2 control-label">Kategori</label>
                                <div class="col-sm-2">
                                    <?= $this->formSelect($form->get("t_jenisreklameusaha")) ?>
                                </div>
                                <div class="col-sm-3">
                                    <?= $this->formText($form->get("t_parameter")) ?>
                                </div>
                                <div class="col-sm-1">
                                    <a class="btn btn-success" onclick="hitungpajakreklame()">Hitung</a>
                                </div>
                                <input type="hidden" id="t_jenisreklame" name="">
                                <input type="hidden" id="t_kelasjalan" name="">
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Dasar Pengenaan</label>
                                <div class="col-sm-2">
                                    <?= $this->formText($form->get("t_dasarpengenaan")) ?>
                                </div>
                            </div>
                        </div>
                        <div id="air">
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Lama Waktu (Tahun)</label>
                                <div class="col-sm-2">
                                    <input type="text" class="form-control" readonly="" id="lamawaktu" name="">
                                </div>
                                <div class="col-sm-2">
                                    <?= $this->formText($form->get("t_lamawaktu")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Debit Air/sumur(/hari)</label>
                                <div class="col-sm-2">
                                    <?= $this->formText($form->get("t_debitair")) ?>
                                </div>
                                <label class="col-sm-1">M<sup>3</sup></label>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Kualitas Air</label>
                                <div class="col-sm-4">
                                    <?= $this->formSelect($form->get("t_kualitasair")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Peruntukan</label>
                                <div class="col-sm-2">
                                    <?= $this->formSelect($form->get("t_peruntukan")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Total Biaya (Rp)</label>
                                <div class="col-sm-2">
                                    <?= $this->formText($form->get("t_totalbiaya")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Volume Air (M<sup>3</sup>)</label>
                                <div class="col-sm-2">
                                    <?= $this->formText($form->get("t_volume")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Total NPA</label>
                                <div class="col-sm-2">
                                    <?= $this->formText($form->get("t_npa")) ?>
                                </div>
                                <div class="col-sm-1">
                                    <a class="btn btn-success" onclick="hitungpajakair()">Hitung</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Tarif (%)</label>
                            <div class="col-sm-2">
                                <?= $this->formText($form->get("t_tarifpajak")) ?>
                                <!-- <input type="text" class="form-control" name="" id="t_tarifpajak"> -->
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Jumlah Pajak Seharusnya</label>
                            <div class="col-sm-2">
                                <?= $this->formText($form->get("t_jmlhketetapanseharusnya")) ?>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <label class="col-sm-2 control-label">Alasan Keberatan</label>
                            <div class="col-md-6">
                                <?= $this->formTextarea($form->get("t_alasankeberatan")) ?>
                            </div>
                        </div>
                    </div>
                    <div class="bg-default" id="tombolsimpan">
                        <?= $this->formInput($form->get('submit')) ?>
                    </div>
                    <?= $this->form()->closeTag($form) ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#t_jumlahkaliangsuran').change(function() {
        $.post('<?= $this->url() ?>/CariJumlahKaliAngsuran', {
            t_jumlahkaliangsuran: $('#t_jumlahkaliangsuran').val(),
            t_tglketetapanangsuran: $('#t_tglketetapanangsuran').val(),
            t_tgljatuhtempo: $('#t_tgljatuhtempo').val(),
            t_jmlhpajak: $('#t_jmlhpajak').val()
        }, function(data) {
            var aa = JSON.parse(data);
            $("#rincianangsuran").html(aa.rincianangsuran);
        });
    });

    $('#t_tglketetapanangsuran').change(function() {
        $.post('<?= $this->url() ?>/CariJumlahKaliAngsuran', {
            t_jumlahkaliangsuran: $('#t_jumlahkaliangsuran').val(),
            t_tglketetapanangsuran: $('#t_tglketetapanangsuran').val(),
            t_tgljatuhtempo: $('#t_tgljatuhtempo').val(),
            t_jmlhpajak: $('#t_jmlhpajak').val()
        }, function(data) {
            var aa = JSON.parse(data);
            $("#rincianangsuran").html(aa.rincianangsuran);
        });
    });
</script>
<div class="modal fade" id="modalKetetapan" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><b>
                        <div id="judulketetapan"></div>
                    </b></h4>
            </div>
            <div class='modal-body'>
                <div>
                    <table class="table table-condensed table-bordered cf" style="font-size: 11px; color: black">
                        <thead class="cf">
                            <tr class="bg-blue">
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    NIOP
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    Nama OP
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    NPWPD
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    Nama WP
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    No. <div id="namaketetapan"></div>
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    Tgl. <div id="namaketetapan1"></div>
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    Jumlah Pajak (Rp.)
                                </th>
                                <th style="background-color: #00BCA4; color: white; text-align: center">
                                    Pilihan
                                </th>
                            </tr>
                            <tr>
                                <td>
                                    <input type="text" id="t_nopcari" class="form-control input-sm" onkeyup="calldataGridKetetapan()">
                                </td>
                                <td>
                                    <input type="text" id="t_namaobjekcari" class="form-control input-sm" onkeyup="calldataGridKetetapan()">
                                </td>
                                <td>
                                    <input type="text" id="t_npwpdwpcari" class="form-control input-sm" onkeyup="calldataGridKetetapan()">
                                </td>
                                <td>
                                    <input type="text" id="t_namawpcari" class="form-control input-sm" onkeyup="calldataGridKetetapan()">
                                </td>
                                <td>
                                    <input type="text" id="t_nopenetapancari" class="form-control input-sm" onkeyup="calldataGridKetetapan()">
                                </td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody id="listketetapan">
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="8" class="text-center">
                                    <div class="row">
                                        <div class="col-sm-4 text-left">Jumlah Baris Ditampilkan: <input type="text" id="rows" style="width: 20%" class="text-center" value="10"></div>
                                        <div class="col-sm-3">
                                            <a href="#" onclick="calldataGridKetetapan(1);
                                                    return false;"><span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span></a>

                                            <input type="text" id="page" value="1" style="width: 20%" class="text-center">

                                            <a href="#" onclick="calldataGridKetetapan(2);
                                                    return false;"><span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span></a>
                                        </div>
                                        <div class="col-sm-5 text-right">
                                            <p>Jumlah Data <span id="total_data"></span>&nbsp;Jumlah Halaman <span id="total_halaman"></span></p>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-xs" style="width: 300px">
        <div class="modal-content">
            <div class="modal-header bg-danger">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><span class="glyph-icon icon-warning"></span><b> Peringatan</b></h4>
            </div>
            <div class="modal-body">
                <p style="font-weight: bold">Pilih "Jenis Ketetapan" Terlebih Dahulu.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-xs" data-dismiss="modal"><span class="glyph-icon icon-close"></span> Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#t_jenisketetapan').change(function() {
        $('#t_namawp').val('');
        $('#t_npwpdwp').val('');
        $('#t_alamat_lengkap').val('');
        $('#t_namaobjek').val('');
        $('#t_nop').val('');
        $('#t_alamatlengkapobjek').val('');
        $('#t_namaketetapan').val('');
        $('#t_nopenetapan').val('');
        $('#t_tglpenetapan').val('');
        $('#t_jmlhpajak').val('');
    });

    $('#cariketetapan').click(function() {
        if ($("#t_jenisketetapan").val() == '') {
            $('#myModal').modal('show');
        } else {
            calldataGridKetetapan();
            $('#modalKetetapan').modal('show');
        }
    });

    var u = document.getElementById("reklame");
    var v = document.getElementById("air");

    $(function() {
        hideall();
        cekjenispajak();
        $('#lamawaktu').val($('#t_lamawaktu').val());
        //pilihKetetapan();

    });

    function hideall() {
        u.style.display = "none";
        v.style.display = "none";

    }

    function calldataGridKetetapan(direction) {
        dataGridKetetapan($("#page").val(), $("#rows").val(), direction);
    }

    function cekjenispajak() {

        if ($('#t_jenispajak').val() == 4 || $('#t_jmlhpajak').val() == '4') {
            u.style.display = "block";
            v.style.display = "none";
            gettarifreklame();
            hitungpajakreklame();
        } else if ($('#t_jenispajak').val() == 8 || $('#t_jmlhpajak').val() == '8') {
            u.style.display = "none";
            v.style.display = "block";

            hitungpajakair();
        } else {

        }

    }

    function dataGridKetetapan(page, row, direction) {
        $.post('<?= $this->url() ?>/dataGridKetetapan/' + page + '/' + row + '/' + direction, {
            t_nop: $("#t_nopcari").val(),
            t_namaobjek: $("#t_namaobjekcari").val(),
            t_npwpdwp: $("#t_npwpdwpcari").val(),
            t_namawp: $("#t_namawpcari").val(),
            t_nopenetapan: $("#t_nopenetapancari").val(),
            t_jenisketetapan: $("#t_jenisketetapan").val()
        }, function(data) {
            var aa = JSON.parse(data);
            $("#listketetapan").html(aa.grid);
            $("#rows").val(aa.rows);
            $("#page").val(aa.page);
            $("#total_data").html(": " + aa.count);
            $("#total_halaman").html(": " + aa.total_halaman);
            $("#judulketetapan").html(aa.judulketetapan);
            $("#namaketetapan").html(aa.namaketetapan);
            $("#namaketetapan1").html(aa.namaketetapan);
        });
    }

    function pilihKetetapan(a, b) {
        $.post('<?= $this->url() ?>/pilihKetetapan', {
            t_idketetapan: a,
            t_jenisketetapan: b
        }, function(data) {
            var aa = JSON.parse(data);
            $('#t_idwpobjek').val(aa.t_idwpobjek);
            $('#t_namawp').val(aa.t_namawp);
            $('#t_npwpdwp').val(aa.t_npwpdwp);
            $('#t_alamat_lengkap').val(aa.t_alamat_lengkap);
            $('#t_namaobjek').val(aa.t_namaobjek);
            $('#t_nop').val(aa.t_nop);
            $('#t_alamatlengkapobjek').val(aa.t_alamatlengkapobjek);
            $('#t_namaketetapan').val(aa.t_namaketetapan);
            $('#t_jenispajak').val(aa.t_jenispajak);
            $('#t_idketetapan').val(aa.t_idketetapan);
            $('#t_nopenetapan').val(aa.t_nopenetapan);
            $('#t_tglpenetapan').val(aa.t_tglpenetapan);
            $('#t_tgljatuhtempo').val(aa.t_tgljatuhtempo);
            $('#t_jmlhpajak').val(aa.t_jmlhpajak);
            $('#t_tarifpajak').val(aa.t_tarifpajak);
            $('#t_jmlhketetapanseharusnya').val(aa.t_jmlhpajak);

            if (aa.t_jenispajak == 4 || aa.t_jenispajak == '4') {
                u.style.display = "block";
                v.style.display = "none";
                $('#jangakwaktusebelumnya').val(aa.t_jangkawaktu);
                $('#t_jangkawaktu').val(aa.t_jangkawaktu);
                $('#t_tipewaktu').val(aa.t_tipewaktu);
                $('#t_jumlah').val(aa.t_jumlah);
                $('#t_ukuranmedia').html(aa.t_ukuranmedia);
                $('#t_jenisreklameusaha').html(aa.t_jenisreklameusaha);
                $('#t_jenisreklame').val(aa.t_jenisreklame);
                $('#t_kelasjalan').val(aa.t_kelasjalan);
                $('#t_idtipewaktu').val(aa.t_idtipewaktu);
                $('#t_parameter').val(aa.t_parameter);
                $('#t_dasarpengenaan').val(aa.t_dasarpengenaan);


            } else if (aa.t_jenispajak == 8 || aa.t_jenispajak == '8') {
                u.style.display = "none";
                v.style.display = "block";
                $('#lamawaktu').val(aa.t_lamawaktu);
                $('#t_lamawaktu').val(aa.t_lamawaktu);
                $('#t_debitair').val(aa.t_debitair);
                $('#t_totalbiaya').val(aa.t_totalbiaya);
                $('#t_jumlah').val(aa.t_jumlah);
                $('#t_volume').val(aa.t_volume);
                $('#t_npa').val(aa.t_npa);
            } else {

            }


            $('#modalKetetapan').modal('hide');
        });
    }

    function hitungpajakair() {
        var params = {
            t_volume: $("#t_volume").val(),
            t_tarifpajak: $("#t_tarifpajak").val(),
            t_totalbiaya: $("#t_totalbiaya").val(),
            t_kualitasair: $("#t_kualitasair").val(),
            t_peruntukan: $("#t_peruntukan").val(),
            t_peruntukanair: $("#t_peruntukanair").val(),
            t_lamawaktu: $("#t_lamawaktu").val(),
            t_debitair: $("#t_debitair").val(),


        };
        $.post('<?= $this->url() ?>/hitungpajakair', params, function(data) {
            var aa = JSON.parse(data);

            $('#t_jmlhketetapanseharusnya').val(aa.t_jmlhpajak);
            // $('#t_jmlhkenaikan').val(aa.t_jmlhkenaikan);
            $('#t_npa').val(aa.t_totalnpa);

        });
    }

    function hitungpajakreklame() {
        $.post('<?= $this->url() ?>/hitungpajakreklame', {

            t_jenisreklame: $("#t_jenisreklame").val(),
            t_kelasjalan: $('#t_kelasjalan').val(),
            t_jangkawaktu: $("#t_jangkawaktu").val(),
            t_jumlah: $("#t_jumlah").val(),
            t_tipewaktu: $("#t_idtipewaktu").val(),
            t_ukuranmedia: $("#t_ukuranmedia").val(),
            t_satuanukuranmedia: $("#t_satuanukuranmedia").val(),
            t_tarifpajak: $("#t_tarifpajak").val(),
            // t_jenistarif :


        }).then(function(data) {
            var aa = JSON.parse(data);
            console.log(aa);
            $('#t_parameter').val(aa.parameter);
            $('#t_dasarpengenaan').val(aa.nsr);
            $('#t_jmlhketetapanseharusnya').val(aa.t_jmlhpajak);

        });
    }

    function gettarifreklame() {
        $.post('<?= $this->url() ?>/caritarifreklame', {
            t_jenistarif: $("#t_jenisreklameusaha").val()
        }).then(function(data) {
            var aa = JSON.parse(data);
            $("#t_tarifpajak").val(aa.t_tarifreklame);
            hitungpajakreklame();
        });

    }
</script>