<?php

ini_set("max_execution_time", 5000);


include($_SERVER['DOCUMENT_ROOT'] . "/" . $this->basePath() . '/public/cetakan/MPDF57/mpdf.php');
$mpdf = new mPDF('utf-8', 'Legal', 0, '', 15, 15, 10, 15, 1, 1, '');


$numbering = '<htmlpageheader name="MyHeader1">

            </htmlpageheader>

            <htmlpageheader name="MyHeader2">

            </htmlpageheader>

            <htmlpagefooter name="MyFooter1">
            <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
                color: #000000; font-weight: bold; font-style: italic;"><tr>
                <td width="33%"><span style="font-weight: bold; font-style: italic;"></span></td>
                <td width="33%" align="center" style="font-weight: bold; font-style: italic;">{PAGENO}/{nbpg}</td>
                <td width="33%" style="text-align: right; "></td>
                </tr></table>
            </htmlpagefooter>

            <htmlpagefooter name="MyFooter2">
            <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
                color: #000000; font-weight: bold; font-style: italic;"><tr>
                <td width="33%"><span style="font-weight: bold; font-style: italic;"></span></td>
                <td width="33%" align="center" style="font-weight: bold; font-style: italic;">{PAGENO}/{nbpg}</td>
                <td width="33%" style="text-align: right; "></td>
                </tr></table>
            </htmlpagefooter>';


$html = '';
$html .= '
<html>
    <head>
        <style type="text/css">            
            @page {
                size: auto;
                odd-header-name: html_MyHeader1;
                odd-footer-name: html_MyFooter1;
              }
              @page chapter2 {
                  odd-header-name: html_MyHeader2;
                  odd-footer-name: html_MyFooter2;
              }
              @page noheader {
                  odd-header-name: _blank;
                  odd-footer-name: _blank;
              }
              div.chapter2 {
                  page-break-before: always;
                  page: chapter2;
              }
              div.noheader {
                  page-break-before: always;
                  page: noheader;
              }
            .border_atas {
                    border-top: 1px solid black;
                    border-collapse: collapse;
            }

            .border_kiri {
                    border-left: 1px solid black;
                    border-collapse: collapse;
            }

            .border_kanan {
                    border-right: 1px solid black;
                    border-collapse: collapse;
            }

            .border_bawah {
                    border-bottom: 1px solid black;
                    border-collapse: collapse;
            }

           

        </style>
    </head>
    <body>
            
            '.$numbering.'


                 
            <h2 style="text-align: center">DAFTAR JALAN REKLAME</h2>
            <table width="100%" class="font_sembilan" border="1" style="border-spacing: 0px;">
                <tr style="text-align: center">
                    <td style="width: 5%;">
                        <center><b>No.</b></center>
                    </td>
                    <td>
                        <center><b>Kode Jalan</b></center>
                    </td>
                    <td>
                       <center><b> Nama Jalan</b></center>
                    </td>
                    <td>
                       <center><b>Zona</b></center>
                    </td>
                    <td>
                        <center><b>Kecamatan</b></center>
                    </td>
                    <td>
                       <center><b> Kelurahan</b></center>
                    </td>
                </tr>';
                
                $counter = 1;
                foreach ($this->datajalanreklame as $k => $v) {
                    $html .= '
                    <tr>
                        <td style="text-align: center">
                            '.$counter.'
                        </td>
                        <td style="text-align: center">
                            '.$v['kd_jlnreklame'].'
                        </td>
                        <td>
                            '.$v['nama_jlnreklame'].'
                        </td>
                        <td >
                            '.$v['nama_zona_reklame'].'
                        </td>
                        <td >
                            '.$v['s_namakec'].'
                        </td>
                        <td >
                            '.$v['s_namakel'].'
                        </td>
                    </tr>
                    ';
                    $counter++;
                }
                $html .= '
            </table>
        
    </body>
</html>';
                
$mpdf->WriteHTML($html);
$mpdf->Output("cetakdaftarjalanreklame.pdf", "I");
    
?>    

