<?php
$judul = '<span style="font-size: 24px;"><b>DATA JALAN REKLAME</b></span>';
$link = '<a href="' . $this->url() . '/tambah" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;TAMBAH
            </a>                                                             
            <button class="btn btn-warning" onclick="cetakdaftarjalan();">
                <span class="glyphicon glyphicon-print"></span>&nbsp;&nbsp;Cetak Daftar Jalan
            </button>';

echo $this->MenuHelper()->headeratas($judul, $link);
?>

<table id="datajalanreklame" cellpadding="0" cellspacing="0" border="0" class="display" width="100%" style="width:100%;">
    <thead>
        <tr class="bg-blue tableheader">

            <th width="15">No</th>
            <th>Kode Jalan</th>            
            <th>Nama Jalan</th>      
            <th>Zona</th>       
            <th>Nama Kecamatan</th>  
            <th>Nama Kelurahan</th>      
            <th>Perintah</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>

    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
</tfoot>
</table>
<style type="text/css">
.dataTables_filter {
     display: none;
}
</style> 
<?php
    $idtabel = '#datajalanreklame';
    $url = $this->url().'/dataGrid';
    $jmlkolom = 6;
    $seleksi_kolom = "'6'"; //iki data sort di disabel
    $pencarian_bawah = 5;
    
?>
<?= $this->MenuHelper()->fr_datatables($this->basePath(), $idtabel, $url, $jmlkolom, $pencarian_bawah, $seleksi_kolom, null);?>

<?= $this->MenuHelper()->headeratas_end(); ?>                    



<script type="text/javascript">
    
    function hapus(a) {
        var tanya = confirm("Hapus data ini?")
        if (tanya) {
            $.post('<?= $this->url() ?>/hapus/' + a);
        }
        setTimeout(function () {
            dTable.ajax.reload();
        }, 500);
    }

    function cetakdaftarjalan() {
        window.open('<?= $this->url() ?>/cetakdaftarjalan');
    }
</script>
