<?php
$judul = '<span style="font-size: 24px;"><b>DATA ZONA</b></span>';
$link = '<a href="' . $this->url() . '/tambahzona" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;TAMBAH
            </a>                                                             
            ';

echo $this->MenuHelper()->headeratas($judul, $link);
?>

<table id="datazonareklame" cellpadding="0" cellspacing="0" border="0" class="display" width="100%" style="width:100%;">
    <thead>
        <tr class="bg-blue tableheader">

            <th width="15">No</th>
            <th>Nama</th>            
            <th>Nilai</th>      
            <th>Tgl Awal</th>       
            <th>Tgl Akhir</th>  
               
            <th>Perintah</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>

    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
   
</tfoot>
</table>
<style type="text/css">
.dataTables_filter {
     display: none;
}
</style> 
<?php
    $idtabel = '#datazonareklame';
    $url = $this->url().'/dataGridzona';
    $jmlkolom = 5;
    $seleksi_kolom = "'5'"; //iki data sort di disabel
    $pencarian_bawah = 5;
    
?>
<?= $this->MenuHelper()->fr_datatables($this->basePath(), $idtabel, $url, $jmlkolom, $pencarian_bawah, $seleksi_kolom, null);?>

<?= $this->MenuHelper()->headeratas_end(); ?>                    



<script type="text/javascript">
    
    function hapus(a) {
        var tanya = confirm("Hapus data ini?")
        if (tanya) {
            $.post('<?= $this->url() ?>/hapuszona/' + a);
        }
        setTimeout(function () {
            dTable.ajax.reload();
        }, 500);
    }

    function cetakdaftarzona() {
        window.open('<?= $this->url() ?>/cetakdaftarzona');
    }
</script>
