<?php
$frm = $this->frm;
$frm->setAttribute('action', $this->url() . '/tambah');
$frm->setAttribute('id', "formtambah");
$frm->prepare();
?>

<?php
$judul = 'FORM JALAN REKLAME [TAMBAH]';
$link = '';

echo $this->MenuHelper()->headeratas($judul, $link);
?>
<?= $this->form()->openTag($frm) ?>
<div class="col-sm-12">
    <label class="col-sm-2 control-label">Kode Jalan</label>
    <div class="col-md-4">
        <?= $this->formHidden($frm->get('id_jlnreklame')) ?>  
        <?= $this->formRow($frm->get('kd_jlnreklame')) ?> 
    </div>
</div>
<div class="col-sm-12">
    <label class="col-sm-2 control-label">Nama Jalan</label>
    <div class="col-md-4">
        
        <?= $this->formRow($frm->get('nama_jlnreklame')) ?>
    </div>
</div>
<div class="col-sm-12">
    <label class="col-sm-2 control-label">Zona</label>
    <div class="col-md-4">
        <?= $this->formRow($frm->get('id_zona_reklame')) ?>
    </div>
</div>
<div class="col-sm-12">
    <label class="col-sm-2 control-label">Nama Kecamatan</label>
    <div class="col-md-4">
        <?= $this->formRow($frm->get('s_idkec')) ?>
    </div>
</div>
<div class="col-sm-12">
    <label class="col-sm-2 control-label">Nama Kelurahan/Desa</label>
    <div class="col-md-4">
        <?= $this->formRow($frm->get('s_idkel')) ?>
    </div>
</div>
 
<div class="col-sm-12">
    <label class="col-sm-2 control-label"></label>
    <div class="col-md-4">
        <?= $this->formInput($frm->get('simpan')) ?> 
        <a href="<?= $this->url('setting_jalanreklame') ?>" class="btn btn-warning btn-sm">Kembali</a>
    </div>
</div>
<?= $this->form()->closeTag($frm) ?>
<?= $this->MenuHelper()->headeratas_end(); ?> 

<script type="text/javascript">
                       
    function combokeckelcari() {
        $.post('<?= $this->url('pendataan') ?>/comboKelurahanCamat', {t_kecamatan: $('#s_idkec').val()}, function (data) {
            var aa = JSON.parse(data);
            $("#s_idkeljalan").html(aa.res);
            //alert(aa.res);
        });
        
    }


</script>