

<?php
$judul = 'FORM ZONA REKLAME [TAMBAH]';
$link = '';

echo $this->MenuHelper()->headeratas($judul, $link);
?>
<form method="post" action="<?= $this->url('setting_jalanreklame')?>/tambahzona" id="formtambah" class="form-horizontal">
<div class="col-sm-12">
    <label class="col-sm-2 control-label">Nama Zona</label>
    <div class="col-md-4">
        <input name="id_zona_reklame" id="id_zona_reklame" value="" type="hidden">  
        <div class="form-group "><input name="nama_zona_reklame" id="nama_zona_reklame" class="form-control" required="required" value="" type="text"></div>
 
    </div>
</div>
<div class="col-sm-12">
    <label class="col-sm-2 control-label">Nilai</label>
    <div class="col-md-4">
        
        <div class="form-group "><input name="nilai_zona_reklame" id="nilai_zona_reklame" class="form-control" required="required" value="" type="text"></div>
    </div>
</div>
<div class="col-sm-12">
    <label class="col-sm-2 control-label">Tgl Awal Berlaku</label>
    <div class="col-md-4">
        
        <div class="form-group "><input name="tglawal_zona" id="tglawal_zona" class="form-control" required="required" value="" type="text"></div>
    </div>
</div>
<div class="col-sm-12">
    <label class="col-sm-2 control-label">Tgl Akhir Berlaku</label>
    <div class="col-md-4">
        
        <div class="form-group "><input name="tglakhir_zona" id="tglakhir_zona" class="form-control" required="required" value="" type="text"></div>
    </div>
</div>
 
<div class="col-sm-12">
    <label class="col-sm-2 control-label"></label>
    <div class="col-md-4">
        <input name="simpan" class="btn btn-primary btn-sm" required="required" value="Simpan" type="submit">
        <a href="<?= $this->url('setting_jalanreklame') ?>/settingzona" class="btn btn-warning btn-sm">Kembali</a>
    </div>
</div>
</form>
<?= $this->MenuHelper()->headeratas_end(); ?> 

<script type="text/javascript">
    fr_tanggal("#tglawal_zona");           
    fr_tanggal("#tglakhir_zona");  
                       
    


</script>