<div class="tab-pane active" id="tab1">
    <div class="row">
        <div class="col-sm-2">
            <select class="form-control input-sm" id="combocaribelum" onchange="calldatagridbelumditetapkan()">
                <option value="">Pilih Pencarian</option>
                <option value="t_tgldaftar">Tanggal Daftar</option>
                <option value="t_nama">Nama</option>
                <option value="t_alamat">Alamat</option>
                <option value="s_namakel">Kelurahan</option>
                <option value="s_namakec">Kecamatan</option>
                <option value="t_alamatpasar">Alamat Pasar</option>
            </select>
        </div>
        <div class="col-sm-3">
            <div class="input-group input-group-sm">
                <input type="text" placeholder="Cari" class="form-control pull-right" name="kolomcaribelum" id="kolomcaribelum" onkeyup="calldatagridbelumditetapkan()">
                <div class="input-group-btn combooperatorbelumc">
                    <select data-toggle="dropdown" class="btn btn-default dropdown-toggle" id="combooperatorbelum" onchange="calldatagridbelumditetapkan()" style="text-align: left;">
                        <option value="">Pilih</option>
                        <option value="carisama">=</option>
                        <option value="carilike">%</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-sm-3"></div>
        <div class="col-sm-2">
            <span class="hiddene">
                <select class="form-control input-sm" id="combosortingbelum" onchange="calldatagridbelumditetapkan()">
                    <option value="">Pilih Urutan</option>
                    <option value="t_tgldaftar">Tanggal Daftar</option>
                    <option value="t_nama">Nama</option>
                    <option value="t_alamat">Alamat</option>
                    <option value="s_namakel">Kelurahan</option>
                    <option value="s_namakec">Kecamatan</option>
                    <option value="t_alamatpasar">Alamat Pasar</option>
                </select>
            </span>
        </div>
        <div class="col-sm-2">
            <span class="hiddene">
                <div class="form-inline">
                    <div class="radio">
                        <label>
                            <input type="radio" value="ASC" id="sortascbelum" name="sortere" onclick="calldatagridbelumditetapkan()">
                            Terkecil
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" checked="" value="DESC" id="sortdescbelum" name="sortere" onclick="calldatagridbelumditetapkan()">
                            Terbesar
                        </label>
                    </div>
                </div>
            </span>
        </div>
    </div>
    <div class="example-box-wrapper">
        <div class="remove-columns">
            <table class="table table-condensed table-bordered cf" style="font-size: 11px;">
                <thead class="cf" style="background-color: blue">
                    <tr class="bg-blue">
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            No.
                        </th>        
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            No. Urut
                        </th>             
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            Nama
                        </th> 
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            Alamat Pasar
                        </th>         
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            Jenis Tempat Usaha
                        </th>        
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            Tgl. Pembayaran
                        </th>        
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            Jumlah Pembayaran Pokok
                        </th>       
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            #
                        </th> 
                    </tr>
                </thead>
                <tbody id="body_gridbelum">
                </tbody>
                <tfoot>              
                    <tr>
                        <td colspan="8" class="text-center">
                            <div class="row">
                                <div class="col-sm-3 text-left">
                                    <span class="hiddene">
                                        <select id="rowsbelum" class="form-control" style="width: 30%" onchange="calldatagridbelumditetapkan(1)">
                                            <option value="10">10</option>
                                            <option value="20">20</option>
                                            <option value="30">30</option>
                                            <option value="40">40</option>
                                            <option value="50">50</option>
                                        </select>
                                    </span>
                                </div>
                                <div class="col-sm-6" style="text-align: center">
                                    <center>
                                        <div id="paginatorebelum"></div>
                                        <input type="hidden" id="pagebelum" value="1">
                                    </center>
                                </div>
                                <div class="col-sm-3 text-right">
                                    <span class="hiddene">
                                        <p>
                                            <b><span id="awaldatabelum"></span>-<span id="akhirdatabelum"></span>/<span id="total_databelum"></span> Data</b>
                                        </p>  
                                    </span>
                                </div>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        calldatagridbelumditetapkan();
    });

    function calldatagridbelumditetapkan(direction) {
        if ($("#combocaribelum").val().length == 0)
            par1 = undefined;
        else
            par1 = $("#combocaribelum").val()
        if ($("#kolomcaribelum").val().length == 0)
            par2 = undefined;
        else
            par2 = $("#kolomcaribelum").val()
        if ($("#combosortingbelum").val().length == 0)
            par3 = undefined;
        else
            par3 = $("#combosortingbelum").val()
        if (document.getElementById("sortascbelum").checked)
            par4 = $("#sortascbelum").val()
        else
            par4 = undefined;
        if (document.getElementById("sortdescbelum").checked)
            par5 = $("#sortdescbelum").val()
        else
            par5 = undefined;
        if ($("#combooperatorbelum").val().length == 0)
            par6 = undefined;
        else
            par6 = $("#combooperatorbelum").val()
        datagridbelum($("#pagebelum").val(), $("#rowsbelum").val(), direction, par1, par2, par3, par4, par5, par6);
    }

    function datagridbelum(pagebelum, row, direction, par1, par2, par3, par4, par5, par6) {
        $.get('<?= $this->url() ?>/dataGridBelum/'+ pagebelum + '/' + row + '/' + direction + '/' + par1 + '/' + par2 + '/' + par3 + '/' + par4 + '/' + par5 + '/' + par6, function (data) {
            var aa = JSON.parse(data)
            $("#body_gridbelum").html(aa.gridbelum);
            $("#rowsbelum").val(aa.rowsbelum);
            $("#pagebelum").val(aa.pagebelum);
            $("#total_databelum").html(": " + aa.countbelum);
            $("#total_halamanbelum").html(": " + aa.total_halamanbelum);
            $("#paginatorebelum").html(aa.paginatorebelum);
            $("#awaldatabelum").html(aa.awaldatabelum);
            $("#akhirdatabelum").html(aa.akhirdatabelum);
        });
    }

    function bukaPenetapanMasal() {
        $('#modalCetakIzin').modal('show');
    }

    function tutupPenetapanMasal() {
        $('#modalCetakIzin').modal('hide');
    }

    function tetapkanMasal() {
        window.open('<?= $this->url() ?>/tetapkanMasal?tglcetakIzin=' + $("#tglcetakIzin").val() + "&tglIzin0=" + $("#tglIzin0").val() + "&tglIzin1=" + $("#tglIzin1").val() + "&id_jenis_ijin=" + $("#id_jenis_ijin").val() + "&id_kecamatan=" + $("#id_kecamatan").val() + "&id_kelurahan=" + $("#id_kelurahan").val() + "&tipeizin=" + $("#tipeizin").val() + "&inputoffline=" + $("#inputoffline").val());
    }
</script>
<style type="text/css">
    .combooperatorbelumc select {
        border: 0 !important;  /*Removes border*/
        -webkit-appearance: none;  /*Removes default chrome and safari style*/
        -moz-appearance: none; /* Removes Default Firefox style*/
        appearance:none;
        /*background: #E08E0B url(img/select-arrow.png) no-repeat 90% center;*/
        background: #E08E0B no-repeat 90% center;
        text-indent: 0.01px; /* Removes default arrow from firefox*/
        color: #FFF;
    }	
</style>
