<?php
$frm = $this->frm;
$frm->setAttribute('action', $this->url() . '/tambah');
$frm->setAttribute('id', "formtambah");
$frm->prepare();
?>
<div id="page-content-wrapper">
    <div id="page-content">
        <div class="">
            <!-- Parsley -->
            <div id="page-title">
                <h2>
                    Setting Kelurahan
                </h2>
            </div>
            <div class="panel">
                <div class="panel-body">
                    <div class="example-box-wrapper">         
                        <div>
                            <?= $this->form()->openTag($frm) ?>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Nama Kecamatan</label>
                                <div class="col-md-4">
                                    <?= $this->formRow($frm->get('s_idkeckel')) ?> 
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Kode Kelurahan/Desa</label>
                                <div class="col-md-4">
                                    <?= $this->formHidden($frm->get('s_idkel')) ?>  
                                    <?= $this->formRow($frm->get('s_kodekel')) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Nama Kelurahan/Desa</label>
                                <div class="col-md-4">
                                    <?= $this->formRow($frm->get('s_namakel')) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label"></label>
                                <div class="col-md-4">
                                    <?= $this->formInput($frm->get('simpan')) ?> 
                                    <a href="<?= $this->url('setting_kelurahan') ?>" class="btn btn-warning btn-sm">Kembali</a>
                                </div>
                            </div>
                            <?= $this->form()->closeTag($frm) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>