<html>
    <body>
        <?php
        ini_set("max_execution_time", 5000);
        ini_set('memory_limit', '1024M');
        ?>
        <div>
            <div>
                <div style='width: 10%; float: left;'>
                </div>
                <div style='width: 90%; float: right;'>
                    <p style="text-align: center; font-size: 10pt; font-weight: BOLD;">
                        PEMERINTAH <?= strtoupper($ar_pemda->s_namakabkota); ?>, <?= strtoupper($ar_pemda->s_namaprov); ?>
                    </p>
                    <p style="text-align: center; font-size: 12pt; font-weight: BOLD; line-height: 1px;">
                        <?= strtoupper($ar_pemda->s_namainstansi); ?> (<?= strtoupper($ar_pemda->s_namasingkatinstansi); ?>)
                    </p>
                    <p style="text-align: center; font-size: 8pt; line-height: 5px">
                        <?= strtoupper($ar_pemda->s_alamatinstansi); ?> Telp/Fax <?= $ar_pemda->s_notelinstansi ?>, <?= $ar_pemda->s_namaibukotakabkota ?> <?= $ar_pemda->s_kodepos ?>
                    </p>
                </div>
                <div style='clear:both;'></div>
            </div>
            <hr style="line-height: 1px; color: black">
            <h4 style="text-align: center">DAFTAR PENETAPAN</h4>
            <p style="font-size: 10pt; line-height: 5px"> 
                Tanggal : <?= $tglpenetapan0 ?> s/d <?= $tglpenetapan1 ?>
            </p>
            <table width="100%" class="font_sembilan">
                <tr style="text-align: center">
                    <td class="border_atas border_bawah border_kanan border_kiri">
                        No.
                    </td>
                    <td>
                        Nama
                    </td>
                    <td>
                        Alamat
                    </td>
                    <td>
                        Bangunan
                    </td>
                    <td>
                        Nomor
                    </td>
                    <td>
                        Alamat Pasar
                    </td>
                    <td>
                        Panjang/Lebar
                    </td>
                    <td>
                        Jenis Usaha
                    </td>
                    <td>
                        Jenis Tempat Usaha
                    </td>
                </tr>
                <?php
                $counter = 1;
                foreach ($this->data as $k => $v) {
                    ?>
                    <tr style="text-align: center">
                        <td>
                            <?= $counter ?>
                        </td>
                        <td>
                            <?= $v['t_nama'] ?>
                        </td>
                        <td align="left">
                            <?= $v['t_alamat'] ?> Kel. <?= $v['s_namakel'] ?> Kec. <?= $v['s_namakec'] ?> Kab/kota <?= $v['t_kabupaten'] ?>
                        </td>
                        <td align="left">
                            <?= $v['t_bangunan'] ?>
                        </td>
                        <td align="left">
                            <?= $v['t_nomor'] ?>
                        </td>
                        <td align="left">
                            <?= $v['t_alamatpasar'] ?>
                        </td>
                        <td>
                            <?= $v['t_panjang'] ?> / <?= $v['t_lebar'] ?>
                        </td>
                        <td align="left">
                            <?= $v['t_jenisusaha'] ?>
                        </td>
                        <td align="left">
                            <?= $v['s_namatempat'] ?>
                        </td>
                    </tr>
                    <?php
                    $counter++;
                }
                ?>
            </table>
        </div>
    </body>
</html>

<style type="text/css" media="print">
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    .font_empatbelas {
        font-size: 14pt;
    }    
</style>