<style>
    .gambar {
        /*width: 100px;
  height: 50px;
  background-color: red;
  font-weight: bold;*/
        position: relative;

        /*-webkit-backface-visibility: visible;
    -ms-backface-visibility: visible;
    backface-visibility: visible;
    -webkit-animation-name: flip 5s infinite;
    animation-name: flip;
    animation: flip 5s infinite;*/

        -webkit-backface-visibility: visible !important;
        -ms-backface-visibility: visible !important;
        backface-visibility: visible !important;
        -webkit-animation-name: flipInY 5s infinite;
        animation-name: flipInY;
        animation: flipInY 5s infinite;
    }



    @keyframes shake {

        0%,
        100% {
            -webkit-transform: translateX(0);
            -ms-transform: translateX(0);
            transform: translateX(0);
        }

        10%,
        30%,
        50%,
        70%,
        90% {
            -webkit-transform: translateX(-10px);
            -ms-transform: translateX(-10px);
            transform: translateX(-10px);
        }

        20%,
        40%,
        60%,
        80% {
            -webkit-transform: translateX(10px);
            -ms-transform: translateX(10px);
            transform: translateX(10px);
        }
    }

    .shake {
        -webkit-animation-name: shake;
        animation-name: shake;
    }

    @-webkit-keyframes flip {
        0% {
            -webkit-transform: perspective(400px) translateZ(0) rotateY(0) scale(1);
            transform: perspective(400px) translateZ(0) rotateY(0) scale(1);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }

        40% {
            -webkit-transform: perspective(400px) translateZ(150px) rotateY(170deg) scale(1);
            transform: perspective(400px) translateZ(150px) rotateY(170deg) scale(1);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }

        50% {
            -webkit-transform: perspective(400px) translateZ(150px) rotateY(190deg) scale(1);
            transform: perspective(400px) translateZ(150px) rotateY(190deg) scale(1);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }

        80% {
            -webkit-transform: perspective(400px) translateZ(0) rotateY(360deg) scale(.95);
            transform: perspective(400px) translateZ(0) rotateY(360deg) scale(.95);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }

        100% {
            -webkit-transform: perspective(400px) translateZ(0) rotateY(360deg) scale(1);
            transform: perspective(400px) translateZ(0) rotateY(360deg) scale(1);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
    }

    @keyframes flip {
        0% {
            -webkit-transform: perspective(400px) translateZ(0) rotateY(0) scale(1);
            -ms-transform: perspective(400px) translateZ(0) rotateY(0) scale(1);
            transform: perspective(400px) translateZ(0) rotateY(0) scale(1);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }

        40% {
            -webkit-transform: perspective(400px) translateZ(150px) rotateY(170deg) scale(1);
            -ms-transform: perspective(400px) translateZ(150px) rotateY(170deg) scale(1);
            transform: perspective(400px) translateZ(150px) rotateY(170deg) scale(1);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
        }

        50% {
            -webkit-transform: perspective(400px) translateZ(150px) rotateY(190deg) scale(1);
            -ms-transform: perspective(400px) translateZ(150px) rotateY(190deg) scale(1);
            transform: perspective(400px) translateZ(150px) rotateY(190deg) scale(1);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }

        80% {
            -webkit-transform: perspective(400px) translateZ(0) rotateY(360deg) scale(.95);
            -ms-transform: perspective(400px) translateZ(0) rotateY(360deg) scale(.95);
            transform: perspective(400px) translateZ(0) rotateY(360deg) scale(.95);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }

        100% {
            -webkit-transform: perspective(400px) translateZ(0) rotateY(360deg) scale(1);
            -ms-transform: perspective(400px) translateZ(0) rotateY(360deg) scale(1);
            transform: perspective(400px) translateZ(0) rotateY(360deg) scale(1);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
        }
    }

    .animated.flip {
        -webkit-backface-visibility: visible;
        -ms-backface-visibility: visible;
        backface-visibility: visible;
        -webkit-animation-name: flip;
        animation-name: flip;
    }

    @-webkit-keyframes flipInX {
        0% {
            -webkit-transform: perspective(400px) rotateX(90deg);
            transform: perspective(400px) rotateX(90deg);
            opacity: 0;
        }

        40% {
            -webkit-transform: perspective(400px) rotateX(-10deg);
            transform: perspective(400px) rotateX(-10deg);
        }

        70% {
            -webkit-transform: perspective(400px) rotateX(10deg);
            transform: perspective(400px) rotateX(10deg);
        }

        100% {
            -webkit-transform: perspective(400px) rotateX(0deg);
            transform: perspective(400px) rotateX(0deg);
            opacity: 1;
        }
    }

    @keyframes flipInX {
        0% {
            -webkit-transform: perspective(400px) rotateX(90deg);
            -ms-transform: perspective(400px) rotateX(90deg);
            transform: perspective(400px) rotateX(90deg);
            opacity: 0;
        }

        40% {
            -webkit-transform: perspective(400px) rotateX(-10deg);
            -ms-transform: perspective(400px) rotateX(-10deg);
            transform: perspective(400px) rotateX(-10deg);
        }

        70% {
            -webkit-transform: perspective(400px) rotateX(10deg);
            -ms-transform: perspective(400px) rotateX(10deg);
            transform: perspective(400px) rotateX(10deg);
        }

        100% {
            -webkit-transform: perspective(400px) rotateX(0deg);
            -ms-transform: perspective(400px) rotateX(0deg);
            transform: perspective(400px) rotateX(0deg);
            opacity: 1;
        }
    }

    .flipInX {
        -webkit-backface-visibility: visible !important;
        -ms-backface-visibility: visible !important;
        backface-visibility: visible !important;
        -webkit-animation-name: flipInX;
        animation-name: flipInX;
    }

    @-webkit-keyframes flipInY {
        0% {
            -webkit-transform: perspective(400px) rotateY(90deg);
            transform: perspective(400px) rotateY(90deg);
            opacity: 0;
        }

        40% {
            -webkit-transform: perspective(400px) rotateY(-10deg);
            transform: perspective(400px) rotateY(-10deg);
        }

        70% {
            -webkit-transform: perspective(400px) rotateY(10deg);
            transform: perspective(400px) rotateY(10deg);
        }

        100% {
            -webkit-transform: perspective(400px) rotateY(0deg);
            transform: perspective(400px) rotateY(0deg);
            opacity: 1;
        }
    }

    @keyframes flipInY {
        0% {
            -webkit-transform: perspective(400px) rotateY(90deg);
            -ms-transform: perspective(400px) rotateY(90deg);
            transform: perspective(400px) rotateY(90deg);
            opacity: 0;
        }

        40% {
            -webkit-transform: perspective(400px) rotateY(-10deg);
            -ms-transform: perspective(400px) rotateY(-10deg);
            transform: perspective(400px) rotateY(-10deg);
        }

        70% {
            -webkit-transform: perspective(400px) rotateY(10deg);
            -ms-transform: perspective(400px) rotateY(10deg);
            transform: perspective(400px) rotateY(10deg);
        }

        100% {
            -webkit-transform: perspective(400px) rotateY(0deg);
            -ms-transform: perspective(400px) rotateY(0deg);
            transform: perspective(400px) rotateY(0deg);
            opacity: 1;
        }
    }

    .flipInY {
        -webkit-backface-visibility: visible !important;
        -ms-backface-visibility: visible !important;
        backface-visibility: visible !important;
        -webkit-animation-name: flipInY;
        animation-name: flipInY;
    }

    @-webkit-keyframes flipOutX {
        0% {
            -webkit-transform: perspective(400px) rotateX(0deg);
            transform: perspective(400px) rotateX(0deg);
            opacity: 1;
        }

        100% {
            -webkit-transform: perspective(400px) rotateX(90deg);
            transform: perspective(400px) rotateX(90deg);
            opacity: 0;
        }
    }

    @keyframes flipOutX {
        0% {
            -webkit-transform: perspective(400px) rotateX(0deg);
            -ms-transform: perspective(400px) rotateX(0deg);
            transform: perspective(400px) rotateX(0deg);
            opacity: 1;
        }

        100% {
            -webkit-transform: perspective(400px) rotateX(90deg);
            -ms-transform: perspective(400px) rotateX(90deg);
            transform: perspective(400px) rotateX(90deg);
            opacity: 0;
        }
    }

    .flipOutX {
        -webkit-animation-name: flipOutX;
        animation-name: flipOutX;
        -webkit-backface-visibility: visible !important;
        -ms-backface-visibility: visible !important;
        backface-visibility: visible !important;
    }

    @-webkit-keyframes flipOutY {
        0% {
            -webkit-transform: perspective(400px) rotateY(0deg);
            transform: perspective(400px) rotateY(0deg);
            opacity: 1;
        }

        100% {
            -webkit-transform: perspective(400px) rotateY(90deg);
            transform: perspective(400px) rotateY(90deg);
            opacity: 0;
        }
    }

    @keyframes flipOutY {
        0% {
            -webkit-transform: perspective(400px) rotateY(0deg);
            -ms-transform: perspective(400px) rotateY(0deg);
            transform: perspective(400px) rotateY(0deg);
            opacity: 1;
        }

        100% {
            -webkit-transform: perspective(400px) rotateY(90deg);
            -ms-transform: perspective(400px) rotateY(90deg);
            transform: perspective(400px) rotateY(90deg);
            opacity: 0;
        }
    }

    .flipOutY {
        -webkit-backface-visibility: visible !important;
        -ms-backface-visibility: visible !important;
        backface-visibility: visible !important;
        -webkit-animation-name: flipOutY;
        animation-name: flipOutY;
    }
</style>

<div id="page-content-wrapper">
    <div id="page-content" style="background-color: #DFF0D8">
        <?php if ($datauser['s_akses'] != 9) { ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel">
                        <div class="panel-body" style="background: url('<?= $this->basePath() ?>/public/upload/bg1.jpg'); 
                             min-height: 250px;
                             background-repeat: no-repeat; 
                             /* background-size: auto 310px; */
                             background-position: right;">
                            <div class="example-box-wrapper" style=" margin-top: 80px;">
                                <div class="tab-content">
                                    <div class="col-sm-1">
                                        <div class="clearfix gambar" align="center">
                                            <img src="<?= $data_pemda->s_logo ?>" alt="" width="80px">
                                        </div>
                                    </div>
                                    <div class="col-sm-10">
                                        <div class="clearfix">
                                            <span style="font-size: 20px; color: white; text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;">
                                                <b><?= strtoupper($data_pemda->s_namaprov) ?><br>
                                                    PEMERINTAH KABUPATEN <?= strtoupper($data_pemda->s_namakabkota) ?>
                                                </b>
                                            </span>
                                            <br>
                                            <span style="font-size: 16px; color: white; text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;"><b><?= strtoupper($data_pemda->s_namainstansi) ?> (<?= $data_pemda->s_namasingkatinstansi ?>)</b></span>
                                            <br>
                                            <span style="color: white; text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;"><?= $data_pemda->s_alamatinstansi ?> Telp/Fax <?= $data_pemda->s_notelinstansi ?>, <?= $data_pemda->s_namaibukotakabkota ?></span>
                                            <br>
                                            <!--<span style="color: white; text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;">Website : <a href="<= $data_pemda->s_website ?>" target="_blank"><= $data_pemda->s_website ?></a></span>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
        <?php if ($datauser['s_akses'] == 2 || $datauser['s_akses'] == 3 || $datauser['s_akses'] == 6 || $datauser['s_akses'] == 8 || $datauser['s_akses'] ==10 || $datauser['s_akses'] == 12) { ?>
            <div class="example-box-wrapper">
                <div class="row">
                    <div class="col-md-3">
                        <div class="tile-box tile-box-alt bg-primary">
                            <div class="tile-header">
                                Pendaftaran
                            </div>
                            <div class="tile-content-wrapper">
                                <i class="glyph-icon icon-edit"></i>
                                <div class="tile-content">
                                    <?= $jmlpendaftaran ?>
                                </div>
                                <small>
                                    Tahun <?= date('Y'); ?> : <?= $jmlpendaftarantahun ?>
                                </small>
                            </div>
                            <a href="<?= $this->url('pendaftaran') ?>" class="tile-footer tooltip-button" data-placement="bottom" title="klik untuk ke daftar pendaftaran!">
                                lihat detail
                                <i class="glyph-icon icon-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="tile-box tile-box-alt bg-facebook">
                            <div class="tile-header">
                                Pendataan
                            </div>
                            <div class="tile-content-wrapper">
                                <i class="glyph-icon icon-pencil"></i>
                                <div class="tile-content">
                                    <?= $jmlpendataan ?>
                                </div>
                                <small>
                                    Tahun <?= date('Y'); ?> : <?= $jmlpendataantahun ?>
                                </small>
                            </div>
                            <a href="<?= $this->url('pendataan') ?>/1" class="tile-footer tooltip-button" data-placement="bottom" title="klik untuk ke daftar pendataan!">
                                lihat detail
                                <i class="glyph-icon icon-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="tile-box tile-box-alt bg-warning">
                            <div class="tile-header">
                                Penetapan
                            </div>
                            <div class="tile-content-wrapper">
                                <i class="glyph-icon icon-check"></i>
                                <div class="tile-content">
                                    <?= $jmlpenetapan ?>
                                </div>
                                <small>
                                    Tahun <?= date('Y'); ?> : <?= $jmlpenetapantahun ?>
                                </small>
                            </div>
                            <a href="<?= $this->url('penetapan') ?>" class="tile-footer tooltip-button" data-placement="bottom" title="klik untuk ke daftar penetapan!">
                                lihat detail
                                <i class="glyph-icon icon-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="tile-box tile-box-alt bg-danger">
                            <div class="tile-header">
                                Pembayaran
                            </div>
                            <div class="tile-content-wrapper">
                                <i class="glyph-icon icon-dollar"></i>
                                <div class="tile-content">
                                    <?= $jmlpembayaran ?>
                                </div>
                                <small>
                                    Tahun <?= date('Y'); ?> : <?= $jmlpembayarantahun ?>
                                </small>
                            </div>
                            <a href="<?= $this->url('pembayaran') ?>" class="tile-footer tooltip-button" data-placement="bottom" title="klik untuk ke daftar pembayaran!">
                                lihat detail
                                <i class="glyph-icon icon-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default hidden-xs">
                <div class="panel-body">
                    <div class="row form-horizontal">
                        <div class="col-sm-2">
                            <select class="form-control input-sm" id="textcari" onchange="calldatagridmonitoring()">
                                <?php
                                $datenow = date('Y');
                                $date2 = date('Y') - 4;
                                for ($i = $datenow; $i >= $date2; $i--) {
                                    echo '<option value="' . $i . '"' . ($i == $datenow ? ' selected="selected"' : '') . '>' . $i . '</option>';
                                ?>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <table>
                                <tr>
                                    <td colspan="28">
                                        <b style="color: red; font-size: 12px;">K = Ketetapan</b><br>
                                        <b style="color: blue; font-size: 12px">P = Pembayaran</b>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <br />
                    <div class="example-box-wrapper">
                        <div class="remove-columns">
                            <div style="overflow: auto">
                                <table class="table table-striped table-condensed table-bordered table-responsive" style="font-size: 11px; color: black">
                                    <thead class="cf" style="background-color: blue">
                                        <tr class="bg-blue">
                                            <th style="background-color: #00BCA4; color: black; text-align: center;vertical-align:middle;" rowspan="2">
                                                NAMA PAJAK
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center;" colspan="2">
                                                Januari
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center;" colspan="2">
                                                Februari
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center;" colspan="2">
                                                Maret
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center" colspan="2">
                                                April
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center" colspan="2">
                                                Mei
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center" colspan="2">
                                                Juni
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center" colspan="2">
                                                Juli
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center" colspan="2">
                                                Agustus
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center" colspan="2">
                                                September
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center" colspan="2">
                                                Oktober
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center" colspan="2">
                                                Nopember
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center" colspan="2">
                                                Desember
                                            </th>
                                            <th style="background-color: #00BCA4; color: black; text-align: center" colspan="2">
                                                TOTAL
                                            </th>
                                            <th style="background-color: #00BCA4; color: black; text-align: center;vertical-align:middle;" rowspan="2">
                                                PIUTANG
                                            </th>
                                        </tr>
                                        <tr>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: white; text-align: center">
                                                P
                                            </th>
                                            <th style="background-color: #00BCA4; color: RED; text-align: center">
                                                K
                                            </th>
                                            <th style="background-color: #00BCA4; color: BLUE; text-align: center">
                                                P
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody id="body_grid">
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>

    </div>
</div>

<style>
    th {
        font-weight: bolder;
    }

    td:nth-child(odd) {
        color: blue;
    }

    td:nth-child(even) {
        color: red;
    }

    td:nth-child(1) {
        color: black;
    }

    .totalrow td {
        font-weight: bolder;
    }

    td.piutang {
        color: black;
    }
</style>
<?php if ($datauser['s_akses'] == 2 || $datauser['s_akses'] == 3 || $datauser['s_akses'] == 8 || $datauser['s_akses'] ==10 || $datauser['s_akses'] == 12) { ?>
    <script type="text/javascript">
        $(function() {
            calldatagridmonitoring();
        });

        function calldatagridmonitoring(direction) {
            if ($("#textcari").val().length == 0)
                par1 = undefined;
            else
                par1 = $("#textcari").val()
            datagridmonitoring(par1);
        }

        function datagridmonitoring(par1) {
            $.get('<?= $this->url() ?>/dataGrid/' + par1, function(data) {
                var aa = JSON.parse(data)
                $("#body_grid").html(aa.grid);
            });
        }
    </script>
<?PHP } ?>