<html>

<head>
    <style type="text/css" media="print">
        table,
        th,
        td {
            border: 1px solid black;
            border-collapse: collapse;
        }

        .mengetahui {
            border: 1px solid #fff;
            border-collapse: collapse;
            margin-top: 10px;
            font-family: sans-serif;
        }

        .font_empatbelas {
            font-size: 14pt;
        }

        @page {
            margin: 30px 50px 50px 30px;
            odd-header-name: html_MyHeader1;
            odd-footer-name: html_MyFooter1;
        }
    </style>
</head>

<body>
    <?php
    if ($formatcetak == 'excel') {
        header("Content-type: application/vnd-ms-excel");
        header("Content-Disposition: attachment; filename=cetakpendaftaranwp.xls");
    }

    ini_set("max_execution_time", 5000);
    ini_set('memory_limit', '1024M');
    if ($statuswp == 'true') {
        $status_wp = '(AKTIF)';
    } elseif ($statuswp == 'false') {
        $status_wp = '(TIDAK AKTIF)';
    } else {
        $status_wp = '';
    }

    if ($jenispendaftaran == 'P') {
        $jenis_pendaftaran = 'PAJAK';
    } elseif ($jenispendaftaran == 'R') {
        $jenis_pendaftaran = 'RETRIBUSI';
    } else {
        $jenis_pendaftaran = 'PAJAK DAN RETRIBUSI';
    }
    $namabulan_text = [
        "Januari",
        "Februari",
        "Maret",
        "April",
        "Mei",
        "Juni",
        "Juli",
        "Agustus",
        "September",
        "Oktober",
        "November",
        "Desember"
    ];
    ?>
    <div style='width: 100%;font-family:sans-serif;'>
        <p style="text-align: center;">
            <strong style=" font-size: 10pt; ">PEMERINTAH KABUPATEN <?= strtoupper($ar_pemda->s_namakabkota); ?></strong><br>
            <strong style=" font-size: 12pt; "><?= strtoupper($ar_pemda->s_namainstansi); ?></strong><br>
            <span style="font-size:8pt"><?= strtoupper($ar_pemda->s_alamatinstansi); ?> Telp/Fax <?= $ar_pemda->s_notelinstansi ?>, <?= $ar_pemda->s_namaibukotakabkota ?> <?= $ar_pemda->s_kodepos ?></span>
        </P>
    </div>
    <hr style="color: black">
    <h4 style="font-family:sans-serif;text-align: center">DATA PENDAFTARAN WAJIB <?= $jenis_pendaftaran ?> <?= $status_wp ?></h4>
    <p style="font-size: 10pt; font-family:sans-serif; line-height: 5px">
        Tanggal Daftar: <?= $tgldaftar0 ?> s/d <?= $tgldaftar1 ?>
    </p>
    <table width="100%" cellpadding="4" style="font-family:sans-serif;" border="1">
        <tr style="text-align: center;background:#dedfe0;">
            <th>No.</th>
            <th>NPWPD</th>
            <th>NAMA</th>
            <th>ALAMAT</th>
            <th>NO. TELP</th>
            <th>EMAIL</th>
        </tr>
        <?php
        $counter = 1;
        foreach ($data as $k => $v) {
            if ($v['t_kecamatan'] == 0) {
                $kecamatan = $v['kecamatanluarwp'];
                $kelurahan = $v['kelurahanluarwp'];
            } else {
                $kecamatan = $v['s_namakec'];
                $kelurahan = $v['s_namakel'];
            }
        ?>
            <tr>
                <td style="text-align: center;vertical-align:top;">
                    <?= $counter ?>
                </td>
                <td style="vertical-align:top;">
                    <?= $v['t_npwpd'] ?>
                </td>
                <td style="vertical-align:top;">
                    <?= $v['t_nama'] ?>
                </td>
                <td style="vertical-align:top;">

                    <?= strtoupper($v['t_alamat']) ?>, RT. <?= strtoupper($v['t_rt']) ?> , RW. <?= strtoupper($v['t_rw']) ?> , DESA <?= strtoupper($kelurahan) ?>, KEC. <?= strtoupper($kecamatan) ?>, KAB. <?= strtoupper($v['t_kabupaten']) ?>
                </td>
                <td style="vertical-align:top;">
                    <?= $v['t_notelp'] ?>
                </td>
                <td style="vertical-align:top;">
                    <?= $v['t_email'] ?>
                </td>
            </tr>
        <?php
            $counter++;
        }
        ?>
    </table>
    <?php
    if ($formatcetak == 'pdf') {
    ?>
        <table width="100%" class="mengetahui">
            <tr class="mengetahui">
                <td style=" width: 35%; text-align: center;vertical-align: bottom;" class="mengetahui">
                    Mengetahui<br>
                    <?= $ar_mengetahui->s_jabatanpej ?>
                    <br><br><br><br><br><br><br>
                    <u><b><?= $ar_mengetahui->s_namapej ?></b></u><br>
                    NIP <?= $ar_mengetahui->s_nippej ?>
                </td>
                <td style=" width: 30%" class="mengetahui"></td>
                <td style=" width: 35%;text-align: center;vertical-align: bottom;" class="mengetahui">
                    <?= $ar_pemda->s_namaibukotakabkota . ', ' . date('d', strtotime($tglcetak)) . " " . $namabulan_text[date('m', strtotime($tglcetak)) - 1] . " " . date('Y', strtotime($tglcetak)) ?>
                    <br>
                    Diperiksa Oleh<br>
                    <?= $ar_diperiksa->s_jabatanpej ?>
                    <br><br><br><br><br><br><br>
                    <u><b><?= $ar_diperiksa->s_namapej ?></b></u><br>
                    NIP <?= $ar_diperiksa->s_nippej ?>
                </td>
            </tr>
        </table>
        <htmlpagefooter name="MyFooter1">
            <table width="100%" style="vertical-align: bottom; font-family: serif; font-size: 8pt;
                   color: #000000; font-weight: bold; font-style: italic;border: 1px solid;">
                <tr>
                    <!--<td width="33%"><span style="font-weight: bold; font-style: italic;">{DATE j-m-Y}</span></td>-->
                    <td style="font-style: italic;text-align: left;font-size: 10px;border: 1px solid #fff;" width="50%">Printed by SIMPATDA</td>
                    <td style="font-style: italic;text-align: right;font-size: 11px;border: 1px solid #fff;" width="50%">Halaman {PAGENO} dari {nbpg}</td>
                </tr>
            </table>
        </htmlpagefooter>
    <?php
    }
    ?>
</body>

</html>