<?php
$form = $this->form;
$form->setAttribute('action', $this->url() . '/form_pemeriksaanskpdkbt');
$form->setAttribute("id", "demo-form");
$form->setAttribute("class", "form-horizontal pad15L pad15R pad15T");
$form->setAttribute("data-parsley-validate", "data-parsley-validate");
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();
?>
<div id="page-content-wrapper">
    <div id="page-content">
        <div class="">
            <!-- Parsley -->
            <div>
                <h3 style="color: blue">
                    Pemeriksaan SKPDKBT &nbsp; -- <b style="color: red"> NO SPTPD : <?= $datatransaksi['t_nourut'] . " / " . $datatransaksi['t_periodepajak']; ?></b> --
                </h3>
            </div>
            <div class="panel">
                <div class="panel-body">
                    <div class="example-box-wrapper">
                        <?= $this->form()->openTag($form) ?>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="alert alert-info">
                                    <div class="alert-content">
                                        <h4 class="alert-title"><b style="color: #000099">Data Pemilik</b></h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2">Tanggal Pendaftaran</label>
                                <div class="col-md-2">
                                    : <?= $datatransaksi['t_tgldaftar'] ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2">Nama</label>
                                <div class="col-md-4">
                                    : <?= $datatransaksi['t_nama'] ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2">Alamat</label>
                                <div class="col-md-10">
                                    : <?= $datatransaksi['t_alamat'] ?>
                                    ,Desa/Kel. <?= $datatransaksi['s_namakel'] ?>
                                    ,Kec. <?= $datatransaksi['s_namakec'] ?>
                                    ,Kab. <?= $datatransaksi['t_kabupaten'] ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="alert alert-info">
                                    <div class="alert-content">
                                        <h4 class="alert-title"><b style="color: #000099">Data Objek Pajak</b></h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2">NIOP</label>
                                <div class="col-sm-4">
                                    : <?= $datatransaksi['t_nop'] ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2">Nama</label>
                                <div class="col-sm-4">
                                    : <?= $datatransaksi['t_namaobjek'] ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2">Alamat</label>
                                <div class="col-sm-10">
                                    : <?= $datatransaksi['t_alamatobjek'] ?>
                                    ,Desa/Kel. <?= $datatransaksi['s_namakelobjek'] ?>
                                    ,Kec. <?= $datatransaksi['s_namakecobjek'] ?>
                                    ,Kab. <?= $datatransaksi['t_kabupatenobjek'] ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="alert alert-info">
                                    <div class="alert-content">
                                        <h4 class="alert-title"><b style="color: #000099">Data Transaksi</b></h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2">Tgl. Pendataaan</label>
                                <div class="col-sm-4">
                                    : <?= date('d-m-Y', strtotime($datatransaksi['t_tglpendataan'])) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2">No. SPTPD</label>
                                <div class="col-sm-4">
                                    : <?= $datatransaksi['t_nourut']; ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2">Masa Pajak</label>
                                <div class="col-sm-4">
                                    : <?= date('d-m-Y', strtotime($datatransaksi['t_masaawal'])) ?> s/d <?= date('d-m-Y', strtotime($datatransaksi['t_masaakhir'])) ?>
                                </div>
                            </div>
                        </div>
                        <div class="row pad10B">
                            <div class="col-sm-12">
                                <div class="alert alert-warning">
                                    <div class="alert-content">
                                        <h4 class="alert-title"><b style="color: #000099">Data SKPDKBT</b></h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">No. SKPDKBT</label>
                                <div class="col-md-2">
                                    <?= $this->formHidden($form->get("t_idskpdkbt")) ?>
                                    <?= $this->formHidden($form->get("t_idtransaksi")) ?>
                                    <?= $this->formText($form->get("t_noskpdkbt")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Periode SKPDKBT</label>
                                <div class="col-md-1">
                                    <?= $this->formText($form->get("t_periodeskpdkbt")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Kode Rekening</label>
                                <div class="col-md-2">
                                    <input type="text" class="form-control" readonly="true" value="<?= $datatransaksi['korek'] ?>">
                                </div>
                                <label class="col-sm-2 control-label"></label>
                                <label class="col-sm-2 control-label">Nama Rekening</label>
                                <div class="col-md-4">
                                    <input type="text" class="form-control" readonly="true" value="<?= $datatransaksi['s_namakorek'] ?>">
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Tanggal SKPDKBT</label>
                                <div class="col-md-2">
                                    <div class="input-prepend input-group">
                                        <span class="add-on input-group-addon">
                                            <i class="glyph-icon icon-calendar"></i>
                                        </span>

                                        <?= $this->formText($form->get("t_tglskpdkbt")) ?>
                                    </div>
                                </div>
                                <label class="col-sm-3 control-label"></label>
                                <label class="col-sm-3 control-label">Tanggal SKPDKB</label>
                                <div class="col-md-2">
                                    <input type="text" id="t_tglskpdkb" value="<?= date('d-m-Y', strtotime($datatransaksi["t_tglskpdkb"])) ?>" class="form-control" readonly="true" style="text-align:right; background:green; color: white; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder">
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Dasar Pengenaan (Pemeriksaan)</label>
                                <div class="col-md-4">
                                    <?= $this->formText($form->get("t_dasarrevisi")) ?>
                                </div>
                                <label class="col-sm-2 control-label">Dasar Pengenaan (Sebelumnya)</label>
                                <div class="col-md-4">
                                    <input type="text" id="t_dasarrevisiskpdkb" value="<?= number_format($datatransaksi["t_dasarrevisiskpdkb"], 0, ',', '.') ?>" class="form-control" readonly="true" style="text-align:right; background:green; color: white; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder">
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Selisih Dasar</label>
                                <div class="col-md-4">
                                    <?= $this->formText($form->get("t_selisihdasar")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Jml. Bulan</label>
                                <div class="col-md-1">
                                    <?= $this->formText($form->get("t_jmlhbln")) ?>
                                </div>
                                <label class="col-sm-2 control-label">Denda (%)</label>
                                <div class="col-md-1">
                                    <?= $this->formText($form->get("t_tarifpersen")) ?>
                                </div>
                                <label class="col-sm-3 control-label"></label>
                                <label class="col-sm-2 control-label">Tarif (%)</label>
                                <div class="col-md-1">
                                    <?= $this->formText($form->get("t_tarifpajak")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">(Pajak Seharusnya)</label>
                                <div class="col-md-4">
                                    <?= $this->formText($form->get("t_jmlhpajakseharusnya")) ?>
                                </div>
                                <label class="col-sm-2 control-label">- (Pajak Sebelumnya)</label>
                                <div class="col-md-4">
                                    <input type="text" id="t_jmlhpajakskpdkb" value="<?= number_format($datatransaksi['t_jmlhpajakskpdkb'], 0, ',', '.') ?>" class="form-control" readonly="true" style="text-align:right; background:green; color: white; padding: 7px 10px; height:40px; font-size: 16px; font-weight:bolder">
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Pajak</label>
                                <div class="col-md-4">
                                    <?= $this->formText($form->get("t_jmlhpajakskpdkbt")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Denda</label>
                                <div class="col-md-4">
                                    <?= $this->formText($form->get("t_jmlhdendaskpdkbt")) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Total</label>
                                <div class="col-md-4">
                                    <?= $this->formText($form->get("t_totalskpdkbt")) ?>
                                </div>
                                <div class="col-md-1">
                                    <a href="javascript:void(0)" class="btn btn-primary btn-sm" onclick="hitungskpdkbt()"> <span class="glyphicon glyph-icon icon-calculator"></span> Hitung</a>
                                </div>
                            </div>
                        </div>
                        <div class="bg-default" id="tombolsimpan">
                            <?= $this->formInput($form->get('Pembayaransubmit')) ?> 
                        </div>
                        <?= $this->form()->closeTag($form) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function hitungskpdkbt() {
        $.post('<?= $this->url() ?>/hitungskpdkbt', {t_dasarrevisi: $("#t_dasarrevisi").val(), t_dasarrevisiskpdkb: $("#t_dasarrevisiskpdkb").val(), t_tglskpdkb: $("#t_tglskpdkb").val(), t_tglskpdkbt: $("#t_tglskpdkbt").val(), t_tarifpajak : $("#t_tarifpajak").val(), t_tarifpersen : $("#t_tarifpersen").val()}, function (data) {
            var aa = JSON.parse(data);
            $('#t_selisihdasar').val(aa.t_selisihdasar);
            $('#t_jmlhbln').val(aa.t_jmlhbln);
            $('#t_jmlhdendaskpdkbt').val(aa.t_jmlhdendaskpdkbt);
            $('#t_jmlhpajakseharusnya').val(aa.t_jmlhpajakseharusnya);
            $('#t_jmlhpajakskpdkbt').val(aa.t_jmlhpajakskpdkbt);
            $('#t_totalskpdkbt').val(aa.t_totalskpdkbt);
        });
    }
</script>