<?php
$judul = '<span style="font-size: 28px;"><b>DATA AKAN JATUH TEMPO</b></span>';
$link = '';

echo $this->MenuHelper()->headeratas($judul, $link);
?>

<table id="dataakanjatuhtempo" cellpadding="0" cellspacing="0" border="0" class="display" width="100%" style="width:100%;">
    <thead>
        <tr class="bg-blue tableheader">

            <th width="15">No</th>
            <th>NPWPD</th>
            <th>NAMA PEMILIK</th>            
            <th>NAMA BADAN</th>      
            <th>NAMA OBJEK</th>       
            <th>MASA PAJAK</th>  
            <th>PERIODE</th>            
            <th>PAJAK TERHUTANG</th>      
            <th>TGL JATUH TEMPO</th> 
            <th>Perintah</th>
            <th>KODE REKENING</th>  
            <th>NAMA REKENING</th>  
            
        </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>    
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
</tfoot>
</table>
<style type="text/css">
.dataTables_filter {
     display: none;
}
</style> 
<?php
    $idtabel = '#dataakanjatuhtempo';
    $url = $this->url().'/dataGridAkanjatuhtempo';
    $jmlkolom = 11;
    $seleksi_kolom = "'9'"; //iki data sort di disabel
    $pencarian_bawah = 5;
    
?>
<?= $this->MenuHelper()->fr_datatables($this->basePath(), $idtabel, $url, $jmlkolom, $pencarian_bawah, $seleksi_kolom, null);?>


    

<?= $this->MenuHelper()->headeratas_end(); ?>

<script type="text/javascript">
    

    function bukaPenetapanMasal() {
        $('#modalCetakIzin').modal('show');
    }

    function tutupPenetapanMasal() {
        $('#modalCetakIzin').modal('hide');
    }

    function tetapkanMasal() {
        window.open('<?= $this->url() ?>/tetapkanMasal?tglcetakIzin=' + $("#tglcetakIzin").val() + "&tglIzin0=" + $("#tglIzin0").val() + "&tglIzin1=" + $("#tglIzin1").val() + "&id_jenis_ijin=" + $("#id_jenis_ijin").val() + "&id_kecamatan=" + $("#id_kecamatan").val() + "&id_kelurahan=" + $("#id_kelurahan").val() + "&tipeizin=" + $("#tipeizin").val() + "&inputoffline=" + $("#inputoffline").val());
    }
</script>

