<?php

ini_set("max_execution_time", 5000);
$t_masa1=$_GET['masaawal'];
$t_masa2=$_GET['masaakhir'];
$tgl=date('Y-m-d',strtotime($data_get['tglcetak']));

function tanggal_indo($tanggal, $cetak_hari = false)
{
	$hari = array ( 1 =>    'Senin',
				'Selasa',
				'Rabu',
				'Kamis',
				'Jumat',
				'Sabtu',
				'Minggu'
			);
			
	$bulan = array (1 =>   'Januari',
				'Februari',
				'Maret',
				'April',
				'Mei',
				'Juni',
				'Juli',
				'Agustus',
				'September',
				'Oktober',
				'November',
				'Desember'
			);
	$split 	 = explode('-', $tanggal);
	$tgl_indo = $split[2] . ' ' . $bulan[ (int)$split[1] ] . ' ' . $split[0];
	
	if ($cetak_hari) {
		$num = date('N', strtotime($tanggal));
		return $hari[$num] . ', ' . $tgl_indo;
	}
	return $tgl_indo;
}


include($_SERVER['DOCUMENT_ROOT'] . "/" . $this->basePath() . '/public/cetakan/MPDF57/mpdf.php');
$mpdf = new mPDF('utf-8', 'Legal', 0, '', 20, 10, 15, 5, 1, 1, '');
//$mpdf = new mPDF(['format' => 'Legal']);

$html = '';
$html .= '

<html>
    <head>
        <style type="text/css">
            .border_atas {
                border-top: 1px solid black;
                border-collapse: collapse;
            }

            .border_kiri {
                border-left: 1px solid black;
                border-collapse: collapse;
            }

            .border_kanan {
                border-right: 1px solid black;
                border-collapse: collapse;
            }

            .border_bawah {
                border-bottom: 1px solid black;
                border-collapse: collapse;
            }

            .font_besar {
                font-size: 12pt;
            }

            .font_kecil {
                font-size: 10pt;
            }

            .font_lima {
                font-size: 7pt;
            }

            .font_tujuh {
                font-size: 7pt;
            }  

            .font_sepuluh {
                font-size: 10pt;
            }    

            .font_sembilan {
                font-size: 9pt;
            }    
        </style>
    </head>
    <body>
        <div class="border_kanan border_atas border_kiri font_sepuluh" style="padding-top: 10px; float: left">
            <div style="width: 8%; float: left">               
                <img src="'.$_SERVER['DOCUMENT_ROOT'] . '' . $this->basePath() . '/' . $ar_pemda->s_logo.'" style="width:60px; height: 65px;"/>
            </div>
            <div style="font-size: 14px; padding: 10px; text-align: center">
				
                PEMERINTAH '.strtoupper($ar_pemda->s_namakabkota).'
                <br>
                '.strtoupper($ar_pemda->s_namainstansi).'
                <br>
                '.$ar_pemda->s_alamatinstansi.' Telp/Fax '.$ar_pemda->s_notelinstansi.'
				<br> '.$ar_pemda->s_namaibukotakabkota.'
				' . $ar_pemda->s_kodepos . '
			
			</div>
			<hr>				
        </div>		       
        <div class="border_kanan border_kiri font_sepuluh" style="padding-left: 420px; padding-top: 20px;">
            Kepada Yth.<br>
				'.$data['t_nama'].'<br>
				Pemilik NPWPD : '.$data['t_npwpd'].'<br>
            Di 	'.$data['t_alamat'] . ', Kel./Desa ' . $data['s_namakel'] . ', Kec. ' . $data['s_namakec'] . ', Kab. '. $data['t_kabupaten'].'
			<br>
		</div>
        <div class="border_kanan border_kiri font_sepuluh" style="padding-top: 30px; text-align: center">			
            <b style="font-size: 16px"><u>SURAT TEGURAN</u></b><br>            
            Nomor :	........................<br> 
        </div>
        <div class="border_kanan border_kiri font_sepuluh" style="padding-top: 30px; padding-left: 30px; padding-right: 30px; text-indent:0.2in; text-align: justify">
            Berdasarkan data yang ada pada Badan Pendapatan Daerah Kabupaten Banyumas, sampai dengan saat ini Saudara belum melaporkan dan melakukan pembayaran pajak untuk masa pajak 
			' . date('d-m-Y', strtotime($t_masa1)) . ' s/d ' . date('d-m-Y', strtotime($t_masa2)) . '.			
		</div>
		<div class="border_kanan border_kiri font_sepuluh">
			<br>
		</div>
		<div class="border_kanan border_kiri font_sepuluh" style="padding-left: 30px; padding-right: 30px; text-indent:0.2in; text-align: justify">	
            Sehubungan dengan hal tersebut diminta kepada Saudara untuk segera memenuhi kewajiban melaporkan SPTPD menggunakan aplikasi elingspt yang 
			dapat diakses pada alamat website https://elingspt.banyumaskab.go.id dan membayarkan pajak daerahnya langsung ke Kas Daerah melalui Bank Jateng di seluruh wilayah Indonesia
			paling lambat 7 (tujuh) hari setelah diterimanya Surat ini. Pelaporan dan pembayaran pajak selanjutnya agar dilaksanakan setiap bulan setelah masa pajak berakhir, paling lambat tanggal 10. 
			Pembayaran melebihi tanggal tersebut dikenakan sanksi administrasi berupa bunga sebesar 2% (dua prosen) perbulan.
			
		</div>
		<div class="border_kanan border_kiri font_sepuluh">
			<br>
		</div>
		<div class="border_kanan border_kiri font_sepuluh" style="padding-left: 30px; padding-right: 30px; text-indent:0.2in; text-align: justify">	
			Apabila Saudara tidak mengindahkan surat teguran ini, maka kami akan melakukan Penetapan atas Objek Pajak yang saudara miliki secara Jabatan,
            yang akan merugikan Saudara sendiri.
			
		</div>
		<div class="border_kanan border_kiri font_sepuluh">
			<br>
		</div>
		<div class="border_kanan border_kiri font_sepuluh" style="padding-left: 30px; padding-right: 30px; text-indent:0.2in; text-align: justify">
            Demikian untuk diperhatikan dan kewajiban Saudara agar dipenuhi sebagaimana mestinya.
        </div>
		<div class="border_kanan border_kiri font_sepuluh">
			<br>
		</div>
        <div class="border_kanan border_kiri font_sepuluh border_bawah" style="padding: 15px 15px 15px 300px; text-align: center">
           <center>'.$ar_pemda->s_ttdkabkot.', '.tanggal_indo($tgl).'<br> 
		   <b>An. KEPALA BADAN PENDAPATAN DAERAH</b>';
            
            if(!empty($data_get['ttd0'])){
                            $namapejabat1 = $this->MenuHelper()->getnamapejabat($data_get['ttd0']);
                    $html .= '
                        
                            <br><b>'.$namapejabat1['s_jabatanpej'].'

                            <br><br><br><br>
                            <u>&nbsp;'.$namapejabat1['s_namapej'].'&nbsp;</u></b>
                                <br>'.$namapejabat1['s_pangkatpej'].'
								<br>NIP. '.$namapejabat1['s_nippej'].'
                            ';
                }

            $html .= '</center>
        </div>
        <hr>
        <table class="border_bawah border_kanan border_kiri border_atas font_sepuluh" style="width: 100%;">
            <tr>
                <td colspan="3" style="text-align: center">
                    <u>TANDA TERIMA</u>					
                </td>
            </tr>
			
            <tr>
                <td style="width: 30%;padding-left: 25px;">
                    NPWPD
                </td>
                <td style="width: 2%">
                    :
                </td>
                <td>
                    '.$data['t_npwpd'].'
                </td>
            </tr>
            <tr>
                <td style="width: 30%;padding-left: 25px; vertical-align: top;">
                    Nama
                </td>
                <td style="width: 2%">
                    :
                </td>
                <td>
                    '.strtoupper($data['t_nama']).'
                </td>
            </tr>
            <tr>
                <td style="width: 30%;padding-left: 25px; vertical-align: top;">
                    Alamat
                </td>
                <td style="width: 2%">
                    :
                </td>
                <td>
                    '.strtoupper($data['t_alamat']).'
                </td>
            </tr>
            <tr>                
            </tr>
            <tr>
                <td colspan="2">

                </td>
                <td style="text-align: center">
                    Yang Menerima
                    <br><br><br><br>
                </td>
            </tr>
            <tr>
                <td colspan="2" style="padding-bottom: 10px">

                </td>
                <td style="text-align: center; padding-bottom: 10px">
                    (............................)
                </td>
            </tr>
        </table>
    </body>
</html>';
//echo $html;
$mpdf->WriteHTML($html);
$mpdf->Output("cetaksuratteguran_untukmelaporkansptpd.pdf", "I");
    
?>

