<?php

ini_set("max_execution_time", 500);
include($_SERVER['DOCUMENT_ROOT'] . "/" . $this->basePath() . '/public/cetakan/MPDF57/mpdf.php');
$mpdf = new mPDF('utf-8', 'Letter', 0, '', 10, 10, 10, 1, 1, 1, '');

$fontnormal = 'font-size: 12px;';

$html = '';

$html .= '

<html>
    <head>
        <style type="text/css">
            .border_atas {
                border-top: 1px solid black;
                border-collapse: collapse;
            }

            .border_kiri {
                border-left: 1px solid black;
                border-collapse: collapse;
            }

            .border_kanan {
                border-right: 1px solid black;
                border-collapse: collapse;
            }

            .border_bawah {
                border-bottom: 1px solid black;
                border-collapse: collapse;
            }

            .font_besar {
                font-size: 12pt;
            }

            .font_kecil {
                font-size: 10pt;
            }

            .font_lima {
                font-size: 7pt;
            }

            .font_tujuh {
                font-size: 7pt;
            }  

            .font_delapan {
                font-size: 8pt;
            }    

            .font_sembilan {
                font-size: 9pt;
            }    
        </style>
    </head>
    <body>';

$alamatobjek = '';
if (!empty($data['t_alamatobjek'])) {
    $alamatobjek .= ucfirst(strtolower($data['t_alamatobjek']));
}
if ((!empty($data['t_rtobjek'])) || (($data['t_rtobjek'] == '   '))) {
    $alamatobjek .= ' RT ' . $data['t_rtobjek'];
}
if (!empty($data['t_rwobjek'])) {
    $alamatobjek .= ' RW ' . $data['t_rwobjek'];
}
if (!empty($data['s_namakelobjek'])) {
    $alamatobjek .= ' Kel. ' . ucfirst(strtolower($data['s_namakelobjek']));
}
if (!empty($data['s_namakecobjek'])) {
    $alamatobjek .= ' Kec. ' . ucfirst(strtolower($data['s_namakecobjek']));
}
if (!empty($data['t_kabupatenobjek'])) {
    $alamatobjek .= ' Kab. ' . ucfirst(strtolower($data['t_kabupatenobjek']));
}

if($data['t_bidangusaha'] == 2){
    $namawp = $data['t_nama_badan'];
    $alamatwp = '';
    if(!empty($data['t_jalan_badan'])){
        $alamatwp .= $data['t_jalan_badan'];
    }
    if(!empty($data['t_rt_badan'])){
        $alamatwp .= ' RT '.$data['t_rt_badan'];
    }
    if(!empty($data['t_rw_badan'])){
        $alamatwp .= ' RW '.$data['t_rw_badan'];
    }
    if(!empty($data['s_namakel'])){
        $alamatwp .= ' Kel. '.$data['s_namakel'];
    }
    if(!empty($data['s_namakec'])){
        $alamatwp .= ' Kec. '.$data['s_namakec'];
    }
    if(!empty($data['t_kabupaten_badan'])){
        $alamatwp .= ' Kab. '.$data['t_kabupaten_badan'];
    }
}else{
    $namawp = $data['t_nama'];
    $alamatwp = '';
    if(!empty($data['t_alamat'])){
        $alamatwp .= $data['t_alamat'];
    }
    if(!empty($data['t_rt'])){
        $alamatwp .= ' RT '.$data['t_rt'];
    }
    if(!empty($data['t_rw'])){
        $alamatwp .= ' RW '.$data['t_rw'];
    }
    if(!empty($data['s_namakel'])){
        $alamatwp .= ' Kel. '.$data['s_namakel'];
    }
    if(!empty($data['s_namakec'])){
        $alamatwp .= ' Kec. '.$data['s_namakec'];
    }
    if(!empty($data['t_kabupaten'])){
        $alamatwp .= ' Kab. '.$data['t_kabupaten'];
    }
}

$html .= '
    
        <table class="font_delapan" style="width: 100%">
            <tr>
                <td style="width: 10%">
                    <img src="'.$_SERVER['DOCUMENT_ROOT'] . "" . $this->basePath() . "/" . $ar_pemda->s_logo.'" style="width:40px;"  />
                </td>
                <td>
                    PEMERINTAH '. strtoupper($ar_pemda->s_namakabkota).'
                    <br>
                    '.$ar_pemda->s_namainstansi.'
                    <br>
                    '.$ar_pemda->s_alamatinstansi.' Telp/Fax '.$ar_pemda->s_notelinstansi.', '.$ar_pemda->s_namaibukotakabkota.'
                </td>
                
            </tr>
        </table>
        <table class="font_delapan" style="width: 100%;">
            <tr>
                <td width="80" style="padding:0; border-spacing:0px; padding-left: 10px; padding-top: 10px">
                    NPWPD
                </td>
                <td width="20" style="padding:0;border-spacing:0px; padding-top: 10px">
                    :
                </td>
                <td style="padding:0;border-spacing:0px; padding-top: 10px">
                    '.$data['t_npwpd'].'
                </td>
            </tr>
               
            <tr>
                <td style="width: 20%; padding:0; border-spacing:0px; padding-left: 10px">
                    Nama
                </td>
                <td style="width: 2%; padding:0;border-spacing:0px;">
                    :
                </td>
                <td style="padding:0;border-spacing:0px;">
                    '.$namawp.'
                </td>
            </tr>
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 10px">
                    Alamat
                </td>
                <td style="padding:0;border-spacing:0px;">
                    :
                </td>
                <td style="padding:0;border-spacing:0px;">
                    '.$alamatwp .'
                </td>
            </tr>
            
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 10px">
                    Nama Objek
                </td>
                <td style="padding:0;border-spacing:0px;">
                    :
                </td>
                <td style="padding:0;border-spacing:0px;">
                    '.$data['t_namaobjek'].'
                </td>
            </tr>
            <tr>
                <td style="padding:0; border-spacing:0px; padding-left: 10px">
                    Alamat Objek
                </td>
                <td style="padding:0;border-spacing:0px;">
                    :
                </td>
                <td style="padding:0;border-spacing:0px;">
                    '.$alamatobjek .'
                </td>
            </tr>
            <tr>
                <td style="padding:0; border-spacing:0px; padding-bottom: 10px; padding-left: 10px">
                    Jatuh Tempo
                </td>
                <td style="padding:0;border-spacing:0px; padding-bottom: 10px;">
                    :
                </td>
                <td style="padding:0;border-spacing:0px; padding-bottom: 10px;">
                    '.date('d-m-Y', strtotime($data['t_tgljatuhtempo'])).'
                </td>
            </tr>
        </table>
        <table class="font_delapan" style="width: 100%;" >
            <tr>
                <td width="400"></td>
                <td >Kepada Yth.
                    <br>'.$data['t_nama'].'
                    <br>Di '.$data['t_alamat'] . ', Kel./Desa ' . $data['s_namakel'] . ', Kec. '. $data['s_namakec'] .', Kab. '. $data['t_kabupaten'].'
                   
                </td>
            </tr>
        </table>
		<br><br>
        <table class="font_delapan" style="width: 100%; vertical-align: top">
            <tr>
                <td><center><b style="font-size: 16px;"><u>SURAT TEGURAN</u></b><br><br> Nomor : ....................................</center></td>
            </tr>
            <tr>
                <td style="padding-left: 10px; padding-top: 10px; width: 20px;">
                    Menurut pembukuan kami, hingga saat ini Saudara masih mempunyai tunggakan Pajak/Retribusi *) sebagai berikut:
                </td>
                
            </tr>
            <tr>
                <td>
                <table class="border_kanan border_kiri font_delapan" style="width: 100%; margin-left: 20px; margin-right: 20px;">
                    <tr>
                        <td class="border_kanan border_kiri border_bawah border_atas">
                    <center>Jenis Pajak/Retribusi *)</center>
                        </td>
                        <td class="border_kanan border_kiri border_bawah border_atas">
                            <center>Tahun</center>
                        </td>
                        <td class="border_kanan border_kiri border_bawah border_atas">
                            <center>Nomor & Tanggal SKPD, SKPDT, SKPDKB, SKPDKBT, STPD, SKRD, SKRDT, STRD, SK. Keberatan, SK. Pembetulan, SK Putusan Banding *)</center>
                        </td>
                        <td class="border_kanan border_kiri border_bawah border_atas">
                            <center>Tanggal Jatuh Tempo</center>
                        </td>
                        <td class="border_kanan border_kiri border_bawah border_atas">
                            <center>Jumlah Tunggakan Rp.</center>
                        </td>
                    </tr>
                    <tr>
                        <td class="border_kanan border_kiri border_bawah border_atas">
                            '.$data['s_namajenis'].'
                        </td>
                        <td class="border_kanan border_kiri border_bawah border_atas">
                            '.$data['t_periodepajak'].'
                        </td>
                        <td class="border_kanan border_kiri border_bawah border_atas">
                            '.$data['t_namaobjek'].'<br>
                            Nomor SPT : '.$data['t_nourut'].'<br>
                            Tanggal Pendataan : '.$data['t_tglpendataan'].'
                        </td>
                        <td class="border_kanan border_kiri border_bawah border_atas">
                            '.$data['t_tgljatuhtempo'].'
                        </td>
                        <td class="border_kanan border_kiri border_bawah border_atas" align="right">
                            '.number_format($data['t_jmlhpajak'], 0, ',', '.').'
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" class="border_kanan border_kiri border_bawah border_atas">&nbsp;</td>
                        <td class="border_kanan border_kiri border_bawah border_atas"><center><b>Jumlah</b></center></td>
            <td class="border_kanan border_kiri border_bawah border_atas" align="right"><b>'.number_format($data['t_jmlhpajak'], 0, ',', '.').'</b></td>
                    </tr>
                </table>
                </td>    
            </tr>
            
        </table>
        
        <table class="font_delapan" style="width: 100%">
            <tr>
                <td style="width: 5%;padding-top: 10px; padding-bottom: 10px; padding-left: 15px">
                    <center><b style="font-size: 14px;"> Dengan huruf : ( <i>'.$this->MenuHelper()->terbilang($data['t_jmlhpajak']).'</i> ) </b></center>
                </td>
            </tr>
        </table>
        <table class="border_bawah border_kanan border_kiri font_delapan" style="width: 100%">
            <tr>
                <td style="width: 5%;padding-top: 10px; padding-bottom: 10px; padding-left: 15px">
                    Untuk Mencegah tindakan penagihan dengan Surat Priksa berdasarkan Undang-Undang Nomor 19 Tahun 1997, maka diminta kepada Saudara agar melunasi jumlah Tunggakan dalam waktu 7(tujuh) hari setelah tanggal Surat Teguran ini.
                    <br><br>
                    Dalam hal Saudara telah melunasi Tunggakan tersebut diatas, diminta agar Saudara segera melaporkan kepada kami (Seksi Penagihan).
                    <br><br>
                    <table style="width: 100%">
                        <tr>
                            <td width="200" class="border_atas border_bawah border_kanan border_kiri font_delapan">
                        <center>PERHATIAN</center><br>
                        PAJAK HARUS DILUNASI DALAM WAKTU 7 (TUJUH) HARI SETELAH TANGGAL, SURAT TEGURAN INI, SESUDAH BATAS WAKTU ITU TINDAKAN PENAGIHAN AKAN DILANJUTKAN DENGAN PENYERAHAN SURAT PAKSA.
                            </td>
                            <td>
                                '.$ar_pemda->s_ttdkabkot.', '.date('d-m-Y').'<br>
                                <center>An. KEPALA BADAN KEUANGAN DAERAH<br>
                                <center>'.$ar_ttd0['s_jabatanpej'].'<br>                                
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <u> '.$ar_ttd0['s_namapej'].' </u><br>
                                NIP. '.$ar_ttd0['s_nippej'].'</center>
                                
                            </td>
                        </tr>
                    </table>
                    
                </td>
            </tr>
        </table>
        
    </body>
</html>';

$mpdf->WriteHTML($html);
$mpdf->Output("cetaksuratteguran.pdf", "I");

?>

