<html>

<body>
    <?php
    ini_set("max_execution_time", 5000);
    ini_set('memory_limit', '1024M');

    ?>
    <div>
        <div style="border-bottom: 2px double black;">
            <div style='width: 10%; float: left;'>
                <?php $gambar = $_SERVER['DOCUMENT_ROOT'] . "" . $this->basePath() . "/" . $ar_pemda->s_logo; ?>
                <img src="<?= $gambar ?>" style="width:50px;" />
            </div>
            <div style='width: 80%; float: right;padding-right:10%;font-family: sans-serif;text-align: center;'>
                <strong style="font-size: 12pt;">
                    PEMERINTAH <?= strtoupper($ar_pemda->s_namakabkota); ?>
                </strong><br>
                <strong style="font-size: 14pt;">
                    <?= strtoupper($ar_pemda->s_namainstansi); ?> (<?= strtoupper($ar_pemda->s_namasingkatinstansi); ?>)
                </strong><br>
                <span style="font-size: 9pt;">
                    <?= strtoupper($ar_pemda->s_alamatinstansi); ?> Kode Pos <?= $ar_pemda->s_kodepos ?><br><?= strtoupper($ar_pemda->s_namaibukotakabkota) ?>
                </span>
            </div>
        </div>
        <h4 style="text-align: center;font-family: sans-serif;">DATA PAJAK PBB</h4>
        <table width="100%">
            <tr>
                <td colspan="3"><strong>DATA NOP</strong></td>
            </tr>
            <tr>
                <td>Nama SPPT</td>
                <td>:</td>
                <td><?= $data['NM_WP_SPPT'] ?></td>
            </tr>
            <tr>
                <td>Letak</td>
                <td>:</td>
                <td><?= $data['JALAN_OP'] ?></td>
                <td></td>
                <td>RT/RW</td>
                <td width="5%">:</td>
                <td width="20%"><?= $rtop . '/' . $rwop ?></td>
            </tr>
            <tr>
                <td>Kecamatan</td>
                <td>:</td>
                <td><?= $data['NM_KECAMATAN'] ?></td>
                <td></td>
                <td>Kelurahan</td>
                <td>:</td>
                <td><?= $data['NM_KELURAHAN'] ?></td>
            </tr>
            <tr>
                <td>Luas Tanah</td>
                <td>:</td>
                <td><?= $data['LUAS_BUMI_SPPT'] ?></td>
                <td></td>
                <td>NJOP Tanah</td>
                <td>:</td>
                <td><?= number_format($data['NILAI_PER_M2_TANAH'] * 1000, 0, ',', '.') ?></td>
            </tr>

            <tr>
                <td>Luas Bangunan</td>
                <td>:</td>
                <td><?= $data['LUAS_BNG_SPPT'] ?></td>
                <td></td>
                <td>NJOP Bangunan</td>
                <td>:</td>
                <td><?= number_format($data['NILAI_PER_M2_BNG'] * 1000, 0, ',', '.')  ?></td>
            </tr>

            <tr>
                <td><br></td>
            </tr>
            <tr>
                <td colspan="3"><strong>DATA SPPT-PBB</strong></td>
            </tr>
            <?php
            foreach ($datasppt as $row) {
                if (($tahun == 0) || ($tahun < 1)) {
                    if (($bulan == 0) || ($bulan < 1)) {
                        if ($bulan < 0) {
                            $months = 0;
                        } else {
                            if (($hari == 0) || ($hari < 1)) {
                                $months = 0;
                            } else {
                                $months = 1;
                            }
                        }
                    } else {
                        if (($hari == 0) || ($hari < 1)) {
                            $months = $bulan;
                        } else {
                            $months = $bulan + 1;
                        }
                    }
                } else {
                    $jmltahun = $tahun * 12;
                    if ($bulan == 0) {
                        $months = $jmltahun;
                    } elseif ($bulan < 1) {
                        $months = $jmltahun + $bulan;
                    } else {
                        $months = $bulan + $jmltahun;
                    }
                }



                if ($months > 24) {
                    $beda = 24;
                } else {
                    $beda = $months;
                }
                $statusbayar = (!empty($row['TGL_BYR'])) ? '<b style="color:green;">LUNAS (Tgl. ' . date('d-m-Y', strtotime($row['TGL_BYR'])) . ')</b>' : '<b style="color:red;">BELUM BAYAR</b>';

                $denda = $beda * $row['PBB_YG_HARUS_DIBAYAR_SPPT'] * 2 / 100;
                $tunggakan = $row['PBB_YG_HARUS_DIBAYAR_SPPT'] + $denda;
                $dibayar = $row['DENDA_SPPT'] + $row['JML_SPPT_YG_DIBAYAR'];

                echo '<tr>
                <td>Tahun</td>
                <td>:</td>
                <td>' . $row['THN_PAJAK_SPPT'] . '</td>
            </tr>
            <tr>
                <td>Jatuh Tempo</td>
                <td>:</td>
                <td>' . date('d-m-Y', strtotime($row['JATUH_TEMPO'])) . '</td>
            </tr>
            <tr>
                <td>Tunggakan</td>
                <td>:</td>
                <td>Rp.  ' . number_format($row['PBB_YG_HARUS_DIBAYAR_SPPT'], 0, ',', '.') . ",-" . '</td>
            </tr>
            <tr>
                <td>Denda</td>
                <td>:</td>
                <td>Rp.  ' . number_format($denda, 0, ',', '.') . ",-" . '</td>
            </tr>
            <tr>
                <td>Tanggal Bayar</td>
                <td>:</td>
                <td>' . date('d-m-Y', strtotime($row['TGL_BYR'])) . '</td>
            </tr>
            <tr>
                <td>Jumlah Bayar</td>
                <td>:</td>
                <td>Rp.  ' . number_format($dibayar, 0, ',', '.') . ",-" . '</td>
            </tr>
            <tr>
                <td>Status Pembayaran</td>
                <td>:</td>
                <td>' . $statusbayar . '</td>
            </tr>';
            }
            ?>


        </table>
    </div>
</body>

</html>

<style type="text/css" media="print">
    body {
        font-family: sans-serif;
    }

    .font_empatbelas {
        font-size: 14pt;
    }
</style>