<?php
$frm = $this->frm;
$frm->setAttribute('action', $this->url() . '/tambah');
$frm->setAttribute('id', "formtambah");
$frm->setAttribute("data-parsley-validate", "data-parsley-validate");
$frm->prepare();
?>
<div id="page-content-wrapper">
    <div id="page-content">
        <div class="">
            <!-- Parsley -->
            <div id="page-title">
                <h2>
                    Edit Faktor Tujuan dan Volume Pengambilan Air Tanah
                </h2>
            </div>
            <div class="panel">
                <div class="panel-body">
                    <div class="example-box-wrapper">         
                        <div>
                            <?= $this->form()->openTag($frm) ?>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Subyek Pemakai</label>
                                <div class="col-md-7">
                                    <?= $this->formHidden($frm->get('s_idair')) ?>  
                                    <?= $this->formRow($frm->get('s_peruntukan')) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">0-50</label>
                                <div class="col-md-1">
                                    <?= $this->formRow($frm->get('s_nilai1')) ?>
                                </div>
                                <label class="col-sm-2 control-label">>50-500</label>
                                <div class="col-md-1">
                                    <?= $this->formRow($frm->get('s_nilai2')) ?>
                                </div>
                                <label class="col-sm-2 control-label">>500-1.000</label>
                                <div class="col-md-1">
                                    <?= $this->formRow($frm->get('s_nilai3')) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">>1.000-2.500</label>
                                <div class="col-md-1">
                                    <?= $this->formRow($frm->get('s_nilai4')) ?>
                                </div>
                                <label class="col-sm-2 control-label">>2.500-5.000</label>
                                <div class="col-md-1">
                                    <?= $this->formRow($frm->get('s_nilai5')) ?>
                                </div>
                                <label class="col-sm-2 control-label"> > 5.000</label>
                                <div class="col-md-1">
                                    <?= $this->formRow($frm->get('s_nilai6')) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label"></label>
                                <div class="col-md-4">
                                    <?= $this->formInput($frm->get('simpan')) ?> 
                                    <a href="<?= $this->url('setting_air') ?>" class="btn btn-warning btn-sm">Kembali</a>
                                </div>
                            </div>
                            <?= $this->form()->closeTag($frm) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>