<?php
$judul = '<span style="font-size: 24px;"><b>DATA JENIS AIR</b></span>';
$link = '<a href="' . $this->url() . '/tambahvolair" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;TAMBAH
            </a>                                                             
            ';

echo $this->MenuHelper()->headeratas($judul, $link);
?>

<table id="datavolair" cellpadding="0" cellspacing="0" border="0" class="display" width="100%" style="width:100%;">
    <thead>
        <tr class="bg-blue tableheader">

            <th width="15">No</th>
            <th>Jenis Air</th>            
            <th>Kode Vol Air</th>      
            <th>Nama Vol Air</th>   
            <th>Min Vol Air</th>   
            <th>Max Vol Air</th>   
            <th>Nilai Vol Air</th>   
            <th>Tgl Berlaku awal</th>   
            <th>Tgl Berlaku akhir</th>   
            <th>Perintah</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
</tfoot>
</table>
<style type="text/css">
.dataTables_filter {
     display: none;
}
</style> 
<?php
    $idtabel = '#datavolair';
    $url = $this->url().'/dataGridvolair';
    $jmlkolom = 9;
    $seleksi_kolom = "'9'"; //iki data sort di disabel
    $pencarian_bawah = 5;
    
?>
<?= $this->MenuHelper()->fr_datatables($this->basePath(), $idtabel, $url, $jmlkolom, $pencarian_bawah, $seleksi_kolom, null);?>

<?= $this->MenuHelper()->headeratas_end(); ?>                    



<script type="text/javascript">
    
    function hapus(a) {
        var tanya = confirm("Hapus data ini?")
        if (tanya) {
            $.post('<?= $this->url() ?>/hapusvolair/' + a);
        }
        setTimeout(function () {
            dTable.ajax.reload();
        }, 500);
    }

    function cetakdaftarjenisair() {
        window.open('<?= $this->url() ?>/cetakdaftarjenisair');
    }
</script>
