<div class="tab-pane active" id="tab2">
    <div class="row">
        <div class="col-md-5">
            <select id="ttdmasalteguran" class="form-control">
                <?php foreach ($ar_ttd0 as $row) { ?>
                    <option value="<?= $row['s_idpej'] ?>"><?= $row['s_namapej'] . " || " . $row['s_jabatanpej'] ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="col-sm-2">
            <button type='button' class='btn btn-danger btn-md' onclick='cetakteguranmasal()'><span class='glyph-icon icon-print'></span> CETAK SURAT</button>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">
            <select class="form-control input-sm" id="combocari" onchange="calldatagrid()">
                <option value="t_namaobjek">Nama OP</option>
                <option value="t_nop">NIOP</option>
                <option value="t_alamatlengkapobjek">Alamat OP</option>
                <option value="t_npwpdwp">NPWPD</option>
                <option value="t_namawp">Nama</option>
            </select>
        </div>
        <div class="col-sm-3">
            <div class="input-group input-group-sm">
                <input type="text" placeholder="Cari" class="form-control pull-right" name="kolomcari" id="kolomcari" onkeyup="calldatagrid()">
                <div class="input-group-btn combooperatorwpc">
                    <select data-toggle="dropdown" class="btn btn-default dropdown-toggle" id="combooperator" onchange="calldatagrid()" style="text-align: left;">
                        <option value="">Pilih</option>
                        <option value="carisama">=</option>
                        <option value="carilike">%</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-sm-3"></div>
        <div class="col-sm-2">
            <span class="hiddene">
                <select class="form-control input-sm" id="combosorting" onchange="calldatagrid()">
                    <option value="">Pilih Urutan</option>
                    <option value="t_namaobjek">Nama OP</option>
                    <option value="t_nop">NIOP</option>
                    <option value="t_alamatlengkapobjek">Alamat OP</option>
                    <option value="t_npwpdwp">NPWPD</option>
                    <option value="t_namawp">Nama</option>
                </select>
            </span>
        </div>
        <div class="col-sm-2">
            <span class="hiddene">
                <div class="form-inline">
                    <div class="radio">
                        <label>
                            <input type="radio" value="ASC" id="sortasc" name="sortere" onclick="calldatagrid()">
                            Terkecil
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" checked="" value="DESC" id="sortdesc" name="sortere" onclick="calldatagrid()">
                            Terbesar
                        </label>
                    </div>
                </div>
            </span>
        </div>
    </div>
    <div class="example-box-wrapper">
        <div class="scroll-columns">
            <table class="table table-condensed table-bordered cf tableTeguran" style="font-size: 11px; color: black;">
                <thead class="cf" style="background-color: blue">
                    <tr class="bg-blue">
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            No.
                        </th>          
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            <input type="checkbox" id="selectAll" >
                        </th>        
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            NIOP
                        </th> 
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            Nama Objek 
                        </th> 
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            Alamat Objek
                        </th>         
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            NPWPD
                        </th> 
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            Nama 
                        </th>     
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            Jenis Pajak
                        </th>     
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            Masa Pajak
                        </th>     
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            No. & Tgl. Teguran
                        </th> 
                        <th style="background-color: #00BCA4; color: white; text-align: center">
                            #
                        </th> 
                    </tr>
                </thead>
                <tbody id="body_grid">
                </tbody>
            </table>
            <div class="row">
                <div class="col-sm-3 text-left">
                    <span>
                        <select id="rows" class="form-control" style="width: 30%" onchange="calldatagrid(1)">
                            <option value="10">10</option>
                            <option value="20">20</option>
                            <option value="30">30</option>
                            <option value="40">40</option>
                            <option value="50">50</option>
                        </select>
                    </span>
                </div>
                <div class="col-sm-6" style="text-align: center">
                    <center>
                        <div id="paginatore"></div>
                        <input type="hidden" id="s_idjenis" value="<?= $s_idjenis ?>">
                        <input type="hidden" id="page" value="1">
                    </center>
                </div>
                <div class="col-sm-3 text-right">
                    <span>
                        <p>
                            <b style="font-size: 13px; color: orangered"><span id="awaldata"></span> s/d <span id="akhirdata"></span> Dari <span id="total_data"></span> Data</b>
                        </p>  
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        calldatagrid();
    });

    function calldatagrid(direction) {
        if ($("#combocari").val().length == 0)
            par1 = undefined;
        else
            par1 = $("#combocari").val()
        if ($("#kolomcari").val().length == 0)
            par2 = undefined;
        else
            par2 = $("#kolomcari").val()
        if ($("#combosorting").val().length == 0)
            par3 = undefined;
        else
            par3 = $("#combosorting").val()
        if (document.getElementById("sortasc").checked)
            par4 = $("#sortasc").val()
        else
            par4 = undefined;
        if (document.getElementById("sortdesc").checked)
            par5 = $("#sortdesc").val()
        else
            par5 = undefined;
        if ($("#combooperator").val().length == 0)
            par6 = undefined;
        else
            par6 = $("#combooperator").val()
        datagrid($("#page").val(), $("#rows").val(), direction, par1, par2, par3, par4, par5, par6);
    }

    function datagrid(pagewp, row, direction, par1, par2, par3, par4, par5, par6) {
        $.get('<?= $this->url() ?>/dataGridSuratTeguran/' + pagewp + '/' + row + '/' + direction + '/' + par1 + '/' + par2 + '/' + par3 + '/' + par4 + '/' + par5 + '/' + par6, function (data) {
            var aa = JSON.parse(data)
            $("#body_grid").html(aa.gridwp);
            $("#rows").val(aa.rowswp);
            $("#page").val(aa.pagewp);
            $("#total_data").html(": " + aa.countwp);
            $("#total_halaman").html(": " + aa.total_halamanwp);
            $("#paginatore").html(aa.paginatorewp);
            $("#awaldata").html(aa.awaldatawp);
            $("#akhirdata").html(aa.akhirdatawp);
        });
    }

    function cetakteguranmasal() {
        var checkValues = $('input[name=t_idteguran]:checked').map(function ()
        {
            return $(this).val();
        }).get();
        if (checkValues == '') {
            $('#AlertCetakTeguran').modal('show');
        } else {
            window.open('<?= $this->url() ?>/cetaksuratteguran?idobjekdbelumlapor=' + checkValues + "&ttdmasalteguran=" + $("#ttdmasalteguran").val() + "&s_idjenis=" + $("#s_idjenis").val());
        }
    }
</script>
<div id="AlertCetakTeguran" class="modal fade" role="dialog">
    <div class="modal-dialog modal-xs" style="width: 300px">
        <div class="modal-content">
            <div class="modal-header bg-danger">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel"><span class="glyph-icon icon-warning"></span><b> Peringatan</b></h4>
            </div>
            <div class="modal-body">
                <p style="font-weight: bold">Centang Minimal 1 Baris Data.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-xs" data-dismiss="modal"><span class="glyph-icon icon-close"></span> Close</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#selectAll').click(function (event) {
            if (this.checked) {
                // Iterate each checkbox
                $(':checkbox').each(function () {
                    this.checked = true;
                }).change();
            } else {
                $(':checkbox').each(function () {
                    this.checked = false;
                }).change();
            }
        });

        $('.tableTeguran tr').click(function (event) {
            if (event.target.type !== 'checkbox') {
                $(':checkbox', this).trigger('click');
            }
        });

        $("input[type='checkbox']").change(function (e) {
            if ($(this).is(":checked")) {
                $(this).closest('tr').addClass("highlight_row");
            } else {
                $(this).closest('tr').removeClass("highlight_row");
            }
        });
    });
</script>
<style type="text/css">
    .combooperatorwpc select {
        border: 0 !important;  /*Removes border*/
        -webkit-appearance: none;  /*Removes default chrome and safari style*/
        -moz-appearance: none; /* Removes Default Firefox style*/
        appearance:none;
        /*background: #E08E0B url(img/select-arrow.png) no-repeat 90% center;*/
        background: #E08E0B no-repeat 90% center;
        text-indent: 0.01px; /* Removes default arrow from firefox*/
        color: #FFF;
    }		
    .tableTeguran {
        width: 100%;
        border-collapse: collapse;
    }
    .tableTeguran tr:hover {
        background: #C6E746;
    }
    .tableTeguran td {
        border: 1px solid #eee;
    }
    .highlight_row {
        background: #eee;
    }
</style>
