<html>
    <head>
        <style type="text/css">
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
        </style>
    </head>
    <body>
        <div class="printarea">            
            <h2 style="text-align: center">DAFTAR TARGET</h2>
            Tahun : <?= $data->s_tahuntarget ?><br>
            Keterangan : <?= $data->s_keterangantarget ?>
            <table width="100%" style="margin-top:10px;">
                <tr style="background:#ccc;">
                    <th style="width: 5%; text-align: center">
                        No.
                    </th>
                    <th style="text-align: center">
                        Kode Rekening 
                    </th>
                    <th style="text-align: center">
                        Nama Rekening
                    </th>
                    <th style="text-align: center">
                        Jumlah Target (Rp)
                    </th>
                </tr>
                <?php
                $counter = 1;
                foreach ($this->datatarget as $k => $v) {
                    ?>
                    <tr>
                        <td style="text-align: center">
                            <?= $counter ?>
                        </td>
                        <td align="left">
                            <?=$v['korek']?>
                        </td>
                        <td align="left">
                            <?=$v['s_namakorek']?>
                        </td>
                        <td align="right">
                            <?= number_format($v['s_targetjumlah'])?>
                        </td>
                    </tr>
                    <?php
                    $counter++;
                }
                ?>
            </table>
        </div>
    </body>
</html>

