<?php
$frm = $this->frm;
$frm->setAttribute('action', $this->url() . '/tambah');
$frm->setAttribute('id', "formtambah");
$frm->prepare();
?>
<div id="page-content-wrapper">
    <div id="page-content">
        <div class="">
            <!-- Parsley -->
            <div id="page-title">
                <h2>
                    Setting Target Realisasi
                </h2>
            </div>
            <div class="panel">
                <div class="panel-body">
                    <div class="example-box-wrapper">         
                        <div>
                            <?= $this->form()->openTag($frm) ?>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Tahun</label>
                                <div class="col-md-1">
                                    <?= $this->formHidden($frm->get('s_idtarget')) ?>  
                                    <?= $this->formText($frm->get('s_tahuntarget')) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Status</label>
                                <div class="col-md-4">
                                    <?= $this->formSelect($frm->get('s_statustarget')) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label">Keterangan</label>
                                <div class="col-md-4">
                                    <?= $this->formTextarea($frm->get('s_keterangantarget')) ?>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <label class="col-sm-2 control-label"></label>
                                <div class="col-md-4">
                                    <?= $this->formInput($frm->get('simpan')) ?> 
                                    <a href="<?= $this->url('setting_target') ?>" class="btn btn-warning btn-sm">Kembali</a>
                                </div>
                            </div>
                            <?= $this->form()->closeTag($frm) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>