<div id="page-content-wrapper">
    <div id="page-content" style="background-color: #DFF0D8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Setting Target OPD
                </h4>
            </div>

            <div class="panel-body">
                <button class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal">
                    Tambah
                </button>

                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header bg-orange">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Form Target</h4>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <input hidden="" name="s_idkelompoktarget" id="s_idkelompoktarget">
                                        <label class="col-sm-4 control-label">OPD/Dinas</label>
                                        <div class="col-md-7">
                                            <select class="form-control" name="s_idsatker" id="s_idsatker">
                                                <option value="">--Silahkan Pilih--</option>
                                                <?php foreach ($dataopd as $r) { ?>
                                                    <option value="<?= $r['s_idsatker'] ?>"> <?= $r['s_kodesatker'] . '||' . $r['s_namasatker'] ?></option>
                                                <?php }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-4 control-label">Tahun Target</label>
                                        <div class="col-md-7">
                                            <input type="text" class="form-control" name="s_tahuntarget" id="s_tahuntarget">
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-4 control-label">Keterangan</label>
                                        <div class="col-md-7">
                                            <input type="text" class="form-control" name="s_namatarget" id="s_namatarget">
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Batal</button>
                                <a class="btn btn-primary" onclick="simpan()">Simpan</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- <a href="<?= $this->url() ?>/tambahtargetopd" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp;&nbsp;Tambah</a> -->
                <!--                <button class="btn btn-warning btn-xs" onclick="cetakdaftartarget();">
                    <span class="glyphicon glyphicon-print"></span>&nbsp;&nbsp;Cetak Daftar Target
                </button>-->
                <div class="row" style="margin-top: 10px;margin-bottom: 10px;">
                    <div style="display: none">
                        <div class="col-sm-2">
                            <select class="form-control input-sm" id="combocari" onchange="calldatagrid()">
                                <option value="s_tahuntarget">Tahun Target</option>
                                <option value="s_namatargetjenis">Status Target</option>
                                <option value="s_keterangantarget">Keterangan Target</option>
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <div class="input-group input-group-sm">
                                <input type="text" placeholder="Cari" class="form-control pull-right" name="kolomcari" id="kolomcari" onkeyup="calldatagrid()">
                                <div class="input-group-btn combooperatorc">
                                    <select data-toggle="dropdown" class="btn btn-default dropdown-toggle" id="combooperator" onchange="calldatagrid()" style="text-align: left;">
                                        <option value="">Pilih</option>
                                        <option value="carisama">=</option>
                                        <option value="carilike">%</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3"></div>
                        <div class="col-sm-2">
                            <span class="hiddene">
                                <select class="form-control input-sm" id="combosorting" onchange="calldatagrid()">
                                    <option value="s_tahuntarget">Tahun Target</option>
                                    <option value="s_namatargetjenis">Status Target</option>
                                    <option value="s_keterangantarget">Keterangan Target</option>
                                </select>
                            </span>
                        </div>
                        <div class="col-sm-2">
                            <span class="hiddene">
                                <div class="form-inline">
                                    <div class="radio">
                                        <label>
                                            <input type="radio" value="ASC" id="sortasc" name="sortere" onclick="calldatagrid()">
                                            Terkecil
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" checked="" value="DESC" id="sortdesc" name="sortere" onclick="calldatagrid()">
                                            Terbesar
                                        </label>
                                    </div>
                                </div>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="example-box-wrapper">
                    <div class="remove-columns">
                        <table class="table table-striped table-condensed table-bordered cf" style="font-size: 11px; color: black">
                            <thead class="cf" style="background-color: blue">
                                <tr class="bg-blue">
                                    <th style="background-color: #00BCA4; color: white; text-align: center; width: 10%">
                                        No.
                                    </th>
                                    <th style="background-color: #00BCA4; color: white; text-align: center;">
                                        Tahun
                                    </th>
                                    <th style="background-color: #00BCA4; color: white; text-align: center;">
                                        Keterangan
                                    </th>
                                    <th style="background-color: #00BCA4; color: white; text-align: center;">
                                        Nama OPD
                                    </th>

                                    <th style="width: 35%; background-color: #00BCA4; color: white; text-align: center">
                                        #
                                    </th>
                                </tr>
                            </thead>
                            <tbody id="body_grid">
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="5" class="text-center">
                                        <div class="row">
                                            <div class="col-sm-3 text-left">
                                                <span class="hiddene">
                                                    <select id="rows" class="form-control" style="width: 30%" onchange="calldatagrid(1)">
                                                        <option value="10">10</option>
                                                        <option value="20">20</option>
                                                        <option value="30">30</option>
                                                        <option value="40">40</option>
                                                        <option value="50">50</option>
                                                    </select>
                                                </span>
                                            </div>
                                            <div class="col-sm-6" style="text-align: center">
                                                <center>
                                                    <div id="paginatore"></div>
                                                    <input type="hidden" id="page" value="1">
                                                </center>
                                            </div>
                                            <div class="col-sm-3 text-right">
                                                <span class="hiddene">
                                                    <p>
                                                        <b style="font-size: 13px; color: orangered"><span id="awaldata"></span> s/d <span id="akhirdata"></span> Dari <span id="total_data"></span> Data</b>
                                                    </p>
                                                </span>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        calldatagrid();
    });

    function calldatagrid(direction) {
        if ($("#combocari").val().length == 0)
            par1 = undefined;
        else
            par1 = $("#combocari").val()
        if ($("#kolomcari").val().length == 0)
            par2 = undefined;
        else
            par2 = $("#kolomcari").val()
        if ($("#combosorting").val().length == 0)
            par3 = undefined;
        else
            par3 = $("#combosorting").val()
        if (document.getElementById("sortasc").checked)
            par4 = $("#sortasc").val()
        else
            par4 = undefined;
        if (document.getElementById("sortdesc").checked)
            par5 = $("#sortdesc").val()
        else
            par5 = undefined;
        if ($("#combooperator").val().length == 0)
            par6 = undefined;
        else
            par6 = $("#combooperator").val()
        datagrid($("#page").val(), $("#rows").val(), direction, par1, par2, par3, par4, par5, par6);
    }

    function datagrid(page, row, direction, par1, par2, par3, par4, par5, par6) {
        $.get('<?= $this->url() ?>/dataGridTargetOPD/' + page + '/' + row + '/' + direction + '/' + par1 + '/' + par2 + '/' + par3 + '/' + par4 + '/' + par5 + '/' + par6, function(data) {
            var aa = JSON.parse(data)
            $("#body_grid").html(aa.grid);
            $("#rows").val(aa.rows);
            $("#page").val(aa.page);
            $("#total_data").html(": " + aa.count);
            $("#total_halaman").html(": " + aa.total_halaman);
            $("#paginatore").html(aa.paginatore);
            $("#awaldata").html(aa.awaldata);
            $("#akhirdata").html(aa.akhirdata);
        });
    }

    function getdatatargetopd(id) {

        $.post('<?= $this->url() ?>/tambahtargetopd', {
            s_idkelompoktarget: id
        }, function(data) {
            var aa = JSON.parse(data);
            $('#s_tahuntarget').val(aa.s_tahuntarget);
            $('#s_namatarget').val(aa.s_namatarget);
            $('#s_idkelompoktarget').val(aa.s_idkelompoktarget);
            $('#s_idsatker').html(aa.opsi);
            $('#myModal').modal('show');
        });
    }

    function simpan() {
        if ($('#s_idsatker').val() == '' || $('#s_namatarget').val() == '' || $('#s_tahuntarget').val() == '') {
            alert("Perikasa Inputan Kembali !");
        } else {
            $.post('<?= $this->url() ?>/simpantargetopd', {
                s_idkelompoktarget: $('#s_idkelompoktarget').val(),
                s_tahuntarget: $('#s_tahuntarget').val(),
                s_namatarget: $('#s_namatarget').val(),
                s_idsatker: $('#s_idsatker').val()
            }, function(data) {
                var aa = JSON.parse(data);
                $('#myModal').modal('hide');
                $('#s_tahuntarget').val('');
                $('#s_namatarget').val('');
                $('#s_idsatker').val('');
                calldatagrid();
            });
        }
    }

    function hapustarget(id) {
        $.post('<?= $this->url() ?>/deletetargetopd', {
            s_idkelompoktarget: id
        }, function(data) {
            var aa = JSON.parse(data);
            datagrid();
        });

    }
</script>

<style type="text/css">
    .combooperatorc select {
        border: 0 !important;
        /*Removes border*/
        -webkit-appearance: none;
        /*Removes default chrome and safari style*/
        -moz-appearance: none;
        /* Removes Default Firefox style*/
        appearance: none;
        /*background: #E08E0B url(img/select-arrow.png) no-repeat 90% center;*/
        background: #E08E0B no-repeat 90% center;
        text-indent: 0.01px;
        /* Removes default arrow from firefox*/
        color: #FFF;
    }
</style>