<div id="page-content-wrapper">
    <div id="page-content" style="background-color: #DFF0D8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Setting Detail Target OPD
                </h4>
            </div>

            <div class="panel-body">
                <button class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal">
                    Tambah
                </button>
                <a href="<?= $this->url('setting_targetopd') ?>" class="btn btn-success btn-md">
                    Selesai
                </a>
                <input type="hidden" value="<?= $s_idkelompoktarget ?>" name="" id="s_idkelompoktarget">
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header bg-orange">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Form Detail Target</h4>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <input type="hidden" name="s_idtargetsatker" id="s_idtargetsatker">
                                        <label class="col-sm-4 control-label">Rekening</label>
                                        <div class="col-md-7">
                                            <select class="form-control" name="s_idkorek" id="s_idkorek">
                                                <option value="">--Silahkan Pilih--</option>
                                                <?php foreach ($korek as $r) { ?>
                                                    <option value="<?= $r['s_idkorek'] ?>"> <?= $r['korek'] . '||' . $r['s_namakorek'] ?></option>
                                                <?php }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <label class="col-sm-4 control-label">Target</label>
                                        <div class="col-md-7">
                                            <input type="text" class="form-control" name="s_target" id="s_target">
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Batal</button>
                                <a class="btn btn-primary" onclick="simpan()">Simpan</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="example-box-wrapper">
                    <div class="remove-columns">
                        <table class="table table-striped table-condensed table-bordered cf" style="font-size: 11px; color: black">
                            <thead class="cf" style="background-color: blue">
                                <tr class="bg-blue">
                                    <th style="background-color: #00BCA4; color: white; text-align: center; width: 10%">
                                        No.
                                    </th>
                                    <th style="background-color: #00BCA4; color: white; text-align: center;">
                                        Kode Rekening
                                    </th>
                                    <th style="background-color: #00BCA4; color: white; text-align: center;">
                                        Nama Rekening
                                    </th>
                                    <th style="background-color: #00BCA4; color: white; text-align: center;">
                                        Target
                                    </th>
                                    <th style="width: 35%; background-color: #00BCA4; color: white; text-align: center">
                                        #
                                    </th>
                                </tr>
                            </thead>
                            <tbody id="body_grid">
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        datagrid();
    });


    function datagrid() {
        $.post('<?= $this->url() ?>/dataGriddetailTargetOPD', {
            s_idkelompoktarget: $('#s_idkelompoktarget').val()
        }, function(data) {
            var aa = JSON.parse(data);
            $("#body_grid").html(aa.grid);

        });
    }

    function getdatasatker(id) {
        $.post('<?= $this->url() ?>/editdetailtargetopd', {
            s_idtargetsatker: id
        }, function(data) {
            var aa = JSON.parse(data);
            $('#s_target').val(aa.s_target);
            $('#s_idtargetsatker').val(aa.s_idtargetsatker);
            $('#s_idkorek').html(aa.opsi);
            $('#myModal').modal('show');
        });
    }

    function simpan() {
        if ($('#s_ta').val() == '' || $('#s_idkorek').val() == '') {
            alert("Perikasa Inputan Kembali !");
        } else {
            $.post('<?= $this->url() ?>/simpandetailtargetopd', {
                s_idkelompoktarget: $('#s_idkelompoktarget').val(),
                s_idkorek: $('#s_idkorek').val(),
                s_idtargetsatker: $('#s_idtargetsatker').val(),
                s_target: $('#s_target').val()
            }, function(data) {
                var aa = JSON.parse(data);
                $('#myModal').modal('hide');
                $('#s_idkorek').val('');
                $('#s_target').val('');
                $('#s_idtargetsatker').val('');
                datagrid();
            });
        }
    }

    function hapusdetail(id) {
        $.post('<?= $this->url() ?>/deletedetailtargetopd', {
            s_idtargetsatker: id
        }, function(data) {
            var aa = JSON.parse(data);
            datagrid();
        });

    }
</script>

<style type="text/css">
    .combooperatorc select {
        border: 0 !important;
        /*Removes border*/
        -webkit-appearance: none;
        /*Removes default chrome and safari style*/
        -moz-appearance: none;
        /* Removes Default Firefox style*/
        appearance: none;
        /*background: #E08E0B url(img/select-arrow.png) no-repeat 90% center;*/
        background: #E08E0B no-repeat 90% center;
        text-indent: 0.01px;
        /* Removes default arrow from firefox*/
        color: #FFF;
    }
</style>